import type { ApiSnapshot, ParamModel, TypeNode } from '../api/model';
import { type DelegateDefinition, deriveDelegates } from '../derive/delegates';
import { dartdocToJsdoc } from './doc';
import type { DeclaredSurface } from './emit';
import { valueFormTsType } from './prop-type';
import { writtenParamName } from './signature';
import { tsTypeOf } from './ts-types';

/** The name each member's first parameter takes: the value being written. */
export const SELF_PARAM = 'self';

const MODULE_HEADER = (frameworkVersion: string): string =>
  '// GENERATED by `bun run generate` from ref/api.json — do not edit.\n' +
  `// Flutter ${frameworkVersion}`;

const IMPLEMENTATIONS_DOC = [
  '/**',
  ' * What writing one of the classes an app writes itself means.',
  ' *',
  ' * Flutter builds none of these and hands over none of them: being one is',
  " * writing one. Each entry is that class's abstract surface, and every",
  ' * member is handed the value itself first — `self` — so what the class',
  ' * inherits is in reach from the members that need it.',
  ' */',
].join('\n');

/**
 * The type a member's parameter takes.
 *
 * A parameter is a value Flutter hands the implementation — the size to lay
 * out at, the delegate to compare against — so it is the type itself, with
 * every member the surface declares on it. A shorthand would be the wrong
 * way round: nothing is being written here, it is being read.
 */
const handedType = (param: ParamModel): string =>
  `${writtenParamName(param.name)}: ${tsTypeOf(param.type)}`;

/**
 * The type a member answers with.
 *
 * What the implementation returns is written, so it takes exactly what a
 * prop of that type takes: `{ … }` for a shape, a keyword for a form.
 */
const writtenType = (node: TypeNode, formNames: ReadonlySet<string>): string =>
  valueFormTsType(node, formNames);

const memberLines = (
  delegate: DelegateDefinition,
  formNames: ReadonlySet<string>,
): string[] => {
  const written = [
    ...delegate.getters.map((getter) => ({
      name: getter.name,
      doc: getter.doc,
      params: [] as ParamModel[],
      returnType: getter.type,
    })),
    ...delegate.methods.map((method) => ({
      name: method.name,
      doc: method.doc,
      params: method.params,
      returnType: method.returnType,
    })),
  ].sort((first, second) => first.name.localeCompare(second.name));
  return written.flatMap((member) => {
    const params = [
      `${SELF_PARAM}: ${delegate.name}`,
      ...member.params.map(handedType),
    ].join(', ');
    const jsdoc = dartdocToJsdoc(member.doc, '    ');
    const signature =
      `    ${member.name}: (${params}) => ` +
      `${writtenType(member.returnType, formNames)};`;
    return jsdoc === '' ? [signature] : [jsdoc, signature];
  });
};

/** A name in a rendered type: `ReadonlyMap<Object, DataRow>` names two. */
const TYPE_NAME = /\b[A-Z][A-Za-z0-9_]*\b/g;

/**
 * A name TypeScript itself declares, which the widgets module does not.
 *
 * `Promise<void>` is how a Dart `Future` reads and `AsyncIterable` how a
 * `Stream` does; both are the language's own, so importing them would ask
 * the generated module for a type it never wrote.
 */
const BUILT_IN_TYPES: ReadonlySet<string> = new Set([
  'Promise',
  'AsyncIterable',
  'Record',
  'ReadonlyMap',
  'Map',
  'Object',
]);

/** What the runtime declares rather than the generated surface. */
const RUNTIME_TYPES: ReadonlySet<string> = new Set([
  'FlutterElement',
  'FlutterChild',
  'FlutterChildren',
]);

/** Every type a delegate's declaration mentions, whoever declares it. */
const mentionedNames = (
  delegate: DelegateDefinition,
  formNames: ReadonlySet<string>,
): Set<string> => {
  const names = new Set<string>([delegate.name]);
  const collect = (rendered: string): void => {
    for (const name of rendered.match(TYPE_NAME) ?? []) {
      if (!BUILT_IN_TYPES.has(name)) {
        names.add(name);
      }
    }
  };
  for (const method of delegate.methods) {
    collect(writtenType(method.returnType, formNames));
    for (const param of method.params) {
      collect(tsTypeOf(param.type));
    }
  }
  for (const getter of delegate.getters) {
    collect(writtenType(getter.type, formNames));
  }
  return names;
};

/**
 * Whether every type this delegate's members mention has a name.
 *
 * A member typed as something no module declares could not be written at
 * all, so the class is not offered: saying it can be written and handing
 * over a declaration that does not compile would be the worse answer of
 * the two.
 */
const isNameable = (
  names: ReadonlySet<string>,
  surface: DeclaredSurface,
): boolean =>
  [...names].every(
    (name) =>
      RUNTIME_TYPES.has(name) ||
      surface.named.has(name) ||
      surface.enums.has(name) ||
      (name.endsWith('Value') &&
        surface.formNames.has(name.slice(0, -'Value'.length))) ||
      (name.endsWith('Object') &&
        surface.formNames.has(name.slice(0, -'Object'.length))),
  );

/**
 * The module that says what writing a delegate means.
 *
 * `defineDelegate('DataTableSource', { … })` is checked against these two
 * maps: the first says what the members are, the second what writing them
 * hands back. Both are derived from the SDK, so a delegate Flutter adds is
 * one an app can write as soon as the snapshot knows about it.
 */
export const emitDelegatesFile = (
  snapshot: ApiSnapshot,
  surface: DeclaredSurface,
): string => {
  const { formNames } = surface;
  const mentioned = new Map(
    deriveDelegates(snapshot).map((delegate) => [
      delegate,
      mentionedNames(delegate, formNames),
    ]),
  );
  const delegates = [...mentioned.keys()].filter((delegate) =>
    isNameable(mentioned.get(delegate) ?? new Set(), surface),
  );
  const mentionedBy = (kept: readonly DelegateDefinition[]): Set<string> =>
    new Set(kept.flatMap((delegate) => [...(mentioned.get(delegate) ?? [])]));
  const names = [...mentionedBy(delegates)];
  const byName = (first: string, second: string): number =>
    first.localeCompare(second);
  const fromWidgets = names
    .filter((name) => !RUNTIME_TYPES.has(name))
    .sort(byName);
  const fromRuntime = names
    .filter((name) => RUNTIME_TYPES.has(name))
    .sort(byName);
  const blocks = [
    MODULE_HEADER(snapshot.meta.frameworkVersion),
    ...(fromRuntime.length === 0
      ? []
      : [
          `import type { ${fromRuntime.join(', ')} } from ` +
            "'../runtime/types';",
        ]),
    ...(fromWidgets.length === 0
      ? []
      : [`import type { ${fromWidgets.join(', ')} } from './widgets';`]),
    [
      IMPLEMENTATIONS_DOC,
      `export interface DelegateImplementations {${
        delegates.length === 0 ? '}' : ''
      }`,
      ...delegates.flatMap((delegate) => {
        const jsdoc = dartdocToJsdoc(delegate.doc, '  ');
        return [
          ...(jsdoc === '' ? [] : [jsdoc]),
          `  ${delegate.name}: {`,
          ...memberLines(delegate, formNames),
          '  };',
        ];
      }),
      ...(delegates.length === 0 ? [] : ['}']),
    ].join('\n'),
    [
      '/** What `defineDelegate` hands back for each name it is given. */',
      `export interface Delegates {${delegates.length === 0 ? '}' : ''}`,
      ...delegates.map((delegate) => `  ${delegate.name}: ${delegate.name};`),
      ...(delegates.length === 0 ? [] : ['}']),
    ].join('\n'),
  ];
  return `${blocks.join('\n\n')}\n`;
};
