import type {
  ApiSnapshot,
  ConstantModel,
  Entity,
  ParamModel,
  TypeNode,
  WidgetEntity,
} from '../api/model';
import type { ChildrenSlot, SlotMap, WidgetSlots } from '../derive/slots';
import { dartdocToJsdoc } from './doc';
import { CHILDREN_TS_TYPES, propTsType } from './prop-type';
import { jsxPropName } from './renames';
import { tsTypeOf } from './ts-types';

const EMPTY_SLOTS: WidgetSlots = { children: null, slots: [] };

const header = (frameworkVersion: string): string =>
  '// GENERATED by `bun run generate` from ref/api.json — do not edit.\n' +
  `// Flutter ${frameworkVersion}`;

const collectRefs = (
  node: TypeNode,
  named: Set<string>,
  enums: Set<string>,
): void => {
  switch (node.kind) {
    case 'named':
      named.add(node.name);
      break;
    case 'enum':
      enums.add(node.name);
      break;
    case 'nullable':
      collectRefs(node.inner, named, enums);
      break;
    case 'list':
    case 'set':
    case 'future':
      collectRefs(node.item, named, enums);
      break;
    case 'map':
      collectRefs(node.key, named, enums);
      collectRefs(node.value, named, enums);
      break;
    case 'function':
      collectRefs(node.returnType, named, enums);
      for (const param of node.params) {
        collectRefs(param.type, named, enums);
      }
      break;
    default:
      break;
  }
};

const defaultConstructorOf = (
  widget: WidgetEntity,
): WidgetEntity['constructors'][number] | undefined =>
  widget.constructors.find((constructor) => constructor.name === '');

const docWithDeprecation = (param: ParamModel): string => {
  if (!param.deprecated) {
    return param.doc;
  }
  return param.doc === ''
    ? '/// @deprecated'
    : `${param.doc}\n///\n/// @deprecated`;
};

const propLine = (
  param: ParamModel,
  widgetSlots: WidgetSlots,
  takenNames: ReadonlySet<string>,
): string => {
  const tsType = propTsType(param, widgetSlots);
  const optional = param.required ? '' : '?';
  const name = jsxPropName(param.name, takenNames);
  const jsdoc = dartdocToJsdoc(docWithDeprecation(param), '  ');
  const declaration = `  ${name}${optional}: ${tsType};`;
  return jsdoc === '' ? declaration : `${jsdoc}\n${declaration}`;
};

const childrenLine = (children: ChildrenSlot, params: ParamModel[]): string => {
  const source = params.find((param) => param.name === children.param);
  const optional = source?.required === true ? '' : '?';
  const jsdoc = source === undefined ? '' : dartdocToJsdoc(source.doc, '  ');
  const declaration = `  children${optional}: ${CHILDREN_TS_TYPES[children.kind]};`;
  return jsdoc === '' ? declaration : `${jsdoc}\n${declaration}`;
};

const widgetBlocks = (
  widget: WidgetEntity,
  widgetSlots: WidgetSlots,
): string[] => {
  const constructor = defaultConstructorOf(widget);
  if (constructor === undefined) {
    return [];
  }

  const takenNames = new Set(constructor.params.map((param) => param.name));
  const lines: string[] = [];
  if (widgetSlots.children !== null) {
    lines.push(childrenLine(widgetSlots.children, constructor.params));
  }
  for (const param of constructor.params) {
    if (param.name === 'key' || param.name === widgetSlots.children?.param) {
      continue;
    }
    lines.push(propLine(param, widgetSlots, takenNames));
  }

  const doc = dartdocToJsdoc(widget.doc, '');
  const docPrefix = doc === '' ? '' : `${doc}\n`;
  const propsInterface =
    `${docPrefix}export interface ${widget.name}Props {\n` +
    `${lines.join('\n')}\n}`;
  const component =
    widget.constants.length === 0
      ? `${docPrefix}export const ${widget.name}: ` +
        `FlutterComponent<${widget.name}Props> =\n` +
        `  declareWidget<${widget.name}Props>('${widget.name}');`
      : `${docPrefix}export const ${widget.name} = Object.assign(\n` +
        `  declareWidget<${widget.name}Props>('${widget.name}'),\n` +
        `  declareConstants<{\n` +
        widget.constants
          .map((constant) => indentBlock(constantMember(constant, EMPTY_NAMES)))
          .join('\n') +
        `\n  }>('${widget.name}'),\n` +
        ');';
  return [propsInterface, component];
};

const EMPTY_NAMES: ReadonlySet<string> = new Set();

const indentBlock = (block: string): string =>
  block
    .split('\n')
    .map((line) => `  ${line}`)
    .join('\n');

const brandInterface = (
  name: string,
  hierarchy: ApiSnapshot['hierarchy'],
): string => {
  const brandKeys = [...new Set([name, ...(hierarchy[name] ?? [])])].sort();
  const brand = brandKeys.map((key) => `readonly ${key}: true`).join('; ');
  return `export interface ${name} {\n  readonly __fsxBrand?: { ${brand} };\n}`;
};

const enumBlock = (entity: Entity & { kind: 'enum' }): string => {
  const doc = dartdocToJsdoc(entity.doc, '');
  const union = entity.values.map((value) => `'${value.name}'`).join(' | ');
  const declaration = `export type ${entity.name} = ${union};`;
  return doc === '' ? declaration : `${doc}\n${declaration}`;
};

const qualifyGeneratedTypes = (
  tsType: string,
  names: ReadonlySet<string>,
): string =>
  tsType.replace(/\b[A-Z][A-Za-z0-9_]*\b/g, (identifier) =>
    names.has(identifier) ? `widgetTypes.${identifier}` : identifier,
  );

const constantMember = (
  constant: ConstantModel,
  generatedNames: ReadonlySet<string>,
): string => {
  const jsdoc = dartdocToJsdoc(constant.doc, '  ');
  const tsType = qualifyGeneratedTypes(tsTypeOf(constant.type), generatedNames);
  const declaration = `  readonly ${constant.name}: ${tsType};`;
  return jsdoc === '' ? declaration : `${jsdoc}\n${declaration}`;
};

export const emitWidgetsFile = (
  snapshot: ApiSnapshot,
  slots: SlotMap,
): string => {
  const widgets = snapshot.entities.filter(
    (entity): entity is WidgetEntity => entity.kind === 'widget',
  );

  const namedRefs = new Set<string>();
  const enumRefs = new Set<string>();
  for (const widget of widgets) {
    for (const param of defaultConstructorOf(widget)?.params ?? []) {
      collectRefs(param.type, namedRefs, enumRefs);
    }
  }
  for (const entity of snapshot.entities) {
    if (entity.kind !== 'enum') {
      for (const constant of entity.constants) {
        collectRefs(constant.type, namedRefs, enumRefs);
      }
    }
  }

  const extractedEnums = new Set(
    snapshot.entities
      .filter((entity) => entity.kind === 'enum')
      .map((entity) => entity.name),
  );
  for (const enumName of [...enumRefs].sort()) {
    if (!extractedEnums.has(enumName)) {
      throw new Error(
        `generated widgets: enum "${enumName}" is referenced but not ` +
          'extracted — extend defaultFlutterLibraries in the extractor.',
      );
    }
  }

  const blocks: string[] = [
    header(snapshot.meta.frameworkVersion),
    "import { declareWidget } from '../runtime/component';\n" +
      "import { declareConstants } from '../runtime/constants';\n" +
      'import type {\n' +
      '  FlutterChild,\n' +
      '  FlutterChildren,\n' +
      '  FlutterComponent,\n' +
      '  FlutterElement,\n' +
      '  TextChildren,\n' +
      "} from '../runtime/types';",
  ];

  for (const entity of snapshot.entities) {
    if (entity.kind === 'enum') {
      blocks.push(enumBlock(entity));
    }
  }
  for (const name of [...namedRefs].sort()) {
    blocks.push(brandInterface(name, snapshot.hierarchy));
  }
  for (const widget of widgets) {
    blocks.push(...widgetBlocks(widget, slots[widget.name] ?? EMPTY_SLOTS));
  }

  return `${blocks.join('\n\n')}\n`;
};

const constantNamespaceEntities = (snapshot: ApiSnapshot): string[] =>
  snapshot.entities
    .filter(
      (entity) =>
        entity.kind !== 'enum' &&
        entity.constants.length > 0 &&
        !(
          entity.kind === 'widget' &&
          entity.constructors.some((constructor) => constructor.name === '')
        ),
    )
    .map((entity) => entity.name);

export const emitGeneratedIndex = (snapshot: ApiSnapshot): string => {
  const names = constantNamespaceEntities(snapshot).join(', ');
  return `${[
    header(snapshot.meta.frameworkVersion),
    "export * from './widgets';",
    `export { ${names} } from './constants';`,
  ].join('\n\n')}\n`;
};

export const emitConstantsFile = (snapshot: ApiSnapshot): string => {
  // Component-rendered widgets carry their statics on the component itself
  // (Object.assign in widgets.ts) to avoid export collisions.
  const namespaceNames = new Set(constantNamespaceEntities(snapshot));
  const namespaces = snapshot.entities.filter((entity) =>
    namespaceNames.has(entity.name),
  );

  const generatedNames = new Set<string>();
  for (const namespace of namespaces) {
    if (namespace.kind !== 'enum') {
      for (const constant of namespace.constants) {
        collectRefs(constant.type, generatedNames, generatedNames);
      }
    }
  }

  const blocks: string[] = [
    header(snapshot.meta.frameworkVersion),
    "import { declareConstants } from '../runtime/constants';\n" +
      "import type * as widgetTypes from './widgets';",
  ];

  for (const namespace of namespaces) {
    if (namespace.kind === 'enum') {
      continue;
    }
    const doc = dartdocToJsdoc(namespace.doc, '');
    const docPrefix = doc === '' ? '' : `${doc}\n`;
    const members = namespace.constants
      .map((constant) => constantMember(constant, generatedNames))
      .join('\n');
    blocks.push(
      `${docPrefix}export const ${namespace.name} = declareConstants<{\n` +
        `${members}\n}>('${namespace.name}');`,
    );
  }

  return `${blocks.join('\n\n')}\n`;
};
