import type {
  ApiSnapshot,
  ClassEntity,
  ConstantModel,
  ConstructorModel,
  Entity,
  ParamModel,
  TypeNode,
  WidgetEntity,
} from '../api/model';
import { DATE_FORMS } from '../derive/date-forms';
import type { ChildrenSlot, SlotMap, WidgetSlots } from '../derive/slots';
import {
  ANY_VALUE_TYPE,
  DART_TYPE,
  deriveValueForms,
  EDGE_INSETS_TYPES,
  HEX_COLOR_TYPE,
  reachableValueFormNames,
  type ValueForms,
} from '../derive/value-forms';
import { dartdocToJsdoc } from './doc';
import { CHILDREN_TS_TYPES, propTsType, valueFormTsType } from './prop-type';
import { jsxPropName } from './renames';
import { signatureParams } from './signature';
import { tsTypeOf } from './ts-types';

const EMPTY_SLOTS: WidgetSlots = { children: null, slots: [] };

const header = (frameworkVersion: string): string =>
  '// GENERATED by `bun run generate` from ref/api.json — do not edit.\n' +
  `// Flutter ${frameworkVersion}`;

const collectRefs = (
  node: TypeNode,
  named: Set<string>,
  enums: Set<string>,
): void => {
  switch (node.kind) {
    case 'named':
      named.add(node.name);
      break;
    case 'enum':
      enums.add(node.name);
      break;
    case 'nullable':
      collectRefs(node.inner, named, enums);
      break;
    case 'list':
    case 'set':
    case 'future':
      collectRefs(node.item, named, enums);
      break;
    case 'map':
      collectRefs(node.key, named, enums);
      collectRefs(node.value, named, enums);
      break;
    case 'function':
      collectRefs(node.returnType, named, enums);
      for (const param of node.params) {
        collectRefs(param.type, named, enums);
      }
      break;
    default:
      break;
  }
};

const defaultConstructorOf = (
  entity: WidgetEntity | ClassEntity,
): WidgetEntity['constructors'][number] | undefined =>
  entity.constructors.find((constructor) => constructor.name === '');

const docWithDeprecation = (param: ParamModel): string => {
  if (!param.deprecated) {
    return param.doc;
  }
  return param.doc === ''
    ? '/// @deprecated'
    : `${param.doc}\n///\n/// @deprecated`;
};

interface PropScope {
  widgetSlots: WidgetSlots;
  takenNames: ReadonlySet<string>;
  formNames: ReadonlySet<string>;
}

const propLine = (param: ParamModel, scope: PropScope): string => {
  const { widgetSlots, takenNames, formNames } = scope;
  const tsType = propTsType(param, widgetSlots, formNames);
  const optional = param.required ? '' : '?';
  const name = jsxPropName(param.name, takenNames);
  const jsdoc = dartdocToJsdoc(docWithDeprecation(param), '  ');
  const declaration = `  ${name}${optional}: ${tsType};`;
  return jsdoc === '' ? declaration : `${jsdoc}\n${declaration}`;
};

const childrenLine = (children: ChildrenSlot, params: ParamModel[]): string => {
  const source = params.find((param) => param.name === children.param);
  const optional = source?.required === true ? '' : '?';
  const jsdoc = source === undefined ? '' : dartdocToJsdoc(source.doc, '  ');
  const declaration = `  children${optional}: ${CHILDREN_TS_TYPES[children.kind]};`;
  return jsdoc === '' ? declaration : `${jsdoc}\n${declaration}`;
};

const GESTURE_WIDGET = 'GestureDetector';

// GestureDetector's callback params are exactly the gestures any widget may
// carry: the compiler wraps the widget, so the props must typecheck on it.
const gestureParams = (
  snapshot: ApiSnapshot,
): { param: ParamModel; jsxName: string }[] => {
  const detector = snapshot.entities.find(
    (entity): entity is WidgetEntity =>
      entity.kind === 'widget' && entity.name === GESTURE_WIDGET,
  );
  const constructor =
    detector === undefined ? undefined : defaultConstructorOf(detector);
  if (constructor === undefined) {
    return [];
  }
  const takenNames = new Set(constructor.params.map((param) => param.name));
  return constructor.params
    .filter((param) => {
      const bare =
        param.type.kind === 'nullable' ? param.type.inner : param.type;
      return param.name.startsWith('on') && bare.kind === 'function';
    })
    .map((param) => ({ param, jsxName: jsxPropName(param.name, takenNames) }));
};

const gesturePropsBlock = (
  gestures: { param: ParamModel; jsxName: string }[],
  formNames: ReadonlySet<string>,
): string[] => {
  if (gestures.length === 0) {
    return [];
  }
  const scope: PropScope = {
    widgetSlots: EMPTY_SLOTS,
    takenNames: new Set(gestures.map(({ param }) => param.name)),
    formNames,
  };
  const lines = gestures.map(({ param }) => propLine(param, scope));
  return [
    '/**\n * Gestures any widget accepts: the compiler wraps it in a' +
      ' GestureDetector.\n */\n' +
      `export interface GestureProps {\n${lines.join('\n')}\n}`,
  ];
};

// A widget declaring the same prop keeps its own: that key is omitted from
// the inherited set rather than clashing with it.
const gestureClause = (
  widget: WidgetEntity,
  ownJsxNames: ReadonlySet<string>,
  gestureJsxNames: string[],
): string => {
  if (gestureJsxNames.length === 0 || widget.name === GESTURE_WIDGET) {
    return '';
  }
  const collisions = gestureJsxNames.filter((name) => ownJsxNames.has(name));
  if (collisions.length === gestureJsxNames.length) {
    return '';
  }
  const omitted = collisions.map((name) => `'${name}'`).join(' | ');
  return collisions.length === 0
    ? ' extends GestureProps'
    : ` extends Omit<GestureProps, ${omitted}>`;
};

interface WidgetScope {
  widgetSlots: WidgetSlots;
  formNames: ReadonlySet<string>;
  gestureJsxNames: string[];
  /** What the surface can name, for the statics this widget offers. */
  readable: ReadableTypes;
}

const widgetBlocks = (widget: WidgetEntity, scope: WidgetScope): string[] => {
  const { widgetSlots, formNames, gestureJsxNames, readable } = scope;
  const constructor = defaultConstructorOf(widget);
  if (constructor === undefined) {
    return [];
  }

  const takenNames = new Set(constructor.params.map((param) => param.name));
  const lines: string[] = [];
  if (widgetSlots.children !== null) {
    lines.push(childrenLine(widgetSlots.children, constructor.params));
  }
  for (const param of constructor.params) {
    if (param.name === 'key' || param.name === widgetSlots.children?.param) {
      continue;
    }
    lines.push(propLine(param, { widgetSlots, takenNames, formNames }));
  }

  const doc = dartdocToJsdoc(widget.doc, '');
  const docPrefix = doc === '' ? '' : `${doc}\n`;
  const ownJsxNames = new Set(
    constructor.params.map((param) => jsxPropName(param.name, takenNames)),
  );
  if (widgetSlots.children !== null) {
    ownJsxNames.add('children');
  }
  const propsInterface =
    `${docPrefix}export interface ${widget.name}Props` +
    `${gestureClause(widget, ownJsxNames, gestureJsxNames)} {\n` +
    `${lines.join('\n')}\n}`;
  // `MediaQuery.of(context)` and `Colors.red` are read off the component
  // itself, so the value carries whatever the widget offers statically.
  const carried = [
    ...(widget.constants.length === 0
      ? []
      : [
          `declareConstants<{\n${widget.constants
            .map((constant) =>
              indentBlock(constantMember(constant, EMPTY_NAMES)),
            )
            .join('\n')}\n  }>('${widget.name}')`,
        ]),
    ...staticSurface(widget, readable).map((type) => `{} as ${type}`),
  ];
  const component =
    carried.length === 0
      ? `${docPrefix}export const ${widget.name}: ` +
        `FlutterComponent<${widget.name}Props> =\n` +
        `  declareWidget<${widget.name}Props>('${widget.name}');`
      : `${docPrefix}export const ${widget.name} = Object.assign(\n` +
        `  declareWidget<${widget.name}Props>('${widget.name}'),\n` +
        `${carried.map((part) => `  ${part},`).join('\n')}\n` +
        ');';
  return [propsInterface, component];
};

/**
 * The statics a class or widget offers, as one declared value.
 *
 * `MediaQuery.of(context)` is how a Flutter app reads the tree, and a value
 * nothing constructs — a `FlutterView`, an `AssetBundle` — is handed over by
 * one of these. Only those whose whole signature the surface can name are
 * declared: one asking for a type the editor never heard of could not be
 * called anyway.
 */
const staticSurface = (
  entity: WidgetEntity | ClassEntity,
  readable: ReadableTypes,
): string[] => {
  if (entity.statics.length === 0 && entity.staticGetters.length === 0) {
    return [];
  }
  const nameable = (node: TypeNode): boolean =>
    isDeclaredType(node, readable.declared, readable.enums);
  const methods = entity.statics.filter(
    (method) =>
      TS_IDENTIFIER.test(method.name) &&
      nameable(method.returnType) &&
      method.params.every((param) => nameable(param.type)),
  );
  const getters = entity.staticGetters.filter(
    (getter) => TS_IDENTIFIER.test(getter.name) && nameable(getter.type),
  );
  if (methods.length === 0 && getters.length === 0) {
    return [];
  }
  const members = [
    ...methods.map((method) => {
      const params = signatureParams(method.params, (param) =>
        valueFormTsType(unwrapNullable(param.type), readable.forms),
      );
      return (
        `    readonly ${method.name}: (${params}) => ` +
        `${tsTypeOf(method.returnType)};`
      );
    }),
    ...getters.map(
      (getter) => `    readonly ${getter.name}: ${tsTypeOf(getter.type)};`,
    ),
  ];
  return [`{\n${members.join('\n')}\n  }`];
};

const isDeclaredType = (
  node: TypeNode,
  declared: ReadonlySet<string>,
  enumRefs: ReadonlySet<string>,
): boolean => {
  switch (node.kind) {
    case 'scalar':
      return true;
    case 'enum':
      return enumRefs.has(node.name);
    case 'named':
      return declared.has(node.name);
    case 'nullable':
      return isDeclaredType(node.inner, declared, enumRefs);
    case 'list':
    case 'set':
    case 'future':
    case 'stream':
      return isDeclaredType(node.item, declared, enumRefs);
    case 'map':
      return (
        isDeclaredType(node.key, declared, enumRefs) &&
        isDeclaredType(node.value, declared, enumRefs)
      );
    // A callback is declared by what it takes and answers with.
    case 'function':
      return (
        isDeclaredType(node.returnType, declared, enumRefs) &&
        node.params.every((param) =>
          isDeclaredType(param.type, declared, enumRefs),
        )
      );
    // A widget, a type variable, `void` and an unknown are all writable as
    // they are: none of them names a declaration that could be missing.
    case 'widget':
    case 'typeVar':
    case 'void':
    case 'unknown':
      return true;
  }
};

/** The named types a callback receives, at any depth of the signature. */
const collectHandedTypes = (node: TypeNode, into: Set<string>): void => {
  switch (node.kind) {
    case 'function':
      for (const param of node.params) {
        if (param.type.kind === 'named') into.add(param.type.name);
      }
      break;
    case 'nullable':
      collectHandedTypes(node.inner, into);
      break;
    case 'list':
    case 'set':
    case 'future':
      collectHandedTypes(node.item, into);
      break;
    default:
      break;
  }
};

/**
 * A value handed straight over, rather than through a callback.
 *
 * `MediaQuery.of(context)` returns a `MediaQueryData`, and the whole point
 * of holding one is reading it — so its members belong to the surface.
 */
const handedValue = (node: TypeNode, into: Set<string>): void => {
  if (node.kind === 'named') {
    into.add(node.name);
    return;
  }
  if (node.kind === 'nullable') {
    handedValue(node.inner, into);
    return;
  }
  if (node.kind === 'list' || node.kind === 'set' || node.kind === 'future') {
    handedValue(node.item, into);
  }
};

const EMPTY_NAMES: ReadonlySet<string> = new Set();

const indentBlock = (block: string): string =>
  block
    .split('\n')
    .map((line) => `  ${line}`)
    .join('\n');

/** What a nominal interface needs beyond the snapshot to declare its members. */
interface ReadableTypes {
  /** Classes the constants module exports, which carry their own newable. */
  namespaces: ReadonlySet<string>;
  /** Classes only `dart:ui` exports, whose names Flutter's own also take. */
  uiOnly: ReadonlySet<string>;
  /** Types a callback hands back, whose members are therefore readable. */
  handed: ReadonlySet<string>;
  /** Every named type the surface declares, so a member can be typed. */
  declared: ReadonlySet<string>;
  enums: ReadonlySet<string>;
  forms: ReadonlySet<string>;
}

const brandInterface = (
  name: string,
  snapshot: ApiSnapshot,
  readable: ReadableTypes,
): string => {
  const { handed, declared, enums: enumRefs, forms: formNames } = readable;
  const brandKeys = [
    ...new Set([name, ...(snapshot.hierarchy[name] ?? [])]),
  ].sort();
  const brand = brandKeys.map((key) => `readonly ${key}: true`).join('; ');
  const entity = snapshot.entities.find(
    (candidate) => candidate.name === name && candidate.kind !== 'enum',
  );
  // What a value of this type can be read for. A callback is handed one of
  // these — `(context, constraints) => …` — and the compiler resolves
  // `constraints.maxWidth`, so the editor has to know it too. A type nothing
  // hands over is a shape, and declaring members on it would guide nobody.
  const fields =
    entity === undefined || entity.kind === 'enum' || !handed.has(name)
      ? []
      : entity.fields
          // A field is exposed when its type is one the surface already
          // declares. Closing over the rest reaches most of the SDK, and a
          // member typed as something the editor has never heard of guides
          // nobody.
          .filter((field) => isDeclaredType(field.type, declared, enumRefs))
          .map(
            (field) =>
              `  readonly ${field.name}: ${valueFormTsType(
                unwrapNullable(field.type),
                formNames,
              )};`,
          );
  // What a value answers to: `scroll.jumpTo(0)`, `node.requestFocus()`.
  // Only a method whose whole signature the surface can name is offered.
  const methods =
    entity === undefined || entity.kind === 'enum'
      ? []
      : entity.methods
          .filter(
            (method) =>
              TS_IDENTIFIER.test(method.name) &&
              isDeclaredType(method.returnType, declared, enumRefs) &&
              method.params.every((param) =>
                isDeclaredType(param.type, declared, enumRefs),
              ),
          )
          .map((method) => {
            const params = signatureParams(method.params, (param) =>
              valueFormTsType(unwrapNullable(param.type), formNames),
            );
            // Written as a method, not as a property holding a function:
            // TypeScript compares method signatures bivariantly, which is
            // what lets a subclass narrow a parameter — `DoNothingAction`
            // takes an `Intent` where `Action` takes whatever it is built
            // for — and still be usable as its supertype.
            return `  ${method.name}(${params}): ${tsTypeOf(
              method.returnType,
            )};`;
          });
  return [
    `export interface ${name} {`,
    `  readonly __fsxBrand?: { ${brand} };`,
    ...fields,
    ...methods,
    '}',
    ...ownedConstructor(name, entity, readable),
  ].join('\n');
};

/**
 * The constructor of a controller a component owns.
 *
 * A ChangeNotifier — a TextEditingController, a ScrollController, a FocusNode
 * — is made once and disposed when the widget goes away, which is why the
 * compiler turns `new TextEditingController()` into a field of the State
 * rather than a value rebuilt every frame. Declaring the constructor is what
 * lets it be written at all; every other class stays a shape you receive.
 */
/** A name TypeScript can declare a member with, plainly. */
const TS_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * How a class is built, as TypeScript declares it.
 *
 * Dart builds a value with an unnamed constructor, with named ones, or with
 * both — `Offset(1, 1)` and `Rect.fromLTRB(…)` — so the declaration carries
 * whichever the class really has, and this is the one place that decides it
 * for every module that emits it.
 */
export const constructorSurface = (
  name: string,
  entity: ApiSnapshot['entities'][number] | undefined,
  readable: ReadableTypes,
): string | null => {
  // A widget is written as a tag, never constructed: its name already
  // belongs to the component the file declares.
  if (entity?.kind !== 'class') {
    return null;
  }
  // A `dart:ui` class shares its name with a Flutter one of the same name —
  // `Gradient` is both — so writing it plainly would mean the other. Until
  // the compiler writes a prefixed import, it is not constructed.
  if (readable.uiOnly.has(name)) {
    return null;
  }
  const writable = (constructor: ConstructorModel): boolean =>
    constructor.params.every((param) =>
      isDeclaredType(param.type, readable.declared, readable.enums),
    );
  const params = (constructor: ConstructorModel): string =>
    signatureParams(constructor.params, (param) =>
      valueFormTsType(unwrapNullable(param.type), readable.forms),
    );
  const unnamed = entity.isAbstract ? undefined : defaultConstructorOf(entity);
  const newable =
    unnamed === undefined || !writable(unnamed)
      ? null
      : `new (${params(unnamed)}) => ${name}`;
  const named = entity.constructors
    .filter(
      (constructor) =>
        constructor.name !== '' &&
        TS_IDENTIFIER.test(constructor.name) &&
        writable(constructor),
    )
    .map(
      (constructor) =>
        `  readonly ${constructor.name}: (${params(constructor)}) => ${name};`,
    );
  // `PlatformViewsService` builds nothing and is never built: it is the name
  // its statics hang off, and it still has to exist as a value.
  const statics = staticSurface(entity, readable);
  if (newable === null && named.length === 0 && statics.length === 0) {
    return null;
  }
  const members = named.length === 0 ? '' : `{\n${named.join('\n')}\n}`;
  return [newable, members, ...statics]
    .filter((part) => part !== null && part !== '')
    .join(' & ');
};

const ownedConstructor = (
  name: string,
  entity: ApiSnapshot['entities'][number] | undefined,
  readable: ReadableTypes,
): string[] => {
  // A class whose constants module already exports it gets its constructors
  // there; two exports of one name would shadow each other.
  const surface = readable.namespaces.has(name)
    ? null
    : constructorSurface(name, entity, readable);
  return surface === null
    ? []
    : ['', `export declare const ${name}: ${surface};`];
};

/**
 * A value a component can own: something the SDK builds with no arguments,
 * and that has an identity worth keeping.
 *
 * A controller, a focus node, a link between two layers — each is made once,
 * kept for as long as the widget lives, and handed to the widgets that use
 * it. A const class is not one of these: `BoxDecoration` is a value written
 * where it is used, and it is written as one — `decoration={{ … }}`. The
 * constructor's own const-ness is what separates them, and whether owning a
 * value also means disposing it is the class's own answer, both read from the
 * SDK rather than guessed from the name.
 */
export const isOwnedValue = (
  entity: ApiSnapshot['entities'][number],
): boolean => {
  if (entity.kind !== 'class') {
    return false;
  }
  const constructor = entity.constructors.find(
    (candidate) => candidate.name === '',
  );
  return (
    constructor !== undefined &&
    !constructor.isConst &&
    constructor.params.every((param) => !param.required)
  );
};

const unwrapNullable = (node: TypeNode): TypeNode =>
  node.kind === 'nullable' ? node.inner : node;

const objectInterfaceBlock = (
  name: string,
  params: ParamModel[],
  formNames: ReadonlySet<string>,
): string => {
  const lines = params.map((param) => {
    const jsdoc = dartdocToJsdoc(docWithDeprecation(param), '  ');
    const tsType = valueFormTsType(unwrapNullable(param.type), formNames);
    const declaration = `  ${param.name}?: ${tsType};`;
    return jsdoc === '' ? declaration : `${jsdoc}\n${declaration}`;
  });
  return `export interface ${name}Object {\n${lines.join('\n')}\n}`;
};

const valueAliasBlock = (name: string, forms: ValueForms): string => {
  const arms = [name];
  if (forms.constructibles.has(name)) {
    arms.push(`${name}Object`);
  }
  if (EDGE_INSETS_TYPES.has(name)) {
    arms.push(
      'number',
      '{ horizontal?: number; vertical?: number }',
      '{ left?: number; top?: number; right?: number; bottom?: number }',
    );
  }
  const dateForm = DATE_FORMS.get(name);
  if (dateForm !== undefined) {
    arms.push(dateForm.tsArm);
  }
  if (name === HEX_COLOR_TYPE) {
    arms.push('`#${string}`');
  }
  if (name === ANY_VALUE_TYPE) {
    arms.push('string', 'number', 'boolean');
  }
  if (name === DART_TYPE) {
    arms.push('string');
  }
  const members = forms.constantMembers.get(name);
  if (members !== undefined) {
    arms.push(...[...members.keys()].map((member) => `'${member}'`));
  }
  const union = arms.map((arm) => `  | ${arm}`).join('\n');
  return `export type ${name}Value =\n${union};`;
};

const valueFormBlocks = (
  name: string,
  forms: ValueForms,
  formNames: ReadonlySet<string>,
): string[] => {
  const params = forms.constructibles.get(name);
  return params === undefined
    ? [valueAliasBlock(name, forms)]
    : [
        objectInterfaceBlock(name, params, formNames),
        valueAliasBlock(name, forms),
      ];
};

const enumBlock = (entity: Entity & { kind: 'enum' }): string => {
  const doc = dartdocToJsdoc(entity.doc, '');
  const union = entity.values.map((value) => `'${value.name}'`).join(' | ');
  const declaration = `export type ${entity.name} = ${union};`;
  return doc === '' ? declaration : `${doc}\n${declaration}`;
};

const qualifyGeneratedTypes = (
  tsType: string,
  names: ReadonlySet<string>,
): string =>
  tsType.replace(/\b[A-Z][A-Za-z0-9_]*\b/g, (identifier) =>
    names.has(identifier) ? `widgetTypes.${identifier}` : identifier,
  );

const constantMember = (
  constant: ConstantModel,
  generatedNames: ReadonlySet<string>,
): string => {
  const jsdoc = dartdocToJsdoc(constant.doc, '  ');
  const tsType = qualifyGeneratedTypes(tsTypeOf(constant.type), generatedNames);
  const declaration = `  readonly ${constant.name}: ${tsType};`;
  return jsdoc === '' ? declaration : `${jsdoc}\n${declaration}`;
};

export const emitWidgetsFile = (
  snapshot: ApiSnapshot,
  slots: SlotMap,
): string => {
  const widgets = snapshot.entities.filter(
    (entity): entity is WidgetEntity => entity.kind === 'widget',
  );
  const forms = deriveValueForms(snapshot);
  const formNames = reachableValueFormNames(snapshot, forms);

  const namedRefs = new Set<string>();
  const enumRefs = new Set<string>();
  // The types a callback is handed — `(context, constraints) => …`. These are
  // the values a developer receives and reads, so these are the ones whose
  // members the editor has to know; everything else is only ever constructed.
  const handed = new Set<string>();
  for (const widget of widgets) {
    for (const param of defaultConstructorOf(widget)?.params ?? []) {
      collectRefs(param.type, namedRefs, enumRefs);
      collectHandedTypes(param.type, handed);
    }
  }
  // A static hands a value over — `MediaQuery.of(context)` — and that value
  // is read, so its members belong to the surface.
  for (const entity of snapshot.entities) {
    if (entity.kind === 'enum') {
      continue;
    }
    // A class that only carries statics — `PlatformViewsService` — is still
    // a name a developer writes, so the surface declares it.
    if (entity.statics.length > 0 || entity.staticGetters.length > 0) {
      namedRefs.add(entity.name);
    }
    for (const method of entity.statics) {
      collectRefs(method.returnType, namedRefs, enumRefs);
      handedValue(method.returnType, handed);
      for (const param of method.params) {
        collectRefs(param.type, namedRefs, enumRefs);
      }
    }
    for (const getter of entity.staticGetters) {
      collectRefs(getter.type, namedRefs, enumRefs);
      handedValue(getter.type, handed);
    }
    // A method's own signature is part of the surface: a subtype that could
    // not declare one would stop being usable where its supertype is.
    for (const method of entity.methods) {
      collectRefs(method.returnType, namedRefs, enumRefs);
      handedValue(method.returnType, handed);
      for (const param of method.params) {
        collectRefs(param.type, namedRefs, enumRefs);
      }
    }
  }
  for (const name of formNames) {
    namedRefs.add(name);
    for (const param of forms.constructibles.get(name) ?? []) {
      collectRefs(param.type, namedRefs, enumRefs);
    }
  }
  for (const entity of snapshot.entities) {
    if (entity.kind !== 'enum') {
      for (const constant of entity.constants) {
        collectRefs(constant.type, namedRefs, enumRefs);
      }
    }
    // A class the constants module exports is a value a developer holds, so
    // this module has to declare what that value is.
    if (entity.kind === 'class' && entity.constants.length > 0) {
      namedRefs.add(entity.name);
    }
  }
  // A type a prop asks for is often abstract — `ImageProvider`, a sliver
  // delegate — and the way to satisfy it is one of its concrete subclasses.
  // Those are values a developer writes, so they are declared too; so is
  // whatever their constructors ask for, and whatever those ask for after
  // that. The surface is closed under "can be written", not guessed at.
  const classes = snapshot.entities.filter(
    (entity): entity is ClassEntity => entity.kind === 'class',
  );
  for (let widened = true; widened;) {
    widened = false;
    for (const entity of classes) {
      const reachable =
        namedRefs.has(entity.name) ||
        entity.supertypes.some((name) => namedRefs.has(name));
      const constructor = defaultConstructorOf(entity);
      if (!reachable || constructor === undefined) {
        continue;
      }
      const before = namedRefs.size + enumRefs.size;
      namedRefs.add(entity.name);
      for (const param of constructor.params) {
        collectRefs(param.type, namedRefs, enumRefs);
      }
      widened = widened || namedRefs.size + enumRefs.size > before;
    }
  }

  // A subtype must carry what its supertype exposes or it stops being
  // assignable to it — `MaterialColor` has to keep satisfying `Color`. The
  // extractor already merges inherited getters, so this is just a wider set.
  for (const entity of snapshot.entities) {
    if (entity.kind === 'enum' || !namedRefs.has(entity.name)) continue;
    if (entity.supertypes.some((supertype) => handed.has(supertype))) {
      handed.add(entity.name);
    }
  }

  for (const name of formNames) {
    for (const generated of [`${name}Value`, `${name}Object`]) {
      if (namedRefs.has(generated) || enumRefs.has(generated)) {
        throw new Error(
          `generated widgets: "${generated}" collides with an extracted ` +
            'type name — rename the value-form suffix.',
        );
      }
    }
  }

  const extractedEnums = new Set(
    snapshot.entities
      .filter((entity) => entity.kind === 'enum')
      .map((entity) => entity.name),
  );
  for (const enumName of [...enumRefs].sort()) {
    if (!extractedEnums.has(enumName)) {
      throw new Error(
        `generated widgets: enum "${enumName}" is referenced but not ` +
          'extracted — extend defaultFlutterLibraries in the extractor.',
      );
    }
  }

  const blocks: string[] = [
    header(snapshot.meta.frameworkVersion),
    "import { declareWidget } from '../runtime/component';\n" +
      "import { declareConstants } from '../runtime/constants';\n" +
      'import type {\n' +
      '  FlutterChild,\n' +
      '  FlutterChildren,\n' +
      '  FlutterComponent,\n' +
      '  FlutterElement,\n' +
      '  TextChildren,\n' +
      "} from '../runtime/types';",
  ];

  for (const entity of snapshot.entities) {
    if (entity.kind === 'enum') {
      blocks.push(enumBlock(entity));
    }
  }
  const readable: ReadableTypes = {
    handed,
    declared: namedRefs,
    enums: enumRefs,
    forms: formNames,
    namespaces: new Set(constantNamespaceEntities(snapshot)),
    uiOnly: uiOnlyNames(snapshot),
  };
  for (const name of [...namedRefs].sort()) {
    blocks.push(
      brandInterface(name, snapshot, {
        handed,
        declared: namedRefs,
        enums: enumRefs,
        forms: formNames,
        namespaces: new Set(constantNamespaceEntities(snapshot)),
        uiOnly: uiOnlyNames(snapshot),
      }),
    );
  }
  for (const name of formNames) {
    blocks.push(...valueFormBlocks(name, forms, formNames));
  }
  const gestures = gestureParams(snapshot);
  blocks.push(...gesturePropsBlock(gestures, formNames));
  const gestureJsxNames = gestures.map(({ jsxName }) => jsxName);
  for (const widget of widgets) {
    blocks.push(
      ...widgetBlocks(widget, {
        widgetSlots: slots[widget.name] ?? EMPTY_SLOTS,
        formNames,
        gestureJsxNames,
        readable,
      }),
    );
  }

  return `${blocks.join('\n\n')}\n`;
};

/** Names only `dart:ui` exports, which a Flutter library also declares. */
const uiOnlyNames = (snapshot: ApiSnapshot): Set<string> =>
  new Set(
    Object.entries(snapshot.exports)
      .filter(([, barrels]) => barrels.length === 1 && barrels[0] === 'ui')
      .map(([name]) => name),
  );

const constantNamespaceEntities = (snapshot: ApiSnapshot): string[] =>
  snapshot.entities
    .filter(
      (entity) =>
        entity.kind !== 'enum' &&
        entity.constants.length > 0 &&
        !(
          entity.kind === 'widget' &&
          entity.constructors.some((constructor) => constructor.name === '')
        ),
    )
    .map((entity) => entity.name);

export const emitGeneratedIndex = (snapshot: ApiSnapshot): string => {
  const names = constantNamespaceEntities(snapshot).join(', ');
  return `${[
    header(snapshot.meta.frameworkVersion),
    "export * from './widgets';",
    // A class the constants module exports is a value; the interface of the
    // same name is a type, and both are part of the surface — `Intent` is
    // written as a value and named as a type.
    `export { ${names} } from './constants';`,
  ].join('\n\n')}\n`;
};

export const emitConstantsFile = (snapshot: ApiSnapshot): string => {
  // Component-rendered widgets carry their statics on the component itself
  // (Object.assign in widgets.ts) to avoid export collisions.
  const namespaceNames = new Set(constantNamespaceEntities(snapshot));
  const namespaces = snapshot.entities.filter((entity) =>
    namespaceNames.has(entity.name),
  );

  const generatedNames = new Set<string>();
  for (const namespace of namespaces) {
    if (namespace.kind === 'enum') {
      continue;
    }
    for (const constant of namespace.constants) {
      collectRefs(constant.type, generatedNames, generatedNames);
    }
    // The constructor these carry names types too, and they are declared in
    // the widgets module, so they need qualifying like everything else.
    generatedNames.add(namespace.name);
    for (const param of defaultConstructorOf(namespace)?.params ?? []) {
      collectRefs(param.type, generatedNames, generatedNames);
    }
  }

  const blocks: string[] = [
    header(snapshot.meta.frameworkVersion),
    "import { declareConstants } from '../runtime/constants';\n" +
      "import type * as widgetTypes from './widgets';\n" +
      "import type { FlutterElement } from '../runtime/types';",
  ];

  // Icon names are chosen by hand in TSX (`<TabItem icon="home">`), so they
  // become a union: the IDE completes them and rejects a typo where it is
  // written, instead of leaving it to the compiler.
  const icons = snapshot.entities.find((entity) => entity.name === 'Icons');
  if (icons !== undefined && icons.kind !== 'enum') {
    const names = icons.constants
      .map((constant) => `'${constant.name}'`)
      .sort();
    blocks.push(
      '/**\n * Every icon name the installed SDK provides.\n */\n' +
        `export type IconName = ${names.join(' | ')};`,
    );
  }

  for (const namespace of namespaces) {
    if (namespace.kind === 'enum') {
      continue;
    }
    const doc = dartdocToJsdoc(namespace.doc, '');
    const docPrefix = doc === '' ? '' : `${doc}\n`;
    const members = namespace.constants
      .map((constant) => constantMember(constant, generatedNames))
      .join('\n');
    // A class with static constants may also have constructors —
    // `Offset.zero`, `new Offset(1, 1)` and `Rect.fromLTRB(…)` are all real.
    // One export carries them all, or whichever is declared second would
    // shadow the other.
    const surface = constructorSurface(namespace.name, namespace, {
      handed: generatedNames,
      declared: generatedNames,
      enums: generatedNames,
      forms: new Set(),
      namespaces: new Set(),
      uiOnly: uiOnlyNames(snapshot),
    });
    const newable =
      surface === null
        ? ''
        : qualifyGeneratedTypes(` & (${surface})`, generatedNames);
    blocks.push(
      `${docPrefix}export const ${namespace.name} = declareConstants<{\n` +
        `${members}\n}${newable}>('${namespace.name}');`,
    );
  }

  return `${blocks.join('\n\n')}\n`;
};
