// GENERATED by `bun run generate:plugin camera` from ref/plugins/camera.json — do not edit.
// camera 0.12.0+2

declare module 'plugin:camera' {
  import type { DeviceOrientation, FlutterComponent, FlutterElement } from 'flutter-tsx';

  export type CameraLensDirection = 'front' | 'back' | 'external';

  export type CameraLensType = 'wide' | 'telephoto' | 'ultraWide' | 'unknown';

  export type ExposureMode = 'auto' | 'locked';

  export type FlashMode = 'off' | 'auto' | 'always' | 'torch';

  export type FocusMode = 'auto' | 'locked';

  export type ImageFormatGroup = 'unknown' | 'yuv420' | 'bgra8888' | 'jpeg' | 'nv21';

  export type ResolutionPreset = 'low' | 'medium' | 'high' | 'veryHigh' | 'ultraHigh' | 'max';

  export type VideoStabilizationMode = 'off' | 'level1' | 'level2' | 'level3';

  export interface BuildContext {
    readonly __external: 'BuildContext';
  }

  export interface CameraImageData {
    readonly __external: 'CameraImageData';
  }

  export interface CrossFileTestOverrides {
    readonly __external: 'CrossFileTestOverrides';
  }

  export interface DateTime {
    readonly __external: 'DateTime';
  }

  export interface Iterator {
    readonly __external: 'Iterator';
  }

  export interface Key {
    readonly __external: 'Key';
  }

  export interface MediaSettings {
    readonly __external: 'MediaSettings';
  }

  export interface Offset {
    readonly __external: 'Offset';
  }

  export interface Size {
    readonly __external: 'Size';
  }

  export interface Uint8List {
    readonly __external: 'Uint8List';
  }

  export type CameraDescriptionArgs = ConstructorParameters<typeof CameraDescription>[0];

  export type CameraValueArgs = ConstructorParameters<typeof CameraValue>[0];

  export class CameraController {
    constructor(description: CameraDescription | CameraDescriptionArgs, resolutionPreset: ResolutionPreset, options?: { enableAudio?: boolean; fps?: number | null; videoBitrate?: number | null; audioBitrate?: number | null; imageFormatGroup?: ImageFormatGroup | null });
    readonly cameraId: number;
    readonly description: CameraDescription;
    readonly enableAudio: boolean;
    readonly hasListeners: boolean;
    readonly imageFormatGroup: ImageFormatGroup | null;
    readonly mediaSettings: MediaSettings;
    readonly resolutionPreset: ResolutionPreset;
    readonly value: unknown;
    buildPreview(): FlutterElement;
    debugCheckIsDisposed(): void;
    getExposureOffsetStepSize(): Promise<number>;
    getMaxExposureOffset(): Promise<number>;
    getMaxZoomLevel(): Promise<number>;
    getMinExposureOffset(): Promise<number>;
    getMinZoomLevel(): Promise<number>;
    getSupportedVideoStabilizationModes(): Promise<VideoStabilizationMode[]>;
    lockCaptureOrientation(orientation?: DeviceOrientation | null): Promise<void>;
    pausePreview(): Promise<void>;
    pauseVideoRecording(): Promise<void>;
    prepareForVideoRecording(): Promise<void>;
    removeListener(listener: () => void): void;
    resumePreview(): Promise<void>;
    resumeVideoRecording(): Promise<void>;
    setDescription(description: CameraDescription | CameraDescriptionArgs): Promise<void>;
    setExposureMode(mode: ExposureMode): Promise<void>;
    setExposureOffset(offset: number): Promise<number>;
    setExposurePoint(point: Offset | null): Promise<void>;
    setFlashMode(mode: FlashMode): Promise<void>;
    setFocusMode(mode: FocusMode): Promise<void>;
    setFocusPoint(point: Offset | null): Promise<void>;
    setVideoStabilizationMode(mode: VideoStabilizationMode, options?: { allowFallback?: boolean }): Promise<void>;
    setZoomLevel(zoom: number): Promise<void>;
    startImageStream(onAvailable: (image: CameraImage) => void): Promise<void>;
    startVideoRecording(options?: { onAvailable?: ((image: CameraImage) => void) | null; enablePersistentRecording?: boolean }): Promise<void>;
    stopImageStream(): Promise<void>;
    stopVideoRecording(): Promise<XFile>;
    supportsImageStreaming(): boolean;
    takePicture(): Promise<XFile>;
    unlockCaptureOrientation(): Promise<void>;
  }

  export class CameraDescription {
    constructor(options: { name: string; lensDirection: CameraLensDirection; sensorOrientation: number; lensType?: CameraLensType });
    readonly lensDirection: CameraLensDirection;
    readonly lensType: CameraLensType;
    readonly name: string;
    readonly sensorOrientation: number;
    toString(): string;
  }

  export class CameraException {
    constructor(code: string, description: string | null);
    readonly code: string;
    readonly description: string | null;
    toString(): string;
  }

  export class CameraImage {
    readonly format: ImageFormat;
    readonly height: number;
    readonly lensAperture: number | null;
    readonly planes: Plane[];
    readonly sensorExposureTime: number | null;
    readonly sensorSensitivity: number | null;
    readonly width: number;
  }

  export interface CameraPreviewProps {
    controller: CameraController;
    key?: Key | null;
    child?: FlutterElement | null;
  }

  export const CameraPreview: FlutterComponent<CameraPreviewProps>;

  export class CameraValue {
    constructor(options: { isInitialized: boolean; errorDescription?: string | null; previewSize?: Size | null; isRecordingVideo: boolean; isTakingPicture: boolean; isStreamingImages: boolean; isRecordingPaused: boolean; flashMode: FlashMode; exposureMode: ExposureMode; focusMode: FocusMode; exposurePointSupported: boolean; focusPointSupported: boolean; deviceOrientation: DeviceOrientation; description: CameraDescription | CameraDescriptionArgs; lockedCaptureOrientation?: DeviceOrientation | null; recordingOrientation?: DeviceOrientation | null; isPreviewPaused?: boolean; previewPauseOrientation?: DeviceOrientation | null; videoStabilizationMode?: VideoStabilizationMode });
    readonly aspectRatio: number;
    readonly description: CameraDescription;
    readonly deviceOrientation: DeviceOrientation;
    readonly errorDescription: string | null;
    readonly exposureMode: ExposureMode;
    readonly exposurePointSupported: boolean;
    readonly flashMode: FlashMode;
    readonly focusMode: FocusMode;
    readonly focusPointSupported: boolean;
    readonly hasError: boolean;
    readonly isCaptureOrientationLocked: boolean;
    readonly isInitialized: boolean;
    readonly isPreviewPaused: boolean;
    readonly isRecordingPaused: boolean;
    readonly isRecordingVideo: boolean;
    readonly isStreamingImages: boolean;
    readonly isTakingPicture: boolean;
    readonly lockedCaptureOrientation: DeviceOrientation | null;
    readonly previewPauseOrientation: DeviceOrientation | null;
    readonly previewSize: Size | null;
    readonly recordingOrientation: DeviceOrientation | null;
    readonly videoStabilizationMode: VideoStabilizationMode;
    copyWith(options?: { isInitialized?: boolean | null; isRecordingVideo?: boolean | null; isTakingPicture?: boolean | null; isStreamingImages?: boolean | null; errorDescription?: string | null; previewSize?: Size | null; isRecordingPaused?: boolean | null; flashMode?: FlashMode | null; exposureMode?: ExposureMode | null; focusMode?: FocusMode | null; exposurePointSupported?: boolean | null; focusPointSupported?: boolean | null; deviceOrientation?: DeviceOrientation | null; lockedCaptureOrientation?: Optional | null; recordingOrientation?: Optional | null; isPreviewPaused?: boolean | null; description?: CameraDescription | null | CameraDescriptionArgs; previewPauseOrientation?: Optional | null; videoStabilizationMode?: VideoStabilizationMode | null }): CameraValue;
    toString(): string;
  }

  export class ImageFormat {
    readonly group: ImageFormatGroup;
    readonly raw: unknown;
  }

  export class Optional {
    readonly first: unknown;
    readonly isEmpty: boolean;
    readonly isNotEmpty: boolean;
    readonly isNotPresent: boolean;
    readonly isPresent: boolean;
    readonly iterator: Iterator;
    readonly last: unknown;
    readonly length: number;
    readonly orNull: unknown | null;
    readonly single: unknown;
    readonly value: unknown;
    ifAbsent(ifAbsent: () => void): void;
    ifPresent(ifPresent: (value: unknown) => void): void;
    or(defaultValue: unknown): unknown;
    toString(): string;
    transform(transformer: (value: unknown) => unknown): Optional;
    transformNullable(transformer: (value: unknown) => unknown | null): Optional;
  }

  export class Plane {
    readonly bytes: Uint8List;
    readonly bytesPerPixel: number | null;
    readonly bytesPerRow: number;
    readonly height: number | null;
    readonly width: number | null;
  }

  export class XFile {
    constructor(path: string, options?: { mimeType?: string | null; name?: string | null; length?: number | null; bytes?: Uint8List | null; lastModified?: DateTime | null; overrides?: CrossFileTestOverrides | null });
    readonly mimeType: string | null;
    readonly name: string;
    readonly path: string;
  }

  export const availableCameras: () => Promise<CameraDescription[]>;

  export const useCamera: (options?: { lens?: CameraLensDirection; lensType?: CameraLensType; resolution?: ResolutionPreset }) => CameraController | null;
}
