// GENERATED by `bun run generate:plugin camera` from ref/plugins/camera.json — do not edit.
// camera 0.12.0+2

declare module 'plugin:camera' {
  import type { DeviceOrientation, FlutterElement } from 'flutter-tsx';

  export type CameraLensDirection = 'front' | 'back' | 'external';

  export type CameraLensType = 'wide' | 'telephoto' | 'ultraWide' | 'unknown';

  export type ExposureMode = 'auto' | 'locked';

  export type FlashMode = 'off' | 'auto' | 'always' | 'torch';

  export type FocusMode = 'auto' | 'locked';

  export type ImageFormatGroup = 'unknown' | 'yuv420' | 'bgra8888' | 'jpeg' | 'nv21';

  export type ResolutionPreset = 'low' | 'medium' | 'high' | 'veryHigh' | 'ultraHigh' | 'max';

  export type VideoStabilizationMode = 'off' | 'level1' | 'level2' | 'level3';

  export interface BuildContext {
    readonly __external: 'BuildContext';
  }

  export interface CameraImageData {
    readonly __external: 'CameraImageData';
  }

  export interface CrossFileTestOverrides {
    readonly __external: 'CrossFileTestOverrides';
  }

  export interface DateTime {
    readonly __external: 'DateTime';
  }

  export interface Key {
    readonly __external: 'Key';
  }

  export interface Offset {
    readonly __external: 'Offset';
  }

  export interface Size {
    readonly __external: 'Size';
  }

  export interface Uint8List {
    readonly __external: 'Uint8List';
  }

  export class CameraController {
    constructor(description: CameraDescription, resolutionPreset: ResolutionPreset, options?: { enableAudio?: boolean; fps?: number | null; videoBitrate?: number | null; audioBitrate?: number | null; imageFormatGroup?: ImageFormatGroup | null });
    buildPreview(): FlutterElement;
    debugCheckIsDisposed(): void;
    dispose(): Promise<void>;
    getExposureOffsetStepSize(): Promise<number>;
    getMaxExposureOffset(): Promise<number>;
    getMaxZoomLevel(): Promise<number>;
    getMinExposureOffset(): Promise<number>;
    getMinZoomLevel(): Promise<number>;
    getSupportedVideoStabilizationModes(): Promise<VideoStabilizationMode[]>;
    initialize(): Promise<void>;
    lockCaptureOrientation(orientation?: DeviceOrientation | null): Promise<void>;
    pausePreview(): Promise<void>;
    pauseVideoRecording(): Promise<void>;
    prepareForVideoRecording(): Promise<void>;
    removeListener(listener: () => void): void;
    resumePreview(): Promise<void>;
    resumeVideoRecording(): Promise<void>;
    setDescription(description: CameraDescription): Promise<void>;
    setExposureMode(mode: ExposureMode): Promise<void>;
    setExposureOffset(offset: number): Promise<number>;
    setExposurePoint(point: Offset | null): Promise<void>;
    setFlashMode(mode: FlashMode): Promise<void>;
    setFocusMode(mode: FocusMode): Promise<void>;
    setFocusPoint(point: Offset | null): Promise<void>;
    setVideoStabilizationMode(mode: VideoStabilizationMode, options?: { allowFallback?: boolean }): Promise<void>;
    setZoomLevel(zoom: number): Promise<void>;
    startImageStream(onAvailable: (image: CameraImage) => void): Promise<void>;
    startVideoRecording(options?: { onAvailable?: ((image: CameraImage) => void) | null; enablePersistentRecording?: boolean }): Promise<void>;
    stopImageStream(): Promise<void>;
    stopVideoRecording(): Promise<XFile>;
    supportsImageStreaming(): boolean;
    takePicture(): Promise<XFile>;
    unlockCaptureOrientation(): Promise<void>;
  }

  export class CameraDescription {
    constructor(options: { name: string; lensDirection: CameraLensDirection; sensorOrientation: number; lensType?: CameraLensType });
    toString(): string;
  }

  export class CameraException {
    constructor(code: string, description: string | null);
    toString(): string;
  }

  export class CameraImage {}

  export class CameraPreview {
    constructor(controller: CameraController, options?: { key?: Key | null; child?: FlutterElement | null });
    build(context: BuildContext): FlutterElement;
  }

  export class CameraValue {
    constructor(options: { isInitialized: boolean; errorDescription?: string | null; previewSize?: Size | null; isRecordingVideo: boolean; isTakingPicture: boolean; isStreamingImages: boolean; isRecordingPaused: boolean; flashMode: FlashMode; exposureMode: ExposureMode; focusMode: FocusMode; exposurePointSupported: boolean; focusPointSupported: boolean; deviceOrientation: DeviceOrientation; description: CameraDescription; lockedCaptureOrientation?: DeviceOrientation | null; recordingOrientation?: DeviceOrientation | null; isPreviewPaused?: boolean; previewPauseOrientation?: DeviceOrientation | null; videoStabilizationMode?: VideoStabilizationMode });
    copyWith(options?: { isInitialized?: boolean | null; isRecordingVideo?: boolean | null; isTakingPicture?: boolean | null; isStreamingImages?: boolean | null; errorDescription?: string | null; previewSize?: Size | null; isRecordingPaused?: boolean | null; flashMode?: FlashMode | null; exposureMode?: ExposureMode | null; focusMode?: FocusMode | null; exposurePointSupported?: boolean | null; focusPointSupported?: boolean | null; deviceOrientation?: DeviceOrientation | null; lockedCaptureOrientation?: Optional | null; recordingOrientation?: Optional | null; isPreviewPaused?: boolean | null; description?: CameraDescription | null; previewPauseOrientation?: Optional | null; videoStabilizationMode?: VideoStabilizationMode | null }): CameraValue;
    toString(): string;
  }

  export class ImageFormat {}

  export class Optional {
    ifAbsent(ifAbsent: () => void): void;
    ifPresent(ifPresent: (value: unknown) => void): void;
    or(defaultValue: unknown): unknown;
    toString(): string;
    transform(transformer: (value: unknown) => unknown): Optional;
    transformNullable(transformer: (value: unknown) => unknown | null): Optional;
  }

  export class Plane {}

  export class XFile {
    constructor(path: string, options?: { mimeType?: string | null; name?: string | null; length?: number | null; bytes?: Uint8List | null; lastModified?: DateTime | null; overrides?: CrossFileTestOverrides | null });
  }

  export const availableCameras: () => Promise<CameraDescription[]>;

  export const useCamera: (options?: { resolution?: ResolutionPreset }) => Omit<CameraController, 'initialize' | 'dispose'>;
}
