// GENERATED by `bun run generate:plugin connectivity_plus` from ref/plugins/connectivity_plus.json — do not edit.
// connectivity_plus 7.3.1

declare module 'plugin:connectivity_plus' {
  export type ConnectivityResult = 'bluetooth' | 'wifi' | 'ethernet' | 'mobile' | 'none' | 'vpn' | 'satellite' | 'other';

  export interface NetworkManagerClient {
    readonly __external: 'NetworkManagerClient';
  }

  export class Connectivity {
    constructor();
    readonly onConnectivityChanged: AsyncIterable<ConnectivityResult[]>;
    checkConnectivity(): Promise<ConnectivityResult[]>;
  }

  export const useConnectivity: () => Connectivity;
}
