// GENERATED by `bun run generate:plugin flutter_secure_storage` from ref/plugins/flutter_secure_storage.json — do not edit.
// flutter_secure_storage 9.2.4

declare module 'plugin:flutter_secure_storage' {
  export type KeyCipherAlgorithm = 'RSA_ECB_PKCS1Padding' | 'RSA_ECB_OAEPwithSHA_256andMGF1Padding';

  export type KeychainAccessibility = 'passcode' | 'unlocked' | 'unlocked_this_device' | 'first_unlock' | 'first_unlock_this_device';

  export type StorageCipherAlgorithm = 'AES_CBC_PKCS7Padding' | 'AES_GCM_NoPadding';

  export interface Stream {
    readonly __external: 'Stream';
  }

  export class AndroidOptions {
    constructor(options?: { encryptedSharedPreferences?: boolean; resetOnError?: boolean; keyCipherAlgorithm?: KeyCipherAlgorithm; storageCipherAlgorithm?: StorageCipherAlgorithm; sharedPreferencesName?: string | null; preferencesKeyPrefix?: string | null });
    readonly preferencesKeyPrefix: string | null;
    readonly sharedPreferencesName: string | null;
    copyWith(options?: { encryptedSharedPreferences?: boolean | null; resetOnError?: boolean | null; keyCipherAlgorithm?: KeyCipherAlgorithm | null; storageCipherAlgorithm?: StorageCipherAlgorithm | null; preferencesKeyPrefix?: string | null; sharedPreferencesName?: string | null }): AndroidOptions;
    toMap(): Record<string, string>;
  }

  export class AppleOptions {
    toMap(): Record<string, string>;
  }

  export class FlutterSecureStorage {
    constructor(options?: { iOptions?: IOSOptions; aOptions?: AndroidOptions; lOptions?: LinuxOptions; wOptions?: WindowsOptions; webOptions?: WebOptions; mOptions?: MacOsOptions });
    readonly aOptions: AndroidOptions;
    readonly iOptions: IOSOptions;
    readonly lOptions: LinuxOptions;
    readonly mOptions: MacOsOptions;
    readonly onCupertinoProtectedDataAvailabilityChanged: Stream | null;
    readonly wOptions: WindowsOptions;
    readonly webOptions: WebOptions;
    containsKey(options: { key: string; iOptions?: IOSOptions | null; aOptions?: AndroidOptions | null; lOptions?: LinuxOptions | null; webOptions?: WebOptions | null; mOptions?: MacOsOptions | null; wOptions?: WindowsOptions | null }): Promise<boolean>;
    delete(options: { key: string; iOptions?: IOSOptions | null; aOptions?: AndroidOptions | null; lOptions?: LinuxOptions | null; webOptions?: WebOptions | null; mOptions?: MacOsOptions | null; wOptions?: WindowsOptions | null }): Promise<void>;
    deleteAll(options?: { iOptions?: IOSOptions | null; aOptions?: AndroidOptions | null; lOptions?: LinuxOptions | null; webOptions?: WebOptions | null; mOptions?: MacOsOptions | null; wOptions?: WindowsOptions | null }): Promise<void>;
    isCupertinoProtectedDataAvailable(): Promise<boolean | null>;
    read(options: { key: string; iOptions?: IOSOptions | null; aOptions?: AndroidOptions | null; lOptions?: LinuxOptions | null; webOptions?: WebOptions | null; mOptions?: MacOsOptions | null; wOptions?: WindowsOptions | null }): Promise<string | null>;
    readAll(options?: { iOptions?: IOSOptions | null; aOptions?: AndroidOptions | null; lOptions?: LinuxOptions | null; webOptions?: WebOptions | null; mOptions?: MacOsOptions | null; wOptions?: WindowsOptions | null }): Promise<Record<string, string>>;
    registerListener(options: { key: string; listener: (value: string | null) => void }): void;
    static setMockInitialValues(values: Record<string, string>): void;
    unregisterAllListeners(): void;
    unregisterAllListenersForKey(options: { key: string }): void;
    unregisterListener(options: { key: string; listener: (value: string | null) => void }): void;
    write(options: { key: string; value: string | null; iOptions?: IOSOptions | null; aOptions?: AndroidOptions | null; lOptions?: LinuxOptions | null; webOptions?: WebOptions | null; mOptions?: MacOsOptions | null; wOptions?: WindowsOptions | null }): Promise<void>;
  }

  export class IOSOptions {
    constructor(options?: { groupId?: string | null; accountName?: string | null; accessibility?: KeychainAccessibility | null; synchronizable?: boolean });
    copyWith(options?: { groupId?: string | null; accountName?: string | null; accessibility?: KeychainAccessibility | null; synchronizable?: boolean | null }): IOSOptions;
  }

  export class LinuxOptions {
    constructor();
    toMap(): Record<string, string>;
  }

  export class MacOsOptions {
    constructor(options?: { groupId?: string | null; accountName?: string | null; accessibility?: KeychainAccessibility | null; synchronizable?: boolean; useDataProtectionKeyChain?: boolean });
    copyWith(options?: { groupId?: string | null; accountName?: string | null; accessibility?: KeychainAccessibility | null; synchronizable?: boolean | null; useDataProtectionKeyChain?: boolean | null }): MacOsOptions;
    toMap(): Record<string, string>;
  }

  export class WebOptions {
    constructor(options?: { dbName?: string; publicKey?: string; wrapKey?: string; wrapKeyIv?: string });
    readonly dbName: string;
    readonly publicKey: string;
    readonly wrapKey: string;
    readonly wrapKeyIv: string;
    toMap(): Record<string, string>;
  }

  export class WindowsOptions {
    constructor(options?: { useBackwardCompatibility?: boolean });
    copyWith(options?: { useBackwardCompatibility?: boolean | null }): WindowsOptions;
    toMap(): Record<string, string>;
  }

  export const useSecureStorage: () => FlutterSecureStorage;
}
