// GENERATED by `bun run generate:plugin http` from ref/plugins/http.json — do not edit.
// http 1.6.0

declare module 'plugin:http' {
  export interface Encoding {
    readonly __external: 'Encoding';
  }

  export interface Object {
    readonly __external: 'Object';
  }

  export interface StreamSink {
    readonly __external: 'StreamSink';
  }

  export interface Uint8List {
    readonly __external: 'Uint8List';
  }

  export interface ZoneSpecification {
    readonly __external: 'ZoneSpecification';
  }

  export class Abortable {
    readonly abortTrigger: Promise<void> | null;
    readonly contentLength: number | null;
    readonly finalized: boolean;
    readonly followRedirects: boolean;
    readonly headers: Record<string, string>;
    readonly maxRedirects: number;
    readonly method: string;
    readonly persistentConnection: boolean;
    readonly url: string;
  }

  export class AbortableMultipartRequest {
    constructor(method: string, url: string, options?: { abortTrigger?: Promise<void> | null });
    readonly abortTrigger: Promise<void> | null;
    readonly contentLength: number;
    readonly fields: Record<string, string>;
    readonly files: MultipartFile[];
    readonly finalized: boolean;
    readonly followRedirects: boolean;
    readonly headers: Record<string, string>;
    readonly maxRedirects: number;
    readonly method: string;
    readonly persistentConnection: boolean;
    readonly url: string;
  }

  export class AbortableRequest {
    constructor(method: string, url: string, options?: { abortTrigger?: Promise<void> | null });
    readonly abortTrigger: Promise<void> | null;
    readonly body: string;
    readonly bodyBytes: Uint8List;
    readonly bodyFields: Record<string, string>;
    readonly contentLength: number;
    readonly encoding: Encoding;
    readonly finalized: boolean;
    readonly followRedirects: boolean;
    readonly headers: Record<string, string>;
    readonly maxRedirects: number;
    readonly method: string;
    readonly persistentConnection: boolean;
    readonly url: string;
  }

  export class AbortableStreamedRequest {
    constructor(method: string, url: string, options?: { abortTrigger?: Promise<void> | null });
    readonly abortTrigger: Promise<void> | null;
    readonly contentLength: number | null;
    readonly finalized: boolean;
    readonly followRedirects: boolean;
    readonly headers: Record<string, string>;
    readonly maxRedirects: number;
    readonly method: string;
    readonly persistentConnection: boolean;
    readonly sink: StreamSink;
    readonly url: string;
  }

  export class BaseClient {
    close(): void;
    delete(url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }): Promise<Response>;
    get(url: string, options?: { headers?: Record<string, string> | null }): Promise<Response>;
    head(url: string, options?: { headers?: Record<string, string> | null }): Promise<Response>;
    patch(url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }): Promise<Response>;
    post(url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }): Promise<Response>;
    put(url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }): Promise<Response>;
    read(url: string, options?: { headers?: Record<string, string> | null }): Promise<string>;
    readBytes(url: string, options?: { headers?: Record<string, string> | null }): Promise<Uint8List>;
    send(request: BaseRequest): Promise<StreamedResponse>;
  }

  export class BaseRequest {
    readonly contentLength: number | null;
    readonly finalized: boolean;
    readonly followRedirects: boolean;
    readonly headers: Record<string, string>;
    readonly maxRedirects: number;
    readonly method: string;
    readonly persistentConnection: boolean;
    readonly url: string;
    finalize(): ByteStream;
    send(): Promise<StreamedResponse>;
    toString(): string;
  }

  export class BaseResponse {
    readonly contentLength: number | null;
    readonly headers: Record<string, string>;
    readonly isRedirect: boolean;
    readonly persistentConnection: boolean;
    readonly reasonPhrase: string | null;
    readonly request: BaseRequest | null;
    readonly statusCode: number;
  }

  export class BaseResponseWithUrl {
    readonly contentLength: number | null;
    readonly headers: Record<string, string>;
    readonly isRedirect: boolean;
    readonly persistentConnection: boolean;
    readonly reasonPhrase: string | null;
    readonly request: BaseRequest | null;
    readonly statusCode: number;
    readonly url: string;
  }

  export class ByteStream {
    constructor(stream: AsyncIterable<number[]>);
    readonly first: Promise<unknown>;
    readonly isBroadcast: boolean;
    readonly isEmpty: Promise<boolean>;
    readonly last: Promise<unknown>;
    readonly length: Promise<number>;
    readonly single: Promise<unknown>;
    bytesToString(encoding?: Encoding): Promise<string>;
    toBytes(): Promise<Uint8List>;
    toStringStream(encoding?: Encoding): AsyncIterable<string>;
  }

  export class Client {
    constructor();
    close(): void;
    delete(url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }): Promise<Response>;
    get(url: string, options?: { headers?: Record<string, string> | null }): Promise<Response>;
    head(url: string, options?: { headers?: Record<string, string> | null }): Promise<Response>;
    patch(url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }): Promise<Response>;
    post(url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }): Promise<Response>;
    put(url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }): Promise<Response>;
    read(url: string, options?: { headers?: Record<string, string> | null }): Promise<string>;
    readBytes(url: string, options?: { headers?: Record<string, string> | null }): Promise<Uint8List>;
    send(request: BaseRequest): Promise<StreamedResponse>;
  }

  export class ClientException {
    constructor(message: string, uri?: string | null);
    readonly message: string;
    readonly uri: string | null;
    toString(): string;
  }

  export class MediaType {
    constructor(type: string, subtype: string, parameters?: Record<string, string> | null);
    readonly mimeType: string;
    readonly parameters: Record<string, string>;
    readonly subtype: string;
    readonly type: string;
    change(options?: { type?: string | null; subtype?: string | null; mimeType?: string | null; parameters?: Record<string, string> | null; clearParameters?: boolean }): MediaType;
    toString(): string;
  }

  export class MultipartFile {
    constructor(field: string, stream: AsyncIterable<number[]>, length: number, options?: { filename?: string | null; contentType?: MediaType | null });
    readonly contentType: MediaType;
    readonly field: string;
    readonly filename: string | null;
    readonly isFinalized: boolean;
    readonly length: number;
    finalize(): ByteStream;
    static fromPath(field: string, filePath: string, options?: { filename?: string | null; contentType?: MediaType | null }): Promise<MultipartFile>;
  }

  export class MultipartRequest {
    constructor(method: string, url: string);
    readonly contentLength: number;
    readonly fields: Record<string, string>;
    readonly files: MultipartFile[];
    readonly finalized: boolean;
    readonly followRedirects: boolean;
    readonly headers: Record<string, string>;
    readonly maxRedirects: number;
    readonly method: string;
    readonly persistentConnection: boolean;
    readonly url: string;
    finalize(): ByteStream;
  }

  export class Request {
    constructor(method: string, url: string);
    readonly body: string;
    readonly bodyBytes: Uint8List;
    readonly bodyFields: Record<string, string>;
    readonly contentLength: number;
    readonly encoding: Encoding;
    readonly finalized: boolean;
    readonly followRedirects: boolean;
    readonly headers: Record<string, string>;
    readonly maxRedirects: number;
    readonly method: string;
    readonly persistentConnection: boolean;
    readonly url: string;
    finalize(): ByteStream;
  }

  export class RequestAbortedException {
    constructor(uri?: string | null);
    readonly message: string;
    readonly uri: string | null;
  }

  export class Response {
    constructor(body: string, statusCode: number, options?: { request?: BaseRequest | null; headers?: Record<string, string>; isRedirect?: boolean; persistentConnection?: boolean; reasonPhrase?: string | null });
    readonly body: string;
    readonly bodyBytes: Uint8List;
    readonly contentLength: number | null;
    readonly headers: Record<string, string>;
    readonly isRedirect: boolean;
    readonly persistentConnection: boolean;
    readonly reasonPhrase: string | null;
    readonly request: BaseRequest | null;
    readonly statusCode: number;
    static fromStream(response: StreamedResponse): Promise<Response>;
  }

  export class StreamedRequest {
    constructor(method: string, url: string);
    readonly contentLength: number | null;
    readonly finalized: boolean;
    readonly followRedirects: boolean;
    readonly headers: Record<string, string>;
    readonly maxRedirects: number;
    readonly method: string;
    readonly persistentConnection: boolean;
    readonly sink: StreamSink;
    readonly url: string;
    finalize(): ByteStream;
  }

  export class StreamedResponse {
    constructor(stream: AsyncIterable<number[]>, statusCode: number, options?: { contentLength?: number | null; request?: BaseRequest | null; headers?: Record<string, string>; isRedirect?: boolean; persistentConnection?: boolean; reasonPhrase?: string | null });
    readonly contentLength: number | null;
    readonly headers: Record<string, string>;
    readonly isRedirect: boolean;
    readonly persistentConnection: boolean;
    readonly reasonPhrase: string | null;
    readonly request: BaseRequest | null;
    readonly statusCode: number;
    readonly stream: ByteStream;
  }

  const delete_: (url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }) => Promise<Response>;
  export { delete_ as delete };

  export const get: (url: string, options?: { headers?: Record<string, string> | null }) => Promise<Response>;

  export const head: (url: string, options?: { headers?: Record<string, string> | null }) => Promise<Response>;

  export const patch: (url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }) => Promise<Response>;

  export const post: (url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }) => Promise<Response>;

  export const put: (url: string, options?: { headers?: Record<string, string> | null; body?: Object | null; encoding?: Encoding | null }) => Promise<Response>;

  export const read: (url: string, options?: { headers?: Record<string, string> | null }) => Promise<string>;

  export const readBytes: (url: string, options?: { headers?: Record<string, string> | null }) => Promise<Uint8List>;

  export const runWithClient: (body: () => unknown, clientFactory: () => Client, options?: { zoneSpecification?: ZoneSpecification | null }) => unknown;

  export const useClient: () => Client;
}
