// GENERATED by `bun run generate:plugin package_info_plus` from ref/plugins/package_info_plus.json — do not edit.
// package_info_plus 8.3.1

declare module 'plugin:package_info_plus' {
  export interface DateTime {
    readonly __external: 'DateTime';
  }

  export interface PackageInfoData {
    readonly __external: 'PackageInfoData';
  }

  export class PackageInfo {
    constructor(options: { appName: string; packageName: string; version: string; buildNumber: string; buildSignature?: string; installerStore?: string | null; installTime?: DateTime | null; updateTime?: DateTime | null });
    readonly appName: string;
    readonly buildNumber: string;
    readonly buildSignature: string;
    readonly data: Record<string, unknown>;
    readonly installTime: DateTime | null;
    readonly installerStore: string | null;
    readonly packageName: string;
    readonly updateTime: DateTime | null;
    readonly version: string;
    static fromPlatform(options?: { baseUrl?: string | null }): Promise<PackageInfo>;
    static setMockInitialValues(options: { appName: string; packageName: string; version: string; buildNumber: string; buildSignature: string; installerStore?: string | null; installTime?: DateTime | null; updateTime?: DateTime | null }): void;
    toString(): string;
  }

  export class PackageInfoPlusLinuxPlugin {
    constructor();
    getAll(options?: { baseUrl?: string | null }): Promise<PackageInfoData>;
    static registerWith(): void;
  }

  export class PackageInfoPlusWindowsPlugin {
    constructor();
    getAll(options?: { baseUrl?: string | null }): Promise<PackageInfoData>;
    static registerWith(): void;
  }

  export const usePackageInfo: () => PackageInfo | null;
}
