// GENERATED by `bun run generate:plugin shared_preferences` from ref/plugins/shared_preferences.json — do not edit.
// shared_preferences 2.5.5

declare module 'plugin:shared_preferences' {
  export interface Object {
    readonly __external: 'Object';
  }

  export class SharedPreferences {
    clear(): Promise<boolean>;
    commit(): Promise<boolean>;
    containsKey(key: string): boolean;
    get(key: string): Object | null;
    getBool(key: string): boolean | null;
    getDouble(key: string): number | null;
    static getInstance(): Promise<SharedPreferences>;
    getInt(key: string): number | null;
    getKeys(): string[];
    getString(key: string): string | null;
    getStringList(key: string): string[] | null;
    reload(): Promise<void>;
    remove(key: string): Promise<boolean>;
    static resetStatic(): void;
    setBool(key: string, value: boolean): Promise<boolean>;
    setDouble(key: string, value: number): Promise<boolean>;
    setInt(key: string, value: number): Promise<boolean>;
    static setMockInitialValues(values: Record<string, Object>): void;
    static setPrefix(prefix: string, options?: { allowList?: string[] | null }): void;
    setString(key: string, value: string): Promise<boolean>;
    setStringList(key: string, value: string[]): Promise<boolean>;
  }

  export class SharedPreferencesAsync {
    constructor(options?: { options?: SharedPreferencesOptions });
    clear(options?: { allowList?: string[] | null }): Promise<void>;
    containsKey(key: string): Promise<boolean>;
    getAll(options?: { allowList?: string[] | null }): Promise<Record<string, Object | null>>;
    getBool(key: string): Promise<boolean | null>;
    getDouble(key: string): Promise<number | null>;
    getInt(key: string): Promise<number | null>;
    getKeys(options?: { allowList?: string[] | null }): Promise<string[]>;
    getString(key: string): Promise<string | null>;
    getStringList(key: string): Promise<string[] | null>;
    remove(key: string): Promise<void>;
    setBool(key: string, value: boolean): Promise<void>;
    setDouble(key: string, value: number): Promise<void>;
    setInt(key: string, value: number): Promise<void>;
    setString(key: string, value: string): Promise<void>;
    setStringList(key: string, value: string[]): Promise<void>;
  }

  export class SharedPreferencesOptions {
    constructor();
  }

  export class SharedPreferencesWithCache {
    readonly keys: string[];
    clear(): Promise<void>;
    containsKey(key: string): boolean;
    static create(options: { sharedPreferencesOptions?: SharedPreferencesOptions; cacheOptions: SharedPreferencesWithCacheOptions; cache?: Record<string, Object | null> | null }): Promise<SharedPreferencesWithCache>;
    get(key: string): Object | null;
    getBool(key: string): boolean | null;
    getDouble(key: string): number | null;
    getInt(key: string): number | null;
    getString(key: string): string | null;
    getStringList(key: string): string[] | null;
    reloadCache(): Promise<void>;
    remove(key: string): Promise<void>;
    setBool(key: string, value: boolean): Promise<void>;
    setDouble(key: string, value: number): Promise<void>;
    setInt(key: string, value: number): Promise<void>;
    setString(key: string, value: string): Promise<void>;
    setStringList(key: string, value: string[]): Promise<void>;
  }

  export class SharedPreferencesWithCacheOptions {
    constructor(options?: { allowList?: string[] | null });
    readonly allowList: string[] | null;
  }

  export const useSharedPreferences: () => SharedPreferences | null;
}
