// GENERATED by `bun run generate:plugin tray_manager` from ref/plugins/tray_manager.json — do not edit.
// tray_manager 0.5.3

declare module 'plugin:tray_manager' {
  export type Placement = 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight';

  export type TrayIconPosition = 'left' | 'right';

  export interface Offset {
    readonly __external: 'Offset';
  }

  export interface Rect {
    readonly __external: 'Rect';
  }

  export class Menu {
    constructor(options?: { items?: MenuItem[] | null });
    readonly items: MenuItem[] | null;
    getMenuItem(key: string): MenuItem | null;
    getMenuItemById(id: number): MenuItem | null;
    toJson(): Record<string, unknown>;
  }

  export class MenuBehavior {
    popUp(menu: Menu, options?: { position?: Offset | null; placement?: Placement }): Promise<void>;
  }

  export class MenuItem {
    constructor(options?: { key?: string | null; type?: string; label?: string | null; sublabel?: string | null; toolTip?: string | null; icon?: string | null; checked?: boolean | null; disabled?: boolean; submenu?: Menu | null; onClick?: ((menuItem: MenuItem) => void) | null; onHighlight?: ((menuItem: MenuItem) => void) | null; onLoseHighlight?: ((menuItem: MenuItem) => void) | null });
    readonly checked: boolean | null;
    readonly disabled: boolean;
    readonly icon: string | null;
    readonly id: number;
    readonly key: string | null;
    readonly label: string | null;
    readonly onClick: ((menuItem: MenuItem) => void) | null;
    readonly onHighlight: ((menuItem: MenuItem) => void) | null;
    readonly onLoseHighlight: ((menuItem: MenuItem) => void) | null;
    readonly sublabel: string | null;
    readonly submenu: Menu | null;
    readonly toolTip: string | null;
    readonly type: string;
    toJson(): Record<string, unknown>;
  }

  export class TrayListener {
    onTrayIconMouseDown(): void;
    onTrayIconMouseUp(): void;
    onTrayIconRightMouseDown(): void;
    onTrayIconRightMouseUp(): void;
    onTrayMenuItemClick(menuItem: MenuItem): void;
  }

  export class TrayManager {
    readonly hasListeners: boolean;
    addListener(listener: TrayListener): void;
    destroy(): Promise<void>;
    getBounds(): Promise<Rect | null>;
    popUpContextMenu(options?: { bringAppToFront?: boolean }): Promise<void>;
    removeListener(listener: TrayListener): void;
    setContextMenu(menu: Menu): Promise<void>;
    setIcon(iconPath: string, options?: { isTemplate?: boolean; iconPosition?: TrayIconPosition; iconSize?: number }): Promise<void>;
    setIconPosition(trayIconPosition: TrayIconPosition): Promise<void>;
    setTitle(title: string): Promise<void>;
    setToolTip(toolTip: string): Promise<void>;
  }

  export const useTrayManager: () => TrayManager;
}
