// GENERATED by `bun run generate:plugin url_launcher` from ref/plugins/url_launcher.json — do not edit.
// url_launcher 6.3.2

declare module 'plugin:url_launcher' {
  import type { Brightness } from 'flutter-tsx';

  export type LaunchMode = 'platformDefault' | 'inAppWebView' | 'inAppBrowserView' | 'externalApplication' | 'externalNonBrowserApplication';

  export class BrowserConfiguration {
    constructor(options?: { showTitle?: boolean });
    readonly showTitle: boolean;
  }

  export class WebViewConfiguration {
    constructor(options?: { enableJavaScript?: boolean; enableDomStorage?: boolean; headers?: Record<string, string> });
    readonly enableDomStorage: boolean;
    readonly enableJavaScript: boolean;
    readonly headers: Record<string, string>;
  }

  export const canLaunch: (urlString: string) => Promise<boolean>;

  export const canLaunchUrl: (url: string) => Promise<boolean>;

  export const closeInAppWebView: () => Promise<void>;

  export const closeWebView: () => Promise<void>;

  export const launch: (urlString: string, options?: { forceSafariVC?: boolean | null; forceWebView?: boolean; enableJavaScript?: boolean; enableDomStorage?: boolean; universalLinksOnly?: boolean; headers?: Record<string, string>; statusBarBrightness?: Brightness | null; webOnlyWindowName?: string | null }) => Promise<boolean>;

  export const launchUrl: (url: string, options?: { mode?: LaunchMode; webViewConfiguration?: WebViewConfiguration; browserConfiguration?: BrowserConfiguration; webOnlyWindowName?: string | null }) => Promise<boolean>;

  export const supportsCloseForLaunchMode: (mode: LaunchMode) => Promise<boolean>;

  export const supportsLaunchMode: (mode: LaunchMode) => Promise<boolean>;
}
