import { describe, expect, test } from 'bun:test';

import type { ApiSnapshot, Entity } from '@src/api/model';
import { emitDelegatesFile } from '@src/generate/delegates';
import type { DeclaredSurface } from '@src/generate/emit';
import { classEntity, param } from '@test/support/entities';

const surfaceOf = (named: string[], formNames: string[]): DeclaredSurface => ({
  named: new Set(named),
  enums: new Set(),
  handed: new Set(named),
  formNames: new Set(formNames),
  forms: { constructibles: new Map(), constantMembers: new Map() },
});

const snapshotOf = (entities: Entity[]): ApiSnapshot => ({
  meta: {
    frameworkVersion: '3.47.1',
    dartSdkVersion: '3.13.1',
    frameworkRevision: 'abc123',
  },
  hierarchy: {},
  exports: {},
  entities,
});

const layoutDelegate = classEntity('LayoutDelegate', {
  library: 'rendering',
  doc: '/// Positions children.',
  isAbstract: true,
  abstractMethods: [
    {
      name: 'performLayout',
      doc: '/// Lays the children out.',
      returnType: { kind: 'void' },
      params: [
        param('size', {
          named: false,
          required: true,
          type: { kind: 'named', name: 'Size' },
        }),
      ],
    },
    {
      name: 'shouldRelayout',
      doc: '',
      returnType: { kind: 'scalar', name: 'bool' },
      params: [
        param('oldDelegate', {
          named: false,
          required: true,
          type: { kind: 'named', name: 'LayoutDelegate' },
        }),
      ],
    },
  ],
  abstractGetters: [
    {
      name: 'extent',
      type: { kind: 'named', name: 'Size' },
      doc: '/// How far it reaches.',
    },
  ],
});

describe('emitDelegatesFile', () => {
  test('emits the complete delegates module', () => {
    // A parameter is a value Flutter hands the implementation, so it is the
    // type itself; what the implementation answers with is written, so it
    // takes every shorthand a prop of that type takes.
    const expected = `// GENERATED by \`bun run generate\` from ref/api.json — do not edit.
// Flutter 3.47.1

import type { LayoutDelegate, Size, SizeValue } from './widgets';

/**
 * What writing one of the classes an app writes itself means.
 *
 * Flutter builds none of these and hands over none of them: being one is
 * writing one. Each entry is that class's abstract surface, and every
 * member is handed the value itself first — \`self\` — so what the class
 * inherits is in reach from the members that need it.
 */
export interface DelegateImplementations {
  /**
   * Positions children.
   */
  LayoutDelegate: {
    /**
     * How far it reaches.
     */
    extent: (self: LayoutDelegate) => SizeValue;
    /**
     * Lays the children out.
     */
    performLayout: (self: LayoutDelegate, size: Size) => void;
    shouldRelayout: (self: LayoutDelegate, oldDelegate: LayoutDelegate) => boolean;
  };
}

/** What \`defineDelegate\` hands back for each name it is given. */
export interface Delegates {
  LayoutDelegate: LayoutDelegate;
}
`;

    expect(
      emitDelegatesFile(
        snapshotOf([layoutDelegate]),
        surfaceOf(['LayoutDelegate', 'Size'], ['Size']),
      ),
    ).toBe(expected);
  });

  test('a snapshot with nothing to write still declares both maps', () => {
    // The module is imported unconditionally — `defineDelegate` names these
    // types — so it has to compile whatever the SDK holds.
    const expected = `// GENERATED by \`bun run generate\` from ref/api.json — do not edit.
// Flutter 3.47.1

/**
 * What writing one of the classes an app writes itself means.
 *
 * Flutter builds none of these and hands over none of them: being one is
 * writing one. Each entry is that class's abstract surface, and every
 * member is handed the value itself first — \`self\` — so what the class
 * inherits is in reach from the members that need it.
 */
export interface DelegateImplementations {}

/** What \`defineDelegate\` hands back for each name it is given. */
export interface Delegates {}
`;

    expect(emitDelegatesFile(snapshotOf([]), surfaceOf([], []))).toBe(expected);
  });
});
