import { describe, expect, test } from 'bun:test';

import type { SiteWidget } from '@src/site/model';
import { emitExampleProbe } from '@src/site/probe';
import type { ExampleBinding } from '@src/site/synthesize';

const widget = (
  name: string,
  example: { tsx: string; complete: boolean; bindings?: ExampleBinding[] },
): SiteWidget => ({
  name,
  library: 'widgets',
  doc: '',
  props: [],
  example: { bindings: [], ...example },
  dartSignature: `${name}()`,
});

const page = {
  widgets: [
    widget('Icon', { tsx: '<Icon icon={Icons.add} />', complete: true }),
    widget('Column', {
      tsx: '<Column>\n  <Text>Item 1</Text>\n  <Text>Item 2</Text>\n</Column>',
      complete: true,
    }),
    widget('FadeTransition', {
      tsx: '<FadeTransition opacity={animation} />',
      complete: true,
      bindings: [
        {
          line: 'const animation = useAnimation({ duration: 600 });',
          imports: ['useAnimation'],
        },
      ],
    }),
    widget('Canvas', { tsx: '<Canvas painter={…} />', complete: false }),
  ],
};

describe('emitExampleProbe', () => {
  test('emits every complete example with its imports, skipping incomplete ones', () => {
    // Each example is the component it would really be, so what the probe
    // typechecks is what the docs show and what the sweep compiles.
    expect(emitExampleProbe(page)).toBe(
      `// GENERATED by \`bun run docs\` from the synthesized API-reference examples
// — do not edit. Checked by \`tsc\`: every complete example must typecheck
// against the published package surface.
import { Column, FadeTransition, Icon, Icons, Text, useAnimation } from 'flutter-tsx';

export const IconExample = () => (
  <Icon icon={Icons.add} />
);

export const ColumnExample = () => (
  <Column>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Column>
);

export const FadeTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <FadeTransition opacity={animation} />
  );
};
`,
    );
  });
});
