import { describe, expect, test } from 'bun:test';

import type { SiteWidget } from '@src/site/model';
import { emitExampleProbe } from '@src/site/probe';

const widget = (
  name: string,
  tsxExample: string,
  exampleComplete: boolean,
): SiteWidget => ({
  name,
  library: 'widgets',
  doc: '',
  props: [],
  tsxExample,
  exampleComplete,
  dartSignature: `${name}()`,
});

const page = {
  widgets: [
    widget('Icon', '<Icon icon={Icons.add} />', true),
    widget(
      'Column',
      '<Column>\n  <Text>Item 1</Text>\n  <Text>Item 2</Text>\n</Column>',
      true,
    ),
    widget('Canvas', '<Canvas painter={…} />', false),
  ],
};

describe('emitExampleProbe', () => {
  test('emits every complete example with its imports, skipping incomplete ones', () => {
    expect(emitExampleProbe(page)).toBe(
      `// GENERATED by \`bun run docs\` from the synthesized API-reference examples
// — do not edit. Checked by \`tsc\`: every complete example must typecheck
// against the published package surface.
import { Column, Icon, Icons, Text } from 'flutter-tsx';

export const examples = [
  <Icon icon={Icons.add} />,
  <Column>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Column>,
];
`,
    );
  });
});
