// GENERATED by `bun run docs` from the synthesized API-reference examples
// — do not edit. Checked by `tsc`: every complete example must typecheck
// against the published package surface.
import {
  AboutDialog,
  AboutListTile,
  AbsorbPointer,
  ActionChip,
  ActionIconTheme,
  AdaptiveTextSelectionToolbar,
  AlertDialog,
  Align,
  AlignTransition,
  AndroidView,
  AnimatedAlign,
  AnimatedBuilder,
  AnimatedContainer,
  AnimatedCrossFade,
  AnimatedDefaultTextStyle,
  AnimatedFractionallySizedBox,
  AnimatedGrid,
  AnimatedIcon,
  AnimatedList,
  AnimatedModalBarrier,
  AnimatedOpacity,
  AnimatedPadding,
  AnimatedPhysicalModel,
  AnimatedPositioned,
  AnimatedPositionedDirectional,
  AnimatedRotation,
  AnimatedScale,
  AnimatedSize,
  AnimatedSlide,
  AnimatedSwitcher,
  AnimatedTheme,
  AppBar,
  AppBarTheme,
  AppKitView,
  AspectRatio,
  AutocompleteHighlightedOption,
  AutofillGroup,
  AutomaticKeepAlive,
  BackButton,
  BackButtonIcon,
  BackdropGroup,
  Badge,
  BadgeTheme,
  Banner,
  Baseline,
  BlockSemantics,
  BottomAppBar,
  BottomAppBarTheme,
  BottomNavigationBar,
  BottomNavigationBarTheme,
  BottomSheet,
  BoxDecoration,
  Builder,
  ButtonBar,
  ButtonBarTheme,
  ButtonTheme,
  CalendarDatePicker,
  Card,
  CardTheme,
  CarouselView,
  CarouselViewTheme,
  Center,
  Checkbox,
  CheckboxListTile,
  CheckboxMenuButton,
  CheckboxTheme,
  CheckedModeBanner,
  CheckedPopupMenuItem,
  Chip,
  ChipTheme,
  ChoiceChip,
  CircleAvatar,
  CircularProgressIndicator,
  ClipOval,
  ClipPath,
  ClipRRect,
  ClipRSuperellipse,
  ClipRect,
  CloseButton,
  CloseButtonIcon,
  ColoredBox,
  Column,
  CompositedTransformFollower,
  CompositedTransformTarget,
  ConstrainedBox,
  Container,
  CupertinoActionSheet,
  CupertinoActionSheetAction,
  CupertinoActivityIndicator,
  CupertinoAdaptiveTextSelectionToolbar,
  CupertinoAlertDialog,
  CupertinoApp,
  CupertinoButton,
  CupertinoCheckbox,
  CupertinoContextMenu,
  CupertinoContextMenuAction,
  CupertinoDatePicker,
  CupertinoDesktopTextSelectionControls,
  CupertinoDesktopTextSelectionToolbar,
  CupertinoDesktopTextSelectionToolbarButton,
  CupertinoDialogAction,
  CupertinoExpansionTile,
  CupertinoFormRow,
  CupertinoFormSection,
  CupertinoFullscreenDialogTransition,
  CupertinoLinearActivityIndicator,
  CupertinoListSection,
  CupertinoListTile,
  CupertinoListTileChevron,
  CupertinoMagnifier,
  CupertinoMenuAnchor,
  CupertinoMenuDivider,
  CupertinoMenuItem,
  CupertinoNavigationBar,
  CupertinoNavigationBarBackButton,
  CupertinoPageScaffold,
  CupertinoPageScaffoldBackgroundColor,
  CupertinoPageTransition,
  CupertinoPicker,
  CupertinoPickerDefaultSelectionOverlay,
  CupertinoPopupSurface,
  CupertinoScrollbar,
  CupertinoSearchTextField,
  CupertinoSheetTransition,
  CupertinoSlider,
  CupertinoSliverNavigationBar,
  CupertinoSliverRefreshControl,
  CupertinoSpellCheckSuggestionsToolbar,
  CupertinoSwitch,
  CupertinoTabBar,
  CupertinoTabView,
  CupertinoTextField,
  CupertinoTextFormFieldRow,
  CupertinoTextMagnifier,
  CupertinoTextSelectionToolbar,
  CupertinoTextSelectionToolbarButton,
  CupertinoTheme,
  CupertinoTimerPicker,
  CupertinoUserInterfaceLevel,
  CustomPaint,
  CustomScrollView,
  CustomSingleChildLayout,
  DataTable,
  DataTableTheme,
  DatePickerDialog,
  DatePickerTheme,
  DateRangePickerDialog,
  DecoratedBox,
  DecoratedBoxTransition,
  DecoratedSliver,
  DefaultAssetBundle,
  DefaultSelectionStyle,
  DefaultTabController,
  DefaultTextEditingShortcuts,
  DefaultTextHeightBehavior,
  DefaultTextStyle,
  DefaultTextStyleTransition,
  DesktopTextSelectionToolbar,
  DesktopTextSelectionToolbarButton,
  DesktopTextSelectionToolbarLayoutDelegate,
  DeviceOrientationBuilder,
  Dialog,
  DialogTheme,
  Directionality,
  DisableWidgetInspectorScope,
  Dismissible,
  DisplayFeatureSubScreen,
  Divider,
  DividerTheme,
  DragBoundary,
  DragTarget,
  Draggable,
  DraggableScrollableActuator,
  DraggableScrollableSheet,
  Drawer,
  DrawerButton,
  DrawerButtonIcon,
  DrawerController,
  DrawerHeader,
  DrawerTheme,
  DropdownButton,
  DropdownButtonFormField,
  DropdownButtonHideUnderline,
  DropdownMenu,
  DropdownMenuFormField,
  DropdownMenuItem,
  DropdownMenuTheme,
  DualTransitionBuilder,
  EditableText,
  ElevatedButton,
  ElevatedButtonTheme,
  EnableWidgetInspectorScope,
  EndDrawerButton,
  EndDrawerButtonIcon,
  ExcludeFocus,
  ExcludeFocusTraversal,
  ExcludeSemantics,
  ExpandIcon,
  Expanded,
  Expansible,
  ExpansibleController,
  ExpansionPanelList,
  ExpansionTile,
  ExpansionTileTheme,
  FadeTransition,
  FilledButton,
  FilledButtonTheme,
  FilterChip,
  FittedBox,
  Flex,
  Flexible,
  FlexibleSpaceBar,
  FlexibleSpaceBarSettings,
  FloatingActionButton,
  FloatingActionButtonTheme,
  FlutterLogo,
  Focus,
  FocusNode,
  FocusScope,
  FocusTraversalGroup,
  FocusTraversalOrder,
  FocusableActionDetector,
  Form,
  FormField,
  FractionalTranslation,
  FractionallySizedBox,
  GestureDetector,
  GlowingOverscrollIndicator,
  GridPaper,
  GridTile,
  GridTileBar,
  GridView,
  HeroController,
  HeroControllerScope,
  HeroMode,
  HtmlElementView,
  Icon,
  IconButton,
  IconButtonTheme,
  IconTheme,
  IgnoreBaseline,
  IgnorePointer,
  IndexedSemantics,
  IndexedStack,
  Ink,
  InkResponse,
  InkWell,
  InputChip,
  InputDatePickerFormField,
  InputDecorationTheme,
  InputDecorator,
  InteractiveViewer,
  IntrinsicHeight,
  IntrinsicWidth,
  KeepAlive,
  KeyboardListener,
  KeyedSubtree,
  LayerLink,
  LayoutBuilder,
  LexicalFocusOrder,
  LicensePage,
  LimitedBox,
  LinearProgressIndicator,
  ListBody,
  ListTile,
  ListTileTheme,
  ListView,
  ListWheelScrollView,
  ListenableBuilder,
  Listener,
  Locale,
  Localizations,
  LongPressDraggable,
  LookupBoundary,
  Magnifier,
  MagnifierController,
  Material,
  MaterialApp,
  MaterialBanner,
  MaterialBannerTheme,
  MaterialButton,
  Matrix4,
  MediaQuery,
  MenuAcceleratorCallbackBinding,
  MenuAcceleratorLabel,
  MenuAnchor,
  MenuBar,
  MenuBarTheme,
  MenuButtonTheme,
  MenuController,
  MenuItemButton,
  MenuTheme,
  MergeSemantics,
  MergeableMaterial,
  MetaData,
  ModalBarrier,
  MouseRegion,
  NavigationBar,
  NavigationBarTheme,
  NavigationDestination,
  NavigationDrawer,
  NavigationDrawerDestination,
  NavigationDrawerTheme,
  NavigationIndicator,
  NavigationRail,
  NavigationRailTheme,
  NavigationToolbar,
  Navigator,
  NavigatorPopHandler,
  NestedScrollView,
  NestedScrollViewViewport,
  NotificationListener,
  Offstage,
  Opacity,
  OrientationBuilder,
  OutlinedButton,
  OutlinedButtonTheme,
  OverflowBar,
  OverflowBox,
  Overlay,
  OverlayPortal,
  OverlayPortalController,
  Padding,
  PageStorage,
  PageStorageBucket,
  PageView,
  PerformanceOverlay,
  PhysicalModel,
  PinnedHeaderSliver,
  Placeholder,
  PlatformAssetBundle,
  PlatformMenuBar,
  PlatformSelectableRegionContextMenu,
  PopScope,
  PopupMenuButton,
  PopupMenuDivider,
  PopupMenuItem,
  PopupMenuTheme,
  Positioned,
  PositionedDirectional,
  PositionedTransition,
  PreferredSize,
  PrimaryScrollController,
  ProgressIndicatorTheme,
  RadioGroup,
  RadioTheme,
  RangeSlider,
  RangeValues,
  RawChip,
  RawGestureDetector,
  RawImage,
  RawKeyboardListener,
  RawMagnifier,
  RawMaterialButton,
  RawMenuAnchor,
  RawMenuAnchorGroup,
  RawScrollbar,
  RawTooltip,
  RefreshProgressIndicator,
  RelativePositionedTransition,
  RenderAbsorbPointer,
  ReorderableDelayedDragStartListener,
  ReorderableDragStartListener,
  ReorderableList,
  ReorderableListView,
  RepaintBoundary,
  RestorationScope,
  RichText,
  RootRestorationScope,
  RootWidget,
  RotatedBox,
  RotationTransition,
  Row,
  SafeArea,
  Scaffold,
  ScaffoldMessenger,
  ScaleTransition,
  ScrollBehavior,
  ScrollConfiguration,
  ScrollController,
  ScrollNotificationObserver,
  ScrollPositionWithSingleContext,
  Scrollable,
  ScrollableDetails,
  ScrollableState,
  Scrollbar,
  ScrollbarTheme,
  SearchBar,
  SearchBarTheme,
  SearchViewTheme,
  SegmentedButtonTheme,
  SelectableRegion,
  SelectableRegionState,
  SelectableText,
  SelectionArea,
  SelectionContainer,
  SelectionListener,
  SelectionListenerNotifier,
  SelectionRegistrarScope,
  Semantics,
  SemanticsDebugger,
  SensitiveContent,
  SharedAppData,
  ShortcutRegistrar,
  ShrinkWrappingViewport,
  SimpleDialog,
  SimpleDialogOption,
  SingleChildScrollView,
  SizeChangedLayoutNotifier,
  SizeTransition,
  SizedBox,
  SizedOverflowBox,
  SlideTransition,
  Slider,
  SliderTheme,
  SliverAnimatedGrid,
  SliverAnimatedList,
  SliverAnimatedOpacity,
  SliverAppBar,
  SliverConstrainedCrossAxis,
  SliverCrossAxisExpanded,
  SliverCrossAxisGroup,
  SliverEnsureSemantics,
  SliverFadeTransition,
  SliverFillRemaining,
  SliverFloatingHeader,
  SliverGridDelegateWithFixedCrossAxisCount,
  SliverIgnorePointer,
  SliverLayoutBuilder,
  SliverMainAxisGroup,
  SliverOffstage,
  SliverOpacity,
  SliverOverlapAbsorber,
  SliverOverlapAbsorberHandle,
  SliverOverlapInjector,
  SliverPadding,
  SliverReorderableList,
  SliverResizingHeader,
  SliverSafeArea,
  SliverSemantics,
  SliverToBoxAdapter,
  SliverVisibility,
  SnackBar,
  SnackBarAction,
  SnackBarTheme,
  SnapshotController,
  SnapshotWidget,
  Spacer,
  SpellCheckSuggestionsToolbar,
  Stack,
  StatefulBuilder,
  StaticSelectionContainerDelegate,
  Stepper,
  StretchEffect,
  StretchingOverscrollIndicator,
  SubmenuButton,
  Switch,
  SwitchListTile,
  SwitchTheme,
  Tab,
  TabBar,
  TabBarTheme,
  TabBarView,
  TabPageSelector,
  TabPageSelectorIndicator,
  Table,
  TableCell,
  TableRowInkWell,
  TapRegion,
  TapRegionSurface,
  Text,
  TextButton,
  TextButtonTheme,
  TextEditingController,
  TextField,
  TextFieldTapRegion,
  TextFormField,
  TextMagnifier,
  TextSelectionGestureDetector,
  TextSelectionTheme,
  TextSelectionToolbar,
  TextSelectionToolbarAnchors,
  TextSelectionToolbarTextButton,
  TextSpan,
  Texture,
  Theme,
  ThemeData,
  TickerMode,
  TimePickerDialog,
  TimePickerTheme,
  Title,
  ToggleButtons,
  ToggleButtonsTheme,
  Tooltip,
  TooltipTheme,
  TooltipVisibility,
  Transform,
  TreeSliver,
  Tween,
  TweenAnimationBuilder,
  TwoDimensionalScrollable,
  UiKitView,
  UnconstrainedBox,
  UnmanagedRestorationScope,
  UserAccountsDrawerHeader,
  ValueNotifier,
  VerticalDivider,
  ViewAnchor,
  ViewCollection,
  Viewport,
  Visibility,
  WidgetToRenderBoxAdapter,
  WidgetsApp,
  Wrap,
  YearPicker,
  tween,
  useAnimation,
} from 'flutter-tsx';

export const AboutDialogExample = () => (
  <AboutDialog>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </AboutDialog>
);

export const AboutListTileExample = () => (
  <AboutListTile>
    <Text>Content</Text>
  </AboutListTile>
);

export const AbsorbPointerExample = () => (
  <AbsorbPointer>
    <Text>Content</Text>
  </AbsorbPointer>
);

export const ActionChipExample = () => (
  <ActionChip label={<Text>Content</Text>} />
);

export const ActionIconThemeExample = () => (
  <ActionIconTheme data={{}}>
    <Text>Content</Text>
  </ActionIconTheme>
);

export const AdaptiveTextSelectionToolbarExample = () => (
  <AdaptiveTextSelectionToolbar
    anchors={new TextSelectionToolbarAnchors({ primaryAnchor: 'infinite' })}
  >
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </AdaptiveTextSelectionToolbar>
);

export const AlertDialogExample = () => <AlertDialog />;

export const AlignExample = () => (
  <Align>
    <Text>Content</Text>
  </Align>
);

export const AlignTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <AlignTransition
      alignment={tween(animation, { from: 'bottomCenter', to: 'bottomCenter' })}
    >
      <Text>Content</Text>
    </AlignTransition>
  );
};

export const AndroidViewExample = () => <AndroidView viewType="example" />;

export const AnimatedAlignExample = () => (
  <AnimatedAlign alignment="bottomCenter" duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedAlign>
);

export const AnimatedBuilderExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <AnimatedBuilder animation={animation} builder={() => <Text>Content</Text>}>
      <Text>Content</Text>
    </AnimatedBuilder>
  );
};

export const AnimatedContainerExample = () => (
  <AnimatedContainer duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedContainer>
);

export const AnimatedCrossFadeExample = () => (
  <AnimatedCrossFade
    firstChild={<Text>Content</Text>}
    secondChild={<Text>Content</Text>}
    crossFadeState="showFirst"
    duration="defaultAnimationDuration"
  />
);

export const AnimatedDefaultTextStyleExample = () => (
  <AnimatedDefaultTextStyle
    style="cupertinoMisspelledTextStyle"
    duration="defaultAnimationDuration"
  >
    <Text>Content</Text>
  </AnimatedDefaultTextStyle>
);

export const AnimatedFractionallySizedBoxExample = () => (
  <AnimatedFractionallySizedBox duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedFractionallySizedBox>
);

export const AnimatedGridExample = () => (
  <AnimatedGrid
    itemBuilder={() => <Text>Content</Text>}
    gridDelegate={
      new SliverGridDelegateWithFixedCrossAxisCount({ crossAxisCount: 8 })
    }
  />
);

export const AnimatedIconExample = () => {
  const animation = useAnimation({ duration: 600 });

  return <AnimatedIcon icon="add_event" progress={animation} />;
};

export const AnimatedListExample = () => (
  <AnimatedList itemBuilder={() => <Text>Content</Text>} />
);

export const AnimatedModalBarrierExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <AnimatedModalBarrier
      color={tween(animation, { from: 'activeBlue', to: 'activeBlue' })}
    />
  );
};

export const AnimatedOpacityExample = () => (
  <AnimatedOpacity opacity={1} duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedOpacity>
);

export const AnimatedPaddingExample = () => (
  <AnimatedPadding padding="infinity" duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedPadding>
);

export const AnimatedPhysicalModelExample = () => (
  <AnimatedPhysicalModel
    color="activeBlue"
    shadowColor="activeBlue"
    duration="defaultAnimationDuration"
  >
    <Text>Content</Text>
  </AnimatedPhysicalModel>
);

export const AnimatedPositionedExample = () => (
  <AnimatedPositioned duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedPositioned>
);

export const AnimatedPositionedDirectionalExample = () => (
  <AnimatedPositionedDirectional duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedPositionedDirectional>
);

export const AnimatedRotationExample = () => (
  <AnimatedRotation turns={1} duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedRotation>
);

export const AnimatedScaleExample = () => (
  <AnimatedScale scale={1} duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedScale>
);

export const AnimatedSizeExample = () => (
  <AnimatedSize duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedSize>
);

export const AnimatedSlideExample = () => (
  <AnimatedSlide offset="infinite" duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedSlide>
);

export const AnimatedSwitcherExample = () => (
  <AnimatedSwitcher duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedSwitcher>
);

export const AnimatedThemeExample = () => {
  const themeData = new ThemeData();

  return (
    <AnimatedTheme data={themeData}>
      <Text>Content</Text>
    </AnimatedTheme>
  );
};

export const AppBarExample = () => <AppBar />;

export const AppBarThemeExample = () => (
  <AppBarTheme>
    <Text>Content</Text>
  </AppBarTheme>
);

export const AppKitViewExample = () => <AppKitView viewType="example" />;

export const AspectRatioExample = () => (
  <AspectRatio aspectRatio={1}>
    <Text>Content</Text>
  </AspectRatio>
);

export const AutocompleteHighlightedOptionExample = () => (
  <AutocompleteHighlightedOption highlightIndexNotifier={new ValueNotifier(8)}>
    <Text>Content</Text>
  </AutocompleteHighlightedOption>
);

export const AutofillGroupExample = () => (
  <AutofillGroup>
    <Text>Content</Text>
  </AutofillGroup>
);

export const AutomaticKeepAliveExample = () => (
  <AutomaticKeepAlive>
    <Text>Content</Text>
  </AutomaticKeepAlive>
);

export const BackButtonExample = () => <BackButton />;

export const BackButtonIconExample = () => <BackButtonIcon />;

export const BackdropGroupExample = () => (
  <BackdropGroup>
    <Text>Content</Text>
  </BackdropGroup>
);

export const BadgeExample = () => (
  <Badge>
    <Text>Content</Text>
  </Badge>
);

export const BadgeThemeExample = () => (
  <BadgeTheme data={{}}>
    <Text>Content</Text>
  </BadgeTheme>
);

export const BannerExample = () => (
  <Banner message="example" location="topStart">
    <Text>Content</Text>
  </Banner>
);

export const BaselineExample = () => (
  <Baseline baseline={1} baselineType="alphabetic">
    <Text>Content</Text>
  </Baseline>
);

export const BlockSemanticsExample = () => (
  <BlockSemantics>
    <Text>Content</Text>
  </BlockSemantics>
);

export const BottomAppBarExample = () => (
  <BottomAppBar>
    <Text>Content</Text>
  </BottomAppBar>
);

export const BottomAppBarThemeExample = () => (
  <BottomAppBarTheme>
    <Text>Content</Text>
  </BottomAppBarTheme>
);

export const BottomNavigationBarExample = () => (
  <BottomNavigationBar items={[]} />
);

export const BottomNavigationBarThemeExample = () => (
  <BottomNavigationBarTheme data={{}}>
    <Text>Content</Text>
  </BottomNavigationBarTheme>
);

export const BottomSheetExample = () => (
  <BottomSheet onClosing={() => {}} builder={() => <Text>Content</Text>} />
);

export const BuilderExample = () => (
  <Builder builder={() => <Text>Content</Text>} />
);

export const ButtonBarExample = () => (
  <ButtonBar>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ButtonBar>
);

export const ButtonBarThemeExample = () => (
  <ButtonBarTheme data={{}}>
    <Text>Content</Text>
  </ButtonBarTheme>
);

export const ButtonThemeExample = () => (
  <ButtonTheme>
    <Text>Content</Text>
  </ButtonTheme>
);

export const CalendarDatePickerExample = () => (
  <CalendarDatePicker
    initialDate="2026-01-31"
    firstDate="2026-01-31"
    lastDate="2026-01-31"
    onDateChanged={() => {}}
  />
);

export const CardExample = () => (
  <Card>
    <Text>Content</Text>
  </Card>
);

export const CardThemeExample = () => (
  <CardTheme>
    <Text>Content</Text>
  </CardTheme>
);

export const CarouselViewExample = () => (
  <CarouselView itemExtent={1}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CarouselView>
);

export const CarouselViewThemeExample = () => (
  <CarouselViewTheme data={{}}>
    <Text>Content</Text>
  </CarouselViewTheme>
);

export const CenterExample = () => (
  <Center>
    <Text>Content</Text>
  </Center>
);

export const CheckboxExample = () => (
  <Checkbox value={true} onChanged={() => {}} />
);

export const CheckboxListTileExample = () => (
  <CheckboxListTile value={true} onChanged={() => {}} />
);

export const CheckboxMenuButtonExample = () => (
  <CheckboxMenuButton value={true} onChanged={() => {}}>
    <Text>Content</Text>
  </CheckboxMenuButton>
);

export const CheckboxThemeExample = () => (
  <CheckboxTheme data={{}}>
    <Text>Content</Text>
  </CheckboxTheme>
);

export const CheckedModeBannerExample = () => (
  <CheckedModeBanner>
    <Text>Content</Text>
  </CheckedModeBanner>
);

export const CheckedPopupMenuItemExample = () => (
  <CheckedPopupMenuItem>
    <Text>Content</Text>
  </CheckedPopupMenuItem>
);

export const ChipExample = () => <Chip label={<Text>Content</Text>} />;

export const ChipThemeExample = () => (
  <ChipTheme data={{}}>
    <Text>Content</Text>
  </ChipTheme>
);

export const ChoiceChipExample = () => (
  <ChoiceChip label={<Text>Content</Text>} selected={true} />
);

export const CircleAvatarExample = () => (
  <CircleAvatar>
    <Text>Content</Text>
  </CircleAvatar>
);

export const CircularProgressIndicatorExample = () => (
  <CircularProgressIndicator />
);

export const ClipOvalExample = () => (
  <ClipOval>
    <Text>Content</Text>
  </ClipOval>
);

export const ClipPathExample = () => (
  <ClipPath>
    <Text>Content</Text>
  </ClipPath>
);

export const ClipRRectExample = () => (
  <ClipRRect>
    <Text>Content</Text>
  </ClipRRect>
);

export const ClipRSuperellipseExample = () => (
  <ClipRSuperellipse>
    <Text>Content</Text>
  </ClipRSuperellipse>
);

export const ClipRectExample = () => (
  <ClipRect>
    <Text>Content</Text>
  </ClipRect>
);

export const CloseButtonExample = () => <CloseButton />;

export const CloseButtonIconExample = () => <CloseButtonIcon />;

export const ColoredBoxExample = () => (
  <ColoredBox color="activeBlue">
    <Text>Content</Text>
  </ColoredBox>
);

export const ColumnExample = () => (
  <Column>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Column>
);

export const CompositedTransformFollowerExample = () => {
  const layerLink = new LayerLink();

  return (
    <CompositedTransformFollower link={layerLink}>
      <Text>Content</Text>
    </CompositedTransformFollower>
  );
};

export const CompositedTransformTargetExample = () => {
  const layerLink = new LayerLink();

  return (
    <CompositedTransformTarget link={layerLink}>
      <Text>Content</Text>
    </CompositedTransformTarget>
  );
};

export const ConstrainedBoxExample = () => (
  <ConstrainedBox constraints={{}}>
    <Text>Content</Text>
  </ConstrainedBox>
);

export const ContainerExample = () => (
  <Container>
    <Text>Content</Text>
  </Container>
);

export const CupertinoActionSheetExample = () => (
  <CupertinoActionSheet actions={[]} />
);

export const CupertinoActionSheetActionExample = () => (
  <CupertinoActionSheetAction onClick={() => {}}>
    <Text>Content</Text>
  </CupertinoActionSheetAction>
);

export const CupertinoActivityIndicatorExample = () => (
  <CupertinoActivityIndicator />
);

export const CupertinoAdaptiveTextSelectionToolbarExample = () => (
  <CupertinoAdaptiveTextSelectionToolbar
    anchors={new TextSelectionToolbarAnchors({ primaryAnchor: 'infinite' })}
  >
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoAdaptiveTextSelectionToolbar>
);

export const CupertinoAlertDialogExample = () => <CupertinoAlertDialog />;

export const CupertinoAppExample = () => <CupertinoApp />;

export const CupertinoButtonExample = () => (
  <CupertinoButton onClick={() => {}}>
    <Text>Content</Text>
  </CupertinoButton>
);

export const CupertinoCheckboxExample = () => (
  <CupertinoCheckbox value={true} onChanged={() => {}} />
);

export const CupertinoContextMenuExample = () => (
  <CupertinoContextMenu actions={[]}>
    <Text>Content</Text>
  </CupertinoContextMenu>
);

export const CupertinoContextMenuActionExample = () => (
  <CupertinoContextMenuAction>
    <Text>Content</Text>
  </CupertinoContextMenuAction>
);

export const CupertinoDatePickerExample = () => (
  <CupertinoDatePicker onDateTimeChanged={() => {}} />
);

export const CupertinoDesktopTextSelectionToolbarExample = () => (
  <CupertinoDesktopTextSelectionToolbar anchor="infinite">
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoDesktopTextSelectionToolbar>
);

export const CupertinoDesktopTextSelectionToolbarButtonExample = () => (
  <CupertinoDesktopTextSelectionToolbarButton onClick={() => {}}>
    <Text>Content</Text>
  </CupertinoDesktopTextSelectionToolbarButton>
);

export const CupertinoDialogActionExample = () => (
  <CupertinoDialogAction>
    <Text>Content</Text>
  </CupertinoDialogAction>
);

export const CupertinoExpansionTileExample = () => (
  <CupertinoExpansionTile title={<Text>Content</Text>}>
    <Text>Content</Text>
  </CupertinoExpansionTile>
);

export const CupertinoFormRowExample = () => (
  <CupertinoFormRow>
    <Text>Content</Text>
  </CupertinoFormRow>
);

export const CupertinoFormSectionExample = () => (
  <CupertinoFormSection>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoFormSection>
);

export const CupertinoFullscreenDialogTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <CupertinoFullscreenDialogTransition
      primaryRouteAnimation={animation}
      secondaryRouteAnimation={animation}
      linearTransition={true}
    >
      <Text>Content</Text>
    </CupertinoFullscreenDialogTransition>
  );
};

export const CupertinoLinearActivityIndicatorExample = () => (
  <CupertinoLinearActivityIndicator progress={1} />
);

export const CupertinoListSectionExample = () => (
  <CupertinoListSection>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoListSection>
);

export const CupertinoListTileExample = () => (
  <CupertinoListTile title={<Text>Content</Text>} />
);

export const CupertinoListTileChevronExample = () => (
  <CupertinoListTileChevron />
);

export const CupertinoMagnifierExample = () => <CupertinoMagnifier />;

export const CupertinoMenuAnchorExample = () => (
  <CupertinoMenuAnchor menuChildren={[]}>
    <Text>Content</Text>
  </CupertinoMenuAnchor>
);

export const CupertinoMenuDividerExample = () => <CupertinoMenuDivider />;

export const CupertinoMenuItemExample = () => (
  <CupertinoMenuItem>
    <Text>Content</Text>
  </CupertinoMenuItem>
);

export const CupertinoNavigationBarExample = () => <CupertinoNavigationBar />;

export const CupertinoNavigationBarBackButtonExample = () => (
  <CupertinoNavigationBarBackButton />
);

export const CupertinoPageScaffoldExample = () => (
  <CupertinoPageScaffold>
    <Text>Content</Text>
  </CupertinoPageScaffold>
);

export const CupertinoPageScaffoldBackgroundColorExample = () => (
  <CupertinoPageScaffoldBackgroundColor color="activeBlue">
    <Text>Content</Text>
  </CupertinoPageScaffoldBackgroundColor>
);

export const CupertinoPageTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <CupertinoPageTransition
      primaryRouteAnimation={animation}
      secondaryRouteAnimation={animation}
      linearTransition={true}
    >
      <Text>Content</Text>
    </CupertinoPageTransition>
  );
};

export const CupertinoPickerExample = () => (
  <CupertinoPicker itemExtent={1} onSelectedItemChanged={() => {}}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoPicker>
);

export const CupertinoPickerDefaultSelectionOverlayExample = () => (
  <CupertinoPickerDefaultSelectionOverlay />
);

export const CupertinoPopupSurfaceExample = () => (
  <CupertinoPopupSurface>
    <Text>Content</Text>
  </CupertinoPopupSurface>
);

export const CupertinoScrollbarExample = () => (
  <CupertinoScrollbar>
    <Text>Content</Text>
  </CupertinoScrollbar>
);

export const CupertinoSearchTextFieldExample = () => (
  <CupertinoSearchTextField />
);

export const CupertinoSheetTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <CupertinoSheetTransition
      primaryRouteAnimation={animation}
      secondaryRouteAnimation={animation}
      linearTransition={true}
    >
      <Text>Content</Text>
    </CupertinoSheetTransition>
  );
};

export const CupertinoSliderExample = () => (
  <CupertinoSlider value={1} onChanged={() => {}} />
);

export const CupertinoSliverNavigationBarExample = () => (
  <CupertinoSliverNavigationBar />
);

export const CupertinoSliverRefreshControlExample = () => (
  <CupertinoSliverRefreshControl />
);

export const CupertinoSpellCheckSuggestionsToolbarExample = () => (
  <CupertinoSpellCheckSuggestionsToolbar
    anchors={new TextSelectionToolbarAnchors({ primaryAnchor: 'infinite' })}
    buttonItems={[]}
  />
);

export const CupertinoSwitchExample = () => (
  <CupertinoSwitch value={true} onChanged={() => {}} />
);

export const CupertinoTabBarExample = () => <CupertinoTabBar items={[]} />;

export const CupertinoTabViewExample = () => <CupertinoTabView />;

export const CupertinoTextFieldExample = () => <CupertinoTextField />;

export const CupertinoTextFormFieldRowExample = () => (
  <CupertinoTextFormFieldRow />
);

export const CupertinoTextMagnifierExample = () => {
  const magnifierController = new MagnifierController();

  return (
    <CupertinoTextMagnifier
      controller={magnifierController}
      magnifierInfo={new ValueNotifier('empty')}
    />
  );
};

export const CupertinoTextSelectionToolbarExample = () => (
  <CupertinoTextSelectionToolbar anchorAbove="infinite" anchorBelow="infinite">
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoTextSelectionToolbar>
);

export const CupertinoTextSelectionToolbarButtonExample = () => (
  <CupertinoTextSelectionToolbarButton>
    <Text>Content</Text>
  </CupertinoTextSelectionToolbarButton>
);

export const CupertinoThemeExample = () => (
  <CupertinoTheme data={{}}>
    <Text>Content</Text>
  </CupertinoTheme>
);

export const CupertinoTimerPickerExample = () => (
  <CupertinoTimerPicker onTimerDurationChanged={() => {}} />
);

export const CupertinoUserInterfaceLevelExample = () => (
  <CupertinoUserInterfaceLevel data="base">
    <Text>Content</Text>
  </CupertinoUserInterfaceLevel>
);

export const CustomPaintExample = () => (
  <CustomPaint>
    <Text>Content</Text>
  </CustomPaint>
);

export const CustomScrollViewExample = () => <CustomScrollView />;

export const CustomSingleChildLayoutExample = () => (
  <CustomSingleChildLayout
    delegate={
      new DesktopTextSelectionToolbarLayoutDelegate({ anchor: 'infinite' })
    }
  >
    <Text>Content</Text>
  </CustomSingleChildLayout>
);

export const DataTableExample = () => <DataTable columns={[]} rows={[]} />;

export const DataTableThemeExample = () => (
  <DataTableTheme data={{}}>
    <Text>Content</Text>
  </DataTableTheme>
);

export const DatePickerDialogExample = () => (
  <DatePickerDialog firstDate="2026-01-31" lastDate="2026-01-31" />
);

export const DatePickerThemeExample = () => (
  <DatePickerTheme data={{}}>
    <Text>Content</Text>
  </DatePickerTheme>
);

export const DateRangePickerDialogExample = () => (
  <DateRangePickerDialog firstDate="2026-01-31" lastDate="2026-01-31" />
);

export const DecoratedBoxExample = () => (
  <DecoratedBox decoration={new BoxDecoration()}>
    <Text>Content</Text>
  </DecoratedBox>
);

export const DecoratedBoxTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <DecoratedBoxTransition
      decoration={tween(animation, {
        from: new BoxDecoration(),
        to: new BoxDecoration(),
      })}
    >
      <Text>Content</Text>
    </DecoratedBoxTransition>
  );
};

export const DecoratedSliverExample = () => (
  <DecoratedSliver decoration={new BoxDecoration()} />
);

export const DefaultAssetBundleExample = () => (
  <DefaultAssetBundle bundle={new PlatformAssetBundle()}>
    <Text>Content</Text>
  </DefaultAssetBundle>
);

export const DefaultSelectionStyleExample = () => (
  <DefaultSelectionStyle>
    <Text>Content</Text>
  </DefaultSelectionStyle>
);

export const DefaultTabControllerExample = () => (
  <DefaultTabController length={8}>
    <Text>Content</Text>
  </DefaultTabController>
);

export const DefaultTextEditingShortcutsExample = () => (
  <DefaultTextEditingShortcuts>
    <Text>Content</Text>
  </DefaultTextEditingShortcuts>
);

export const DefaultTextHeightBehaviorExample = () => (
  <DefaultTextHeightBehavior textHeightBehavior={{}}>
    <Text>Content</Text>
  </DefaultTextHeightBehavior>
);

export const DefaultTextStyleExample = () => (
  <DefaultTextStyle style="cupertinoMisspelledTextStyle">
    <Text>Content</Text>
  </DefaultTextStyle>
);

export const DefaultTextStyleTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <DefaultTextStyleTransition
      style={tween(animation, {
        from: 'cupertinoMisspelledTextStyle',
        to: 'cupertinoMisspelledTextStyle',
      })}
    >
      <Text>Content</Text>
    </DefaultTextStyleTransition>
  );
};

export const DesktopTextSelectionToolbarExample = () => (
  <DesktopTextSelectionToolbar anchor="infinite">
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </DesktopTextSelectionToolbar>
);

export const DesktopTextSelectionToolbarButtonExample = () => (
  <DesktopTextSelectionToolbarButton onClick={() => {}}>
    <Text>Content</Text>
  </DesktopTextSelectionToolbarButton>
);

export const DeviceOrientationBuilderExample = () => (
  <DeviceOrientationBuilder builder={() => <Text>Content</Text>} />
);

export const DialogExample = () => (
  <Dialog>
    <Text>Content</Text>
  </Dialog>
);

export const DialogThemeExample = () => (
  <DialogTheme>
    <Text>Content</Text>
  </DialogTheme>
);

export const DirectionalityExample = () => (
  <Directionality textDirection="rtl">
    <Text>Content</Text>
  </Directionality>
);

export const DisableWidgetInspectorScopeExample = () => (
  <DisableWidgetInspectorScope>
    <Text>Content</Text>
  </DisableWidgetInspectorScope>
);

export const DismissibleExample = () => (
  <Dismissible key="example">
    <Text>Content</Text>
  </Dismissible>
);

export const DisplayFeatureSubScreenExample = () => (
  <DisplayFeatureSubScreen>
    <Text>Content</Text>
  </DisplayFeatureSubScreen>
);

export const DividerExample = () => <Divider />;

export const DividerThemeExample = () => (
  <DividerTheme data={{}}>
    <Text>Content</Text>
  </DividerTheme>
);

export const DragBoundaryExample = () => (
  <DragBoundary>
    <Text>Content</Text>
  </DragBoundary>
);

export const DragTargetExample = () => (
  <DragTarget builder={() => <Text>Content</Text>} />
);

export const DraggableExample = () => (
  <Draggable feedback={<Text>Content</Text>}>
    <Text>Content</Text>
  </Draggable>
);

export const DraggableScrollableActuatorExample = () => (
  <DraggableScrollableActuator>
    <Text>Content</Text>
  </DraggableScrollableActuator>
);

export const DraggableScrollableSheetExample = () => (
  <DraggableScrollableSheet builder={() => <Text>Content</Text>} />
);

export const DrawerExample = () => (
  <Drawer>
    <Text>Content</Text>
  </Drawer>
);

export const DrawerButtonExample = () => <DrawerButton />;

export const DrawerButtonIconExample = () => <DrawerButtonIcon />;

export const DrawerControllerExample = () => (
  <DrawerController alignment="start">
    <Text>Content</Text>
  </DrawerController>
);

export const DrawerHeaderExample = () => (
  <DrawerHeader>
    <Text>Content</Text>
  </DrawerHeader>
);

export const DrawerThemeExample = () => (
  <DrawerTheme data={{}}>
    <Text>Content</Text>
  </DrawerTheme>
);

export const DropdownButtonExample = () => (
  <DropdownButton items={[]} onChanged={() => {}} />
);

export const DropdownButtonFormFieldExample = () => (
  <DropdownButtonFormField items={[]} onChanged={() => {}} />
);

export const DropdownButtonHideUnderlineExample = () => (
  <DropdownButtonHideUnderline>
    <Text>Content</Text>
  </DropdownButtonHideUnderline>
);

export const DropdownMenuExample = () => (
  <DropdownMenu dropdownMenuEntries={[]} />
);

export const DropdownMenuFormFieldExample = () => (
  <DropdownMenuFormField dropdownMenuEntries={[]} />
);

export const DropdownMenuItemExample = () => (
  <DropdownMenuItem>
    <Text>Content</Text>
  </DropdownMenuItem>
);

export const DropdownMenuThemeExample = () => (
  <DropdownMenuTheme data={{}}>
    <Text>Content</Text>
  </DropdownMenuTheme>
);

export const DualTransitionBuilderExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <DualTransitionBuilder
      animation={animation}
      forwardBuilder={() => <Text>Content</Text>}
      reverseBuilder={() => <Text>Content</Text>}
    >
      <Text>Content</Text>
    </DualTransitionBuilder>
  );
};

export const EditableTextExample = () => {
  const textEditingController = new TextEditingController();
  const focusNode = new FocusNode();

  return (
    <EditableText
      controller={textEditingController}
      focusNode={focusNode}
      style="cupertinoMisspelledTextStyle"
      cursorColor="activeBlue"
      backgroundCursorColor="activeBlue"
    />
  );
};

export const ElevatedButtonExample = () => (
  <ElevatedButton onClick={() => {}}>
    <Text>Content</Text>
  </ElevatedButton>
);

export const ElevatedButtonThemeExample = () => (
  <ElevatedButtonTheme data={{}}>
    <Text>Content</Text>
  </ElevatedButtonTheme>
);

export const EnableWidgetInspectorScopeExample = () => (
  <EnableWidgetInspectorScope>
    <Text>Content</Text>
  </EnableWidgetInspectorScope>
);

export const EndDrawerButtonExample = () => <EndDrawerButton />;

export const EndDrawerButtonIconExample = () => <EndDrawerButtonIcon />;

export const ExcludeFocusExample = () => (
  <ExcludeFocus>
    <Text>Content</Text>
  </ExcludeFocus>
);

export const ExcludeFocusTraversalExample = () => (
  <ExcludeFocusTraversal>
    <Text>Content</Text>
  </ExcludeFocusTraversal>
);

export const ExcludeSemanticsExample = () => (
  <ExcludeSemantics>
    <Text>Content</Text>
  </ExcludeSemantics>
);

export const ExpandIconExample = () => <ExpandIcon onClick={() => {}} />;

export const ExpandedExample = () => (
  <Expanded>
    <Text>Content</Text>
  </Expanded>
);

export const ExpansibleExample = () => {
  const expansibleController = new ExpansibleController();

  return (
    <Expansible
      headerBuilder={() => <Text>Content</Text>}
      bodyBuilder={() => <Text>Content</Text>}
      controller={expansibleController}
    />
  );
};

export const ExpansionPanelListExample = () => <ExpansionPanelList />;

export const ExpansionTileExample = () => (
  <ExpansionTile title={<Text>Content</Text>}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ExpansionTile>
);

export const ExpansionTileThemeExample = () => (
  <ExpansionTileTheme data={{}}>
    <Text>Content</Text>
  </ExpansionTileTheme>
);

export const FadeTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <FadeTransition opacity={animation}>
      <Text>Content</Text>
    </FadeTransition>
  );
};

export const FilledButtonExample = () => (
  <FilledButton onClick={() => {}}>
    <Text>Content</Text>
  </FilledButton>
);

export const FilledButtonThemeExample = () => (
  <FilledButtonTheme data={{}}>
    <Text>Content</Text>
  </FilledButtonTheme>
);

export const FilterChipExample = () => (
  <FilterChip label={<Text>Content</Text>} onSelected={() => {}} />
);

export const FittedBoxExample = () => (
  <FittedBox>
    <Text>Content</Text>
  </FittedBox>
);

export const FlexExample = () => (
  <Flex direction="horizontal">
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Flex>
);

export const FlexibleExample = () => (
  <Flexible>
    <Text>Content</Text>
  </Flexible>
);

export const FlexibleSpaceBarExample = () => <FlexibleSpaceBar />;

export const FlexibleSpaceBarSettingsExample = () => (
  <FlexibleSpaceBarSettings
    toolbarOpacity={1}
    minExtent={1}
    maxExtent={1}
    currentExtent={1}
  >
    <Text>Content</Text>
  </FlexibleSpaceBarSettings>
);

export const FloatingActionButtonExample = () => (
  <FloatingActionButton onClick={() => {}}>
    <Text>Content</Text>
  </FloatingActionButton>
);

export const FloatingActionButtonThemeExample = () => (
  <FloatingActionButtonTheme data={{}}>
    <Text>Content</Text>
  </FloatingActionButtonTheme>
);

export const FlutterLogoExample = () => <FlutterLogo />;

export const FocusExample = () => (
  <Focus>
    <Text>Content</Text>
  </Focus>
);

export const FocusScopeExample = () => (
  <FocusScope>
    <Text>Content</Text>
  </FocusScope>
);

export const FocusTraversalGroupExample = () => (
  <FocusTraversalGroup>
    <Text>Content</Text>
  </FocusTraversalGroup>
);

export const FocusTraversalOrderExample = () => (
  <FocusTraversalOrder order={new LexicalFocusOrder('example')}>
    <Text>Content</Text>
  </FocusTraversalOrder>
);

export const FocusableActionDetectorExample = () => (
  <FocusableActionDetector>
    <Text>Content</Text>
  </FocusableActionDetector>
);

export const FormExample = () => (
  <Form>
    <Text>Content</Text>
  </Form>
);

export const FormFieldExample = () => (
  <FormField builder={() => <Text>Content</Text>} />
);

export const FractionalTranslationExample = () => (
  <FractionalTranslation translation="infinite">
    <Text>Content</Text>
  </FractionalTranslation>
);

export const FractionallySizedBoxExample = () => (
  <FractionallySizedBox>
    <Text>Content</Text>
  </FractionallySizedBox>
);

export const GestureDetectorExample = () => (
  <GestureDetector>
    <Text>Content</Text>
  </GestureDetector>
);

export const GlowingOverscrollIndicatorExample = () => (
  <GlowingOverscrollIndicator axisDirection="up" color="activeBlue">
    <Text>Content</Text>
  </GlowingOverscrollIndicator>
);

export const GridPaperExample = () => (
  <GridPaper>
    <Text>Content</Text>
  </GridPaper>
);

export const GridTileExample = () => (
  <GridTile>
    <Text>Content</Text>
  </GridTile>
);

export const GridTileBarExample = () => <GridTileBar />;

export const GridViewExample = () => (
  <GridView
    gridDelegate={
      new SliverGridDelegateWithFixedCrossAxisCount({ crossAxisCount: 8 })
    }
  >
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </GridView>
);

export const HeroControllerScopeExample = () => {
  const heroController = new HeroController();

  return (
    <HeroControllerScope controller={heroController}>
      <Text>Content</Text>
    </HeroControllerScope>
  );
};

export const HeroModeExample = () => (
  <HeroMode>
    <Text>Content</Text>
  </HeroMode>
);

export const HtmlElementViewExample = () => (
  <HtmlElementView viewType="example" />
);

export const IconExample = () => <Icon icon="abc" />;

export const IconButtonExample = () => (
  <IconButton onClick={() => {}} icon={<Text>Content</Text>} />
);

export const IconButtonThemeExample = () => (
  <IconButtonTheme data={{}}>
    <Text>Content</Text>
  </IconButtonTheme>
);

export const IconThemeExample = () => (
  <IconTheme data={{}}>
    <Text>Content</Text>
  </IconTheme>
);

export const IgnoreBaselineExample = () => (
  <IgnoreBaseline>
    <Text>Content</Text>
  </IgnoreBaseline>
);

export const IgnorePointerExample = () => (
  <IgnorePointer>
    <Text>Content</Text>
  </IgnorePointer>
);

export const IndexedSemanticsExample = () => (
  <IndexedSemantics index={8}>
    <Text>Content</Text>
  </IndexedSemantics>
);

export const IndexedStackExample = () => (
  <IndexedStack>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </IndexedStack>
);

export const InkExample = () => (
  <Ink>
    <Text>Content</Text>
  </Ink>
);

export const InkResponseExample = () => (
  <InkResponse>
    <Text>Content</Text>
  </InkResponse>
);

export const InkWellExample = () => (
  <InkWell>
    <Text>Content</Text>
  </InkWell>
);

export const InputChipExample = () => (
  <InputChip label={<Text>Content</Text>} />
);

export const InputDatePickerFormFieldExample = () => (
  <InputDatePickerFormField firstDate="2026-01-31" lastDate="2026-01-31" />
);

export const InputDecorationThemeExample = () => (
  <InputDecorationTheme>
    <Text>Content</Text>
  </InputDecorationTheme>
);

export const InputDecoratorExample = () => (
  <InputDecorator decoration={{}}>
    <Text>Content</Text>
  </InputDecorator>
);

export const InteractiveViewerExample = () => (
  <InteractiveViewer>
    <Text>Content</Text>
  </InteractiveViewer>
);

export const IntrinsicHeightExample = () => (
  <IntrinsicHeight>
    <Text>Content</Text>
  </IntrinsicHeight>
);

export const IntrinsicWidthExample = () => (
  <IntrinsicWidth>
    <Text>Content</Text>
  </IntrinsicWidth>
);

export const KeepAliveExample = () => (
  <KeepAlive keepAlive={true}>
    <Text>Content</Text>
  </KeepAlive>
);

export const KeyboardListenerExample = () => {
  const focusNode = new FocusNode();

  return (
    <KeyboardListener focusNode={focusNode}>
      <Text>Content</Text>
    </KeyboardListener>
  );
};

export const KeyedSubtreeExample = () => (
  <KeyedSubtree>
    <Text>Content</Text>
  </KeyedSubtree>
);

export const LayoutBuilderExample = () => (
  <LayoutBuilder builder={() => <Text>Content</Text>} />
);

export const LicensePageExample = () => <LicensePage />;

export const LimitedBoxExample = () => (
  <LimitedBox>
    <Text>Content</Text>
  </LimitedBox>
);

export const LinearProgressIndicatorExample = () => <LinearProgressIndicator />;

export const ListBodyExample = () => (
  <ListBody>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ListBody>
);

export const ListTileExample = () => <ListTile />;

export const ListTileThemeExample = () => (
  <ListTileTheme>
    <Text>Content</Text>
  </ListTileTheme>
);

export const ListViewExample = () => (
  <ListView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ListView>
);

export const ListWheelScrollViewExample = () => (
  <ListWheelScrollView itemExtent={1}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ListWheelScrollView>
);

export const ListenableBuilderExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <ListenableBuilder
      listenable={animation}
      builder={() => <Text>Content</Text>}
    >
      <Text>Content</Text>
    </ListenableBuilder>
  );
};

export const ListenerExample = () => (
  <Listener>
    <Text>Content</Text>
  </Listener>
);

export const LocalizationsExample = () => (
  <Localizations locale={new Locale('example')} delegates={[]}>
    <Text>Content</Text>
  </Localizations>
);

export const LongPressDraggableExample = () => (
  <LongPressDraggable feedback={<Text>Content</Text>}>
    <Text>Content</Text>
  </LongPressDraggable>
);

export const LookupBoundaryExample = () => (
  <LookupBoundary>
    <Text>Content</Text>
  </LookupBoundary>
);

export const MagnifierExample = () => <Magnifier />;

export const MaterialExample = () => (
  <Material>
    <Text>Content</Text>
  </Material>
);

export const MaterialAppExample = () => <MaterialApp />;

export const MaterialBannerExample = () => (
  <MaterialBanner content={<Text>Content</Text>} actions={[]} />
);

export const MaterialBannerThemeExample = () => (
  <MaterialBannerTheme>
    <Text>Content</Text>
  </MaterialBannerTheme>
);

export const MaterialButtonExample = () => (
  <MaterialButton onClick={() => {}}>
    <Text>Content</Text>
  </MaterialButton>
);

export const MediaQueryExample = () => (
  <MediaQuery data={{}}>
    <Text>Content</Text>
  </MediaQuery>
);

export const MenuAcceleratorCallbackBindingExample = () => (
  <MenuAcceleratorCallbackBinding>
    <Text>Content</Text>
  </MenuAcceleratorCallbackBinding>
);

export const MenuAcceleratorLabelExample = () => (
  <MenuAcceleratorLabel>Hello world</MenuAcceleratorLabel>
);

export const MenuAnchorExample = () => (
  <MenuAnchor menuChildren={[]}>
    <Text>Content</Text>
  </MenuAnchor>
);

export const MenuBarExample = () => (
  <MenuBar>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </MenuBar>
);

export const MenuBarThemeExample = () => (
  <MenuBarTheme data={{}}>
    <Text>Content</Text>
  </MenuBarTheme>
);

export const MenuButtonThemeExample = () => (
  <MenuButtonTheme data={{}}>
    <Text>Content</Text>
  </MenuButtonTheme>
);

export const MenuItemButtonExample = () => (
  <MenuItemButton>
    <Text>Content</Text>
  </MenuItemButton>
);

export const MenuThemeExample = () => (
  <MenuTheme data={{}}>
    <Text>Content</Text>
  </MenuTheme>
);

export const MergeSemanticsExample = () => (
  <MergeSemantics>
    <Text>Content</Text>
  </MergeSemantics>
);

export const MergeableMaterialExample = () => <MergeableMaterial />;

export const MetaDataExample = () => (
  <MetaData>
    <Text>Content</Text>
  </MetaData>
);

export const ModalBarrierExample = () => <ModalBarrier />;

export const MouseRegionExample = () => (
  <MouseRegion>
    <Text>Content</Text>
  </MouseRegion>
);

export const NavigationBarExample = () => <NavigationBar destinations={[]} />;

export const NavigationBarThemeExample = () => (
  <NavigationBarTheme data={{}}>
    <Text>Content</Text>
  </NavigationBarTheme>
);

export const NavigationDestinationExample = () => (
  <NavigationDestination icon={<Text>Content</Text>} label="example" />
);

export const NavigationDrawerExample = () => (
  <NavigationDrawer>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </NavigationDrawer>
);

export const NavigationDrawerDestinationExample = () => (
  <NavigationDrawerDestination
    icon={<Text>Content</Text>}
    label={<Text>Content</Text>}
  />
);

export const NavigationDrawerThemeExample = () => (
  <NavigationDrawerTheme data={{}}>
    <Text>Content</Text>
  </NavigationDrawerTheme>
);

export const NavigationIndicatorExample = () => {
  const animation = useAnimation({ duration: 600 });

  return <NavigationIndicator animation={animation} />;
};

export const NavigationRailExample = () => (
  <NavigationRail destinations={[]} selectedIndex={8} />
);

export const NavigationRailThemeExample = () => (
  <NavigationRailTheme data={{}}>
    <Text>Content</Text>
  </NavigationRailTheme>
);

export const NavigationToolbarExample = () => <NavigationToolbar />;

export const NavigatorExample = () => <Navigator />;

export const NavigatorPopHandlerExample = () => (
  <NavigatorPopHandler>
    <Text>Content</Text>
  </NavigatorPopHandler>
);

export const NestedScrollViewExample = () => (
  <NestedScrollView headerSliverBuilder={() => []}>
    <Text>Content</Text>
  </NestedScrollView>
);

export const NestedScrollViewViewportExample = () => {
  const sliverOverlapAbsorberHandle = new SliverOverlapAbsorberHandle();

  return (
    <NestedScrollViewViewport
      offset={
        new ScrollPositionWithSingleContext({
          physics: {},
          context: new ScrollableState(),
        })
      }
      handle={sliverOverlapAbsorberHandle}
    />
  );
};

export const NotificationListenerExample = () => (
  <NotificationListener>
    <Text>Content</Text>
  </NotificationListener>
);

export const OffstageExample = () => (
  <Offstage>
    <Text>Content</Text>
  </Offstage>
);

export const OpacityExample = () => (
  <Opacity opacity={1}>
    <Text>Content</Text>
  </Opacity>
);

export const OrientationBuilderExample = () => (
  <OrientationBuilder builder={() => <Text>Content</Text>} />
);

export const OutlinedButtonExample = () => (
  <OutlinedButton onClick={() => {}}>
    <Text>Content</Text>
  </OutlinedButton>
);

export const OutlinedButtonThemeExample = () => (
  <OutlinedButtonTheme data={{}}>
    <Text>Content</Text>
  </OutlinedButtonTheme>
);

export const OverflowBarExample = () => (
  <OverflowBar>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </OverflowBar>
);

export const OverflowBoxExample = () => (
  <OverflowBox>
    <Text>Content</Text>
  </OverflowBox>
);

export const OverlayExample = () => <Overlay />;

export const OverlayPortalExample = () => {
  const overlayPortalController = new OverlayPortalController();

  return (
    <OverlayPortal
      controller={overlayPortalController}
      overlayChildBuilder={() => <Text>Content</Text>}
    >
      <Text>Content</Text>
    </OverlayPortal>
  );
};

export const PaddingExample = () => (
  <Padding padding="infinity">
    <Text>Content</Text>
  </Padding>
);

export const PageStorageExample = () => {
  const pageStorageBucket = new PageStorageBucket();

  return (
    <PageStorage bucket={pageStorageBucket}>
      <Text>Content</Text>
    </PageStorage>
  );
};

export const PageViewExample = () => (
  <PageView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </PageView>
);

export const PerformanceOverlayExample = () => <PerformanceOverlay />;

export const PhysicalModelExample = () => (
  <PhysicalModel color="activeBlue">
    <Text>Content</Text>
  </PhysicalModel>
);

export const PinnedHeaderSliverExample = () => (
  <PinnedHeaderSliver>
    <Text>Content</Text>
  </PinnedHeaderSliver>
);

export const PlaceholderExample = () => (
  <Placeholder>
    <Text>Content</Text>
  </Placeholder>
);

export const PlatformMenuBarExample = () => (
  <PlatformMenuBar menus={[]}>
    <Text>Content</Text>
  </PlatformMenuBar>
);

export const PlatformSelectableRegionContextMenuExample = () => (
  <PlatformSelectableRegionContextMenu>
    <Text>Content</Text>
  </PlatformSelectableRegionContextMenu>
);

export const PopScopeExample = () => (
  <PopScope>
    <Text>Content</Text>
  </PopScope>
);

export const PopupMenuButtonExample = () => (
  <PopupMenuButton itemBuilder={() => []}>
    <Text>Content</Text>
  </PopupMenuButton>
);

export const PopupMenuDividerExample = () => <PopupMenuDivider />;

export const PopupMenuItemExample = () => (
  <PopupMenuItem>
    <Text>Content</Text>
  </PopupMenuItem>
);

export const PopupMenuThemeExample = () => (
  <PopupMenuTheme data={{}}>
    <Text>Content</Text>
  </PopupMenuTheme>
);

export const PositionedExample = () => (
  <Positioned>
    <Text>Content</Text>
  </Positioned>
);

export const PositionedDirectionalExample = () => (
  <PositionedDirectional>
    <Text>Content</Text>
  </PositionedDirectional>
);

export const PositionedTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <PositionedTransition rect={tween(animation, { from: 'fill', to: 'fill' })}>
      <Text>Content</Text>
    </PositionedTransition>
  );
};

export const PreferredSizeExample = () => (
  <PreferredSize preferredSize="infinite">
    <Text>Content</Text>
  </PreferredSize>
);

export const PrimaryScrollControllerExample = () => {
  const scrollController = new ScrollController();

  return (
    <PrimaryScrollController controller={scrollController}>
      <Text>Content</Text>
    </PrimaryScrollController>
  );
};

export const ProgressIndicatorThemeExample = () => (
  <ProgressIndicatorTheme data={{}}>
    <Text>Content</Text>
  </ProgressIndicatorTheme>
);

export const RadioGroupExample = () => (
  <RadioGroup onChanged={() => {}}>
    <Text>Content</Text>
  </RadioGroup>
);

export const RadioThemeExample = () => (
  <RadioTheme data={{}}>
    <Text>Content</Text>
  </RadioTheme>
);

export const RangeSliderExample = () => (
  <RangeSlider values={new RangeValues(1, 1)} onChanged={() => {}} />
);

export const RawChipExample = () => <RawChip label={<Text>Content</Text>} />;

export const RawGestureDetectorExample = () => (
  <RawGestureDetector>
    <Text>Content</Text>
  </RawGestureDetector>
);

export const RawImageExample = () => <RawImage />;

export const RawKeyboardListenerExample = () => {
  const focusNode = new FocusNode();

  return (
    <RawKeyboardListener focusNode={focusNode}>
      <Text>Content</Text>
    </RawKeyboardListener>
  );
};

export const RawMagnifierExample = () => (
  <RawMagnifier size="infinite">
    <Text>Content</Text>
  </RawMagnifier>
);

export const RawMaterialButtonExample = () => (
  <RawMaterialButton onClick={() => {}}>
    <Text>Content</Text>
  </RawMaterialButton>
);

export const RawMenuAnchorExample = () => {
  const menuController = new MenuController();

  return (
    <RawMenuAnchor
      controller={menuController}
      overlayBuilder={() => <Text>Content</Text>}
    >
      <Text>Content</Text>
    </RawMenuAnchor>
  );
};

export const RawMenuAnchorGroupExample = () => {
  const menuController = new MenuController();

  return (
    <RawMenuAnchorGroup controller={menuController}>
      <Text>Content</Text>
    </RawMenuAnchorGroup>
  );
};

export const RawScrollbarExample = () => (
  <RawScrollbar>
    <Text>Content</Text>
  </RawScrollbar>
);

export const RawTooltipExample = () => (
  <RawTooltip
    semanticsTooltip="example"
    tooltipBuilder={() => <Text>Content</Text>}
  >
    <Text>Content</Text>
  </RawTooltip>
);

export const RefreshProgressIndicatorExample = () => (
  <RefreshProgressIndicator />
);

export const RelativePositionedTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <RelativePositionedTransition
      rect={tween(animation, { from: 'largest', to: 'largest' })}
      size="infinite"
    >
      <Text>Content</Text>
    </RelativePositionedTransition>
  );
};

export const ReorderableDelayedDragStartListenerExample = () => (
  <ReorderableDelayedDragStartListener index={8}>
    <Text>Content</Text>
  </ReorderableDelayedDragStartListener>
);

export const ReorderableDragStartListenerExample = () => (
  <ReorderableDragStartListener index={8}>
    <Text>Content</Text>
  </ReorderableDragStartListener>
);

export const ReorderableListExample = () => (
  <ReorderableList itemBuilder={() => <Text>Content</Text>} itemCount={8} />
);

export const ReorderableListViewExample = () => (
  <ReorderableListView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ReorderableListView>
);

export const RepaintBoundaryExample = () => (
  <RepaintBoundary>
    <Text>Content</Text>
  </RepaintBoundary>
);

export const RestorationScopeExample = () => (
  <RestorationScope restorationId="example">
    <Text>Content</Text>
  </RestorationScope>
);

export const RichTextExample = () => <RichText text={new TextSpan()} />;

export const RootRestorationScopeExample = () => (
  <RootRestorationScope restorationId="example">
    <Text>Content</Text>
  </RootRestorationScope>
);

export const RootWidgetExample = () => (
  <RootWidget>
    <Text>Content</Text>
  </RootWidget>
);

export const RotatedBoxExample = () => (
  <RotatedBox quarterTurns={8}>
    <Text>Content</Text>
  </RotatedBox>
);

export const RotationTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <RotationTransition turns={animation}>
      <Text>Content</Text>
    </RotationTransition>
  );
};

export const RowExample = () => (
  <Row>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Row>
);

export const SafeAreaExample = () => (
  <SafeArea>
    <Text>Content</Text>
  </SafeArea>
);

export const ScaffoldExample = () => (
  <Scaffold>
    <Text>Content</Text>
  </Scaffold>
);

export const ScaffoldMessengerExample = () => (
  <ScaffoldMessenger>
    <Text>Content</Text>
  </ScaffoldMessenger>
);

export const ScaleTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <ScaleTransition scale={animation}>
      <Text>Content</Text>
    </ScaleTransition>
  );
};

export const ScrollConfigurationExample = () => (
  <ScrollConfiguration behavior={new ScrollBehavior()}>
    <Text>Content</Text>
  </ScrollConfiguration>
);

export const ScrollNotificationObserverExample = () => (
  <ScrollNotificationObserver>
    <Text>Content</Text>
  </ScrollNotificationObserver>
);

export const ScrollableExample = () => (
  <Scrollable viewportBuilder={() => <Text>Content</Text>} />
);

export const ScrollbarExample = () => (
  <Scrollbar>
    <Text>Content</Text>
  </Scrollbar>
);

export const ScrollbarThemeExample = () => (
  <ScrollbarTheme data={{}}>
    <Text>Content</Text>
  </ScrollbarTheme>
);

export const SearchBarExample = () => <SearchBar />;

export const SearchBarThemeExample = () => (
  <SearchBarTheme data={{}}>
    <Text>Content</Text>
  </SearchBarTheme>
);

export const SearchViewThemeExample = () => (
  <SearchViewTheme data={{}}>
    <Text>Content</Text>
  </SearchViewTheme>
);

export const SegmentedButtonThemeExample = () => (
  <SegmentedButtonTheme data={{}}>
    <Text>Content</Text>
  </SegmentedButtonTheme>
);

export const SelectableRegionExample = () => (
  <SelectableRegion
    selectionControls={new CupertinoDesktopTextSelectionControls()}
  >
    <Text>Content</Text>
  </SelectableRegion>
);

export const SelectableTextExample = () => (
  <SelectableText>Hello world</SelectableText>
);

export const SelectionAreaExample = () => (
  <SelectionArea>
    <Text>Content</Text>
  </SelectionArea>
);

export const SelectionContainerExample = () => (
  <SelectionContainer delegate={new StaticSelectionContainerDelegate()}>
    <Text>Content</Text>
  </SelectionContainer>
);

export const SelectionListenerExample = () => {
  const selectionListenerNotifier = new SelectionListenerNotifier();

  return (
    <SelectionListener selectionNotifier={selectionListenerNotifier}>
      <Text>Content</Text>
    </SelectionListener>
  );
};

export const SelectionRegistrarScopeExample = () => (
  <SelectionRegistrarScope registrar={new SelectableRegionState()}>
    <Text>Content</Text>
  </SelectionRegistrarScope>
);

export const SemanticsExample = () => (
  <Semantics>
    <Text>Content</Text>
  </Semantics>
);

export const SemanticsDebuggerExample = () => (
  <SemanticsDebugger>
    <Text>Content</Text>
  </SemanticsDebugger>
);

export const SensitiveContentExample = () => (
  <SensitiveContent sensitivity="autoSensitive">
    <Text>Content</Text>
  </SensitiveContent>
);

export const SharedAppDataExample = () => (
  <SharedAppData>
    <Text>Content</Text>
  </SharedAppData>
);

export const ShortcutRegistrarExample = () => (
  <ShortcutRegistrar>
    <Text>Content</Text>
  </ShortcutRegistrar>
);

export const ShrinkWrappingViewportExample = () => (
  <ShrinkWrappingViewport
    offset={
      new ScrollPositionWithSingleContext({
        physics: {},
        context: new ScrollableState(),
      })
    }
  />
);

export const SimpleDialogExample = () => (
  <SimpleDialog>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </SimpleDialog>
);

export const SimpleDialogOptionExample = () => (
  <SimpleDialogOption>
    <Text>Content</Text>
  </SimpleDialogOption>
);

export const SingleChildScrollViewExample = () => (
  <SingleChildScrollView>
    <Text>Content</Text>
  </SingleChildScrollView>
);

export const SizeChangedLayoutNotifierExample = () => (
  <SizeChangedLayoutNotifier>
    <Text>Content</Text>
  </SizeChangedLayoutNotifier>
);

export const SizeTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <SizeTransition sizeFactor={animation}>
      <Text>Content</Text>
    </SizeTransition>
  );
};

export const SizedBoxExample = () => (
  <SizedBox>
    <Text>Content</Text>
  </SizedBox>
);

export const SizedOverflowBoxExample = () => (
  <SizedOverflowBox size="infinite">
    <Text>Content</Text>
  </SizedOverflowBox>
);

export const SlideTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return (
    <SlideTransition
      position={tween(animation, { from: 'infinite', to: 'infinite' })}
    >
      <Text>Content</Text>
    </SlideTransition>
  );
};

export const SliderExample = () => <Slider value={1} onChanged={() => {}} />;

export const SliderThemeExample = () => (
  <SliderTheme data={{}}>
    <Text>Content</Text>
  </SliderTheme>
);

export const SliverAnimatedGridExample = () => (
  <SliverAnimatedGrid
    itemBuilder={() => <Text>Content</Text>}
    gridDelegate={
      new SliverGridDelegateWithFixedCrossAxisCount({ crossAxisCount: 8 })
    }
  />
);

export const SliverAnimatedListExample = () => (
  <SliverAnimatedList itemBuilder={() => <Text>Content</Text>} />
);

export const SliverAnimatedOpacityExample = () => (
  <SliverAnimatedOpacity opacity={1} duration="defaultAnimationDuration" />
);

export const SliverAppBarExample = () => <SliverAppBar />;

export const SliverConstrainedCrossAxisExample = () => (
  <SliverConstrainedCrossAxis maxExtent={1} sliver={<Text>Content</Text>} />
);

export const SliverCrossAxisExpandedExample = () => (
  <SliverCrossAxisExpanded flex={8} sliver={<Text>Content</Text>} />
);

export const SliverCrossAxisGroupExample = () => (
  <SliverCrossAxisGroup slivers={[]} />
);

export const SliverEnsureSemanticsExample = () => (
  <SliverEnsureSemantics sliver={<Text>Content</Text>} />
);

export const SliverFadeTransitionExample = () => {
  const animation = useAnimation({ duration: 600 });

  return <SliverFadeTransition opacity={animation} />;
};

export const SliverFillRemainingExample = () => (
  <SliverFillRemaining>
    <Text>Content</Text>
  </SliverFillRemaining>
);

export const SliverFloatingHeaderExample = () => (
  <SliverFloatingHeader>
    <Text>Content</Text>
  </SliverFloatingHeader>
);

export const SliverIgnorePointerExample = () => <SliverIgnorePointer />;

export const SliverLayoutBuilderExample = () => (
  <SliverLayoutBuilder builder={() => <Text>Content</Text>} />
);

export const SliverMainAxisGroupExample = () => (
  <SliverMainAxisGroup slivers={[]} />
);

export const SliverOffstageExample = () => <SliverOffstage />;

export const SliverOpacityExample = () => <SliverOpacity opacity={1} />;

export const SliverOverlapAbsorberExample = () => {
  const sliverOverlapAbsorberHandle = new SliverOverlapAbsorberHandle();

  return <SliverOverlapAbsorber handle={sliverOverlapAbsorberHandle} />;
};

export const SliverOverlapInjectorExample = () => {
  const sliverOverlapAbsorberHandle = new SliverOverlapAbsorberHandle();

  return <SliverOverlapInjector handle={sliverOverlapAbsorberHandle} />;
};

export const SliverPaddingExample = () => <SliverPadding padding="infinity" />;

export const SliverReorderableListExample = () => (
  <SliverReorderableList
    itemBuilder={() => <Text>Content</Text>}
    itemCount={8}
  />
);

export const SliverResizingHeaderExample = () => (
  <SliverResizingHeader>
    <Text>Content</Text>
  </SliverResizingHeader>
);

export const SliverSafeAreaExample = () => (
  <SliverSafeArea sliver={<Text>Content</Text>} />
);

export const SliverSemanticsExample = () => (
  <SliverSemantics sliver={<Text>Content</Text>} />
);

export const SliverToBoxAdapterExample = () => (
  <SliverToBoxAdapter>
    <Text>Content</Text>
  </SliverToBoxAdapter>
);

export const SliverVisibilityExample = () => (
  <SliverVisibility sliver={<Text>Content</Text>} />
);

export const SnackBarExample = () => (
  <SnackBar content={<Text>Content</Text>} />
);

export const SnackBarActionExample = () => (
  <SnackBarAction label="example" onClick={() => {}} />
);

export const SnackBarThemeExample = () => (
  <SnackBarTheme data={{}}>
    <Text>Content</Text>
  </SnackBarTheme>
);

export const SnapshotWidgetExample = () => {
  const snapshotController = new SnapshotController();

  return (
    <SnapshotWidget controller={snapshotController}>
      <Text>Content</Text>
    </SnapshotWidget>
  );
};

export const SpacerExample = () => <Spacer />;

export const SpellCheckSuggestionsToolbarExample = () => (
  <SpellCheckSuggestionsToolbar anchor="infinite" buttonItems={[]} />
);

export const StackExample = () => (
  <Stack>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Stack>
);

export const StatefulBuilderExample = () => (
  <StatefulBuilder builder={() => <Text>Content</Text>} />
);

export const StepperExample = () => <Stepper steps={[]} />;

export const StretchEffectExample = () => (
  <StretchEffect axis="horizontal">
    <Text>Content</Text>
  </StretchEffect>
);

export const StretchingOverscrollIndicatorExample = () => (
  <StretchingOverscrollIndicator axisDirection="up">
    <Text>Content</Text>
  </StretchingOverscrollIndicator>
);

export const SubmenuButtonExample = () => (
  <SubmenuButton menuChildren={[]}>
    <Text>Content</Text>
  </SubmenuButton>
);

export const SwitchExample = () => <Switch value={true} onChanged={() => {}} />;

export const SwitchListTileExample = () => (
  <SwitchListTile value={true} onChanged={() => {}} />
);

export const SwitchThemeExample = () => (
  <SwitchTheme data={{}}>
    <Text>Content</Text>
  </SwitchTheme>
);

export const TabExample = () => (
  <Tab>
    <Text>Content</Text>
  </Tab>
);

export const TabBarExample = () => <TabBar tabs={[]} />;

export const TabBarThemeExample = () => (
  <TabBarTheme>
    <Text>Content</Text>
  </TabBarTheme>
);

export const TabBarViewExample = () => (
  <TabBarView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </TabBarView>
);

export const TabPageSelectorExample = () => <TabPageSelector />;

export const TabPageSelectorIndicatorExample = () => (
  <TabPageSelectorIndicator
    backgroundColor="activeBlue"
    borderColor="activeBlue"
    size={1}
  />
);

export const TableExample = () => <Table />;

export const TableCellExample = () => (
  <TableCell>
    <Text>Content</Text>
  </TableCell>
);

export const TableRowInkWellExample = () => (
  <TableRowInkWell>
    <Text>Content</Text>
  </TableRowInkWell>
);

export const TapRegionExample = () => (
  <TapRegion>
    <Text>Content</Text>
  </TapRegion>
);

export const TapRegionSurfaceExample = () => (
  <TapRegionSurface>
    <Text>Content</Text>
  </TapRegionSurface>
);

export const TextExample = () => <Text>Hello world</Text>;

export const TextButtonExample = () => (
  <TextButton onClick={() => {}}>
    <Text>Content</Text>
  </TextButton>
);

export const TextButtonThemeExample = () => (
  <TextButtonTheme data={{}}>
    <Text>Content</Text>
  </TextButtonTheme>
);

export const TextFieldExample = () => <TextField />;

export const TextFieldTapRegionExample = () => (
  <TextFieldTapRegion>
    <Text>Content</Text>
  </TextFieldTapRegion>
);

export const TextFormFieldExample = () => <TextFormField />;

export const TextMagnifierExample = () => (
  <TextMagnifier magnifierInfo={new ValueNotifier('empty')} />
);

export const TextSelectionGestureDetectorExample = () => (
  <TextSelectionGestureDetector>
    <Text>Content</Text>
  </TextSelectionGestureDetector>
);

export const TextSelectionThemeExample = () => (
  <TextSelectionTheme data={{}}>
    <Text>Content</Text>
  </TextSelectionTheme>
);

export const TextSelectionToolbarExample = () => (
  <TextSelectionToolbar anchorAbove="infinite" anchorBelow="infinite">
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </TextSelectionToolbar>
);

export const TextSelectionToolbarTextButtonExample = () => (
  <TextSelectionToolbarTextButton padding="infinity">
    <Text>Content</Text>
  </TextSelectionToolbarTextButton>
);

export const TextureExample = () => <Texture textureId={8} />;

export const ThemeExample = () => {
  const themeData = new ThemeData();

  return (
    <Theme data={themeData}>
      <Text>Content</Text>
    </Theme>
  );
};

export const TickerModeExample = () => (
  <TickerMode enabled={true}>
    <Text>Content</Text>
  </TickerMode>
);

export const TimePickerDialogExample = () => (
  <TimePickerDialog initialTime="09:30" />
);

export const TimePickerThemeExample = () => (
  <TimePickerTheme data={{}}>
    <Text>Content</Text>
  </TimePickerTheme>
);

export const TitleExample = () => (
  <Title color="activeBlue">
    <Text>Content</Text>
  </Title>
);

export const ToggleButtonsExample = () => (
  <ToggleButtons isSelected={[]}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ToggleButtons>
);

export const ToggleButtonsThemeExample = () => (
  <ToggleButtonsTheme data={{}}>
    <Text>Content</Text>
  </ToggleButtonsTheme>
);

export const TooltipExample = () => (
  <Tooltip message="example">
    <Text>Content</Text>
  </Tooltip>
);

export const TooltipThemeExample = () => (
  <TooltipTheme data={{}}>
    <Text>Content</Text>
  </TooltipTheme>
);

export const TooltipVisibilityExample = () => (
  <TooltipVisibility visible={true}>
    <Text>Content</Text>
  </TooltipVisibility>
);

export const TransformExample = () => (
  <Transform
    transform={new Matrix4(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)}
  >
    <Text>Content</Text>
  </Transform>
);

export const TreeSliverExample = () => <TreeSliver tree={[]} />;

export const TweenAnimationBuilderExample = () => {
  const tween = new Tween();

  return (
    <TweenAnimationBuilder
      tween={tween}
      duration="defaultAnimationDuration"
      builder={() => <Text>Content</Text>}
    >
      <Text>Content</Text>
    </TweenAnimationBuilder>
  );
};

export const TwoDimensionalScrollableExample = () => (
  <TwoDimensionalScrollable
    horizontalDetails={new ScrollableDetails({ direction: 'up' })}
    verticalDetails={new ScrollableDetails({ direction: 'up' })}
    viewportBuilder={() => <Text>Content</Text>}
  />
);

export const UiKitViewExample = () => <UiKitView viewType="example" />;

export const UnconstrainedBoxExample = () => (
  <UnconstrainedBox>
    <Text>Content</Text>
  </UnconstrainedBox>
);

export const UnmanagedRestorationScopeExample = () => (
  <UnmanagedRestorationScope>
    <Text>Content</Text>
  </UnmanagedRestorationScope>
);

export const UserAccountsDrawerHeaderExample = () => (
  <UserAccountsDrawerHeader
    accountName={<Text>Content</Text>}
    accountEmail={<Text>Content</Text>}
  />
);

export const VerticalDividerExample = () => <VerticalDivider />;

export const ViewAnchorExample = () => (
  <ViewAnchor>
    <Text>Content</Text>
  </ViewAnchor>
);

export const ViewCollectionExample = () => <ViewCollection views={[]} />;

export const ViewportExample = () => (
  <Viewport
    offset={
      new ScrollPositionWithSingleContext({
        physics: {},
        context: new ScrollableState(),
      })
    }
  />
);

export const VisibilityExample = () => (
  <Visibility>
    <Text>Content</Text>
  </Visibility>
);

export const WidgetToRenderBoxAdapterExample = () => (
  <WidgetToRenderBoxAdapter renderBox={new RenderAbsorbPointer()} />
);

export const WidgetsAppExample = () => (
  <WidgetsApp color="activeBlue" builder={() => <Text>Content</Text>} />
);

export const WrapExample = () => (
  <Wrap>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Wrap>
);

export const YearPickerExample = () => (
  <YearPicker
    firstDate="2026-01-31"
    lastDate="2026-01-31"
    selectedDate="2026-01-31"
    onChanged={() => {}}
  />
);
