// GENERATED by `bun run docs` from the synthesized API-reference examples
// — do not edit. Checked by `tsc`: every complete example must typecheck
// against the published package surface.
import {
  AboutDialog,
  AboutListTile,
  AbsorbPointer,
  ActionChip,
  ActionIconTheme,
  AlertDialog,
  Align,
  AndroidView,
  AnimatedAlign,
  AnimatedContainer,
  AnimatedCrossFade,
  AnimatedDefaultTextStyle,
  AnimatedFractionallySizedBox,
  AnimatedOpacity,
  AnimatedPadding,
  AnimatedPhysicalModel,
  AnimatedPositioned,
  AnimatedPositionedDirectional,
  AnimatedRotation,
  AnimatedScale,
  AnimatedSize,
  AnimatedSlide,
  AnimatedSwitcher,
  AppBar,
  AppBarTheme,
  AppKitView,
  AspectRatio,
  AutofillGroup,
  AutomaticKeepAlive,
  BackButton,
  BackButtonIcon,
  BackdropFilter,
  BackdropGroup,
  Badge,
  BadgeTheme,
  Banner,
  Baseline,
  BlockSemantics,
  BottomAppBar,
  BottomAppBarTheme,
  BottomNavigationBar,
  BottomNavigationBarTheme,
  ButtonBar,
  ButtonBarTheme,
  ButtonTheme,
  Card,
  CardTheme,
  CarouselView,
  CarouselViewTheme,
  Center,
  Checkbox,
  CheckboxListTile,
  CheckboxMenuButton,
  CheckboxTheme,
  CheckedModeBanner,
  CheckedPopupMenuItem,
  Chip,
  ChipTheme,
  ChoiceChip,
  CircleAvatar,
  CircularProgressIndicator,
  ClipOval,
  ClipPath,
  ClipRRect,
  ClipRSuperellipse,
  ClipRect,
  CloseButton,
  CloseButtonIcon,
  ColoredBox,
  Column,
  ConstrainedBox,
  Container,
  CupertinoActionSheet,
  CupertinoActionSheetAction,
  CupertinoActivityIndicator,
  CupertinoAlertDialog,
  CupertinoApp,
  CupertinoButton,
  CupertinoCheckbox,
  CupertinoContextMenu,
  CupertinoContextMenuAction,
  CupertinoDatePicker,
  CupertinoDesktopTextSelectionToolbar,
  CupertinoDesktopTextSelectionToolbarButton,
  CupertinoDialogAction,
  CupertinoExpansionTile,
  CupertinoFormRow,
  CupertinoFormSection,
  CupertinoLinearActivityIndicator,
  CupertinoListSection,
  CupertinoListTile,
  CupertinoListTileChevron,
  CupertinoMagnifier,
  CupertinoMenuAnchor,
  CupertinoMenuDivider,
  CupertinoMenuItem,
  CupertinoNavigationBar,
  CupertinoNavigationBarBackButton,
  CupertinoPageScaffold,
  CupertinoPageScaffoldBackgroundColor,
  CupertinoPicker,
  CupertinoPickerDefaultSelectionOverlay,
  CupertinoPopupSurface,
  CupertinoScrollbar,
  CupertinoSearchTextField,
  CupertinoSlider,
  CupertinoSliverNavigationBar,
  CupertinoSliverRefreshControl,
  CupertinoSwitch,
  CupertinoTabBar,
  CupertinoTabView,
  CupertinoTextField,
  CupertinoTextFormFieldRow,
  CupertinoTextSelectionToolbar,
  CupertinoTextSelectionToolbarButton,
  CupertinoTheme,
  CupertinoTimerPicker,
  CupertinoUserInterfaceLevel,
  CustomPaint,
  CustomScrollView,
  DataTable,
  DataTableTheme,
  DatePickerTheme,
  DefaultSelectionStyle,
  DefaultTabController,
  DefaultTextEditingShortcuts,
  DefaultTextHeightBehavior,
  DefaultTextStyle,
  DesktopTextSelectionToolbar,
  DesktopTextSelectionToolbarButton,
  Dialog,
  DialogTheme,
  Directionality,
  DisableWidgetInspectorScope,
  DisplayFeatureSubScreen,
  Divider,
  DividerTheme,
  DragBoundary,
  Draggable,
  DraggableScrollableActuator,
  Drawer,
  DrawerButton,
  DrawerButtonIcon,
  DrawerController,
  DrawerHeader,
  DrawerTheme,
  DropdownButton,
  DropdownButtonFormField,
  DropdownButtonHideUnderline,
  DropdownMenu,
  DropdownMenuFormField,
  DropdownMenuItem,
  DropdownMenuTheme,
  ElevatedButton,
  ElevatedButtonTheme,
  EnableWidgetInspectorScope,
  EndDrawerButton,
  EndDrawerButtonIcon,
  ExcludeFocus,
  ExcludeFocusTraversal,
  ExcludeSemantics,
  ExpandIcon,
  Expanded,
  ExpansionPanelList,
  ExpansionTile,
  ExpansionTileTheme,
  FilledButton,
  FilledButtonTheme,
  FilterChip,
  FittedBox,
  Flex,
  Flexible,
  FlexibleSpaceBar,
  FlexibleSpaceBarSettings,
  FloatingActionButton,
  FloatingActionButtonTheme,
  FlutterLogo,
  Focus,
  FocusScope,
  FocusTraversalGroup,
  FocusableActionDetector,
  Form,
  FractionalTranslation,
  FractionallySizedBox,
  GestureDetector,
  GlowingOverscrollIndicator,
  GridPaper,
  GridTile,
  GridTileBar,
  HeroMode,
  HtmlElementView,
  Icon,
  IconButton,
  IconButtonTheme,
  IconTheme,
  IgnoreBaseline,
  IgnorePointer,
  IndexedSemantics,
  IndexedStack,
  Ink,
  InkResponse,
  InkWell,
  InputChip,
  InputDecorationTheme,
  InputDecorator,
  InteractiveViewer,
  IntrinsicHeight,
  IntrinsicWidth,
  KeepAlive,
  KeyedSubtree,
  LicensePage,
  LimitedBox,
  LinearProgressIndicator,
  ListBody,
  ListTile,
  ListTileTheme,
  ListView,
  ListWheelScrollView,
  Listener,
  LongPressDraggable,
  LookupBoundary,
  Magnifier,
  Material,
  MaterialApp,
  MaterialBanner,
  MaterialBannerTheme,
  MaterialButton,
  MediaQuery,
  MenuAcceleratorCallbackBinding,
  MenuAcceleratorLabel,
  MenuAnchor,
  MenuBar,
  MenuBarTheme,
  MenuButtonTheme,
  MenuItemButton,
  MenuTheme,
  MergeSemantics,
  MergeableMaterial,
  MetaData,
  ModalBarrier,
  MouseRegion,
  NavigationBar,
  NavigationBarTheme,
  NavigationDestination,
  NavigationDrawer,
  NavigationDrawerDestination,
  NavigationDrawerTheme,
  NavigationRail,
  NavigationRailTheme,
  NavigationToolbar,
  Navigator,
  NavigatorPopHandler,
  NotificationListener,
  Offstage,
  Opacity,
  OutlinedButton,
  OutlinedButtonTheme,
  OverflowBar,
  OverflowBox,
  Overlay,
  Padding,
  PageView,
  PerformanceOverlay,
  PhysicalModel,
  PinnedHeaderSliver,
  Placeholder,
  PlatformMenuBar,
  PlatformSelectableRegionContextMenu,
  PopScope,
  PopupMenuDivider,
  PopupMenuItem,
  PopupMenuTheme,
  Positioned,
  PositionedDirectional,
  PreferredSize,
  ProgressIndicatorTheme,
  RadioGroup,
  RadioTheme,
  RawChip,
  RawGestureDetector,
  RawImage,
  RawMagnifier,
  RawMaterialButton,
  RawScrollbar,
  RefreshProgressIndicator,
  ReorderableDelayedDragStartListener,
  ReorderableDragStartListener,
  ReorderableListView,
  RepaintBoundary,
  RestorationScope,
  RootRestorationScope,
  RootWidget,
  RotatedBox,
  Row,
  SafeArea,
  Scaffold,
  ScaffoldMessenger,
  ScrollNotificationObserver,
  Scrollbar,
  ScrollbarTheme,
  SearchBar,
  SearchBarTheme,
  SearchViewTheme,
  SegmentedButtonTheme,
  SelectableText,
  SelectionArea,
  Semantics,
  SemanticsDebugger,
  SensitiveContent,
  SharedAppData,
  ShortcutRegistrar,
  SimpleDialog,
  SimpleDialogOption,
  SingleChildScrollView,
  SizeChangedLayoutNotifier,
  SizedBox,
  SizedOverflowBox,
  Slider,
  SliderTheme,
  SliverAnimatedOpacity,
  SliverAppBar,
  SliverConstrainedCrossAxis,
  SliverCrossAxisExpanded,
  SliverCrossAxisGroup,
  SliverEnsureSemantics,
  SliverFillRemaining,
  SliverFloatingHeader,
  SliverIgnorePointer,
  SliverMainAxisGroup,
  SliverOffstage,
  SliverOpacity,
  SliverPadding,
  SliverResizingHeader,
  SliverSafeArea,
  SliverSemantics,
  SliverToBoxAdapter,
  SliverVisibility,
  SnackBar,
  SnackBarAction,
  SnackBarTheme,
  Spacer,
  SpellCheckSuggestionsToolbar,
  Stack,
  Stepper,
  StretchEffect,
  StretchingOverscrollIndicator,
  SubmenuButton,
  Switch,
  SwitchListTile,
  SwitchTheme,
  Tab,
  TabBar,
  TabBarTheme,
  TabBarView,
  TabPageSelector,
  TabPageSelectorIndicator,
  Table,
  TableCell,
  TableRowInkWell,
  TapRegion,
  TapRegionSurface,
  Text,
  TextButton,
  TextButtonTheme,
  TextField,
  TextFieldTapRegion,
  TextFormField,
  TextSelectionGestureDetector,
  TextSelectionTheme,
  TextSelectionToolbar,
  TextSelectionToolbarTextButton,
  Texture,
  TickerMode,
  TimePickerTheme,
  Title,
  ToggleButtons,
  ToggleButtonsTheme,
  Tooltip,
  TooltipTheme,
  TooltipVisibility,
  TreeSliver,
  UiKitView,
  UnconstrainedBox,
  UnmanagedRestorationScope,
  UserAccountsDrawerHeader,
  VerticalDivider,
  ViewAnchor,
  ViewCollection,
  Visibility,
  WidgetsApp,
  Wrap,
} from 'flutter-tsx';

export const examples = [
  <AboutDialog>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </AboutDialog>,
  <AboutListTile>
    <Text>Content</Text>
  </AboutListTile>,
  <AbsorbPointer>
    <Text>Content</Text>
  </AbsorbPointer>,
  <ActionChip label={<Text>Content</Text>} />,
  <ActionIconTheme data={{}}>
    <Text>Content</Text>
  </ActionIconTheme>,
  <AlertDialog />,
  <Align>
    <Text>Content</Text>
  </Align>,
  <AndroidView viewType="example" />,
  <AnimatedAlign alignment="bottomCenter" duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedAlign>,
  <AnimatedContainer duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedContainer>,
  <AnimatedCrossFade
    firstChild={<Text>Content</Text>}
    secondChild={<Text>Content</Text>}
    crossFadeState="showFirst"
    duration="defaultAnimationDuration"
  />,
  <AnimatedDefaultTextStyle
    style="cupertinoMisspelledTextStyle"
    duration="defaultAnimationDuration"
  >
    <Text>Content</Text>
  </AnimatedDefaultTextStyle>,
  <AnimatedFractionallySizedBox duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedFractionallySizedBox>,
  <AnimatedOpacity opacity={1} duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedOpacity>,
  <AnimatedPadding padding="infinity" duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedPadding>,
  <AnimatedPhysicalModel
    color="activeBlue"
    shadowColor="activeBlue"
    duration="defaultAnimationDuration"
  >
    <Text>Content</Text>
  </AnimatedPhysicalModel>,
  <AnimatedPositioned duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedPositioned>,
  <AnimatedPositionedDirectional duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedPositionedDirectional>,
  <AnimatedRotation turns={1} duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedRotation>,
  <AnimatedScale scale={1} duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedScale>,
  <AnimatedSize duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedSize>,
  <AnimatedSlide offset="infinite" duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedSlide>,
  <AnimatedSwitcher duration="defaultAnimationDuration">
    <Text>Content</Text>
  </AnimatedSwitcher>,
  <AppBar />,
  <AppBarTheme>
    <Text>Content</Text>
  </AppBarTheme>,
  <AppKitView viewType="example" />,
  <AspectRatio aspectRatio={1}>
    <Text>Content</Text>
  </AspectRatio>,
  <AutofillGroup>
    <Text>Content</Text>
  </AutofillGroup>,
  <AutomaticKeepAlive>
    <Text>Content</Text>
  </AutomaticKeepAlive>,
  <BackButton />,
  <BackButtonIcon />,
  <BackdropFilter>
    <Text>Content</Text>
  </BackdropFilter>,
  <BackdropGroup>
    <Text>Content</Text>
  </BackdropGroup>,
  <Badge>
    <Text>Content</Text>
  </Badge>,
  <BadgeTheme data={{}}>
    <Text>Content</Text>
  </BadgeTheme>,
  <Banner message="example" location="topStart">
    <Text>Content</Text>
  </Banner>,
  <Baseline baseline={1} baselineType="alphabetic">
    <Text>Content</Text>
  </Baseline>,
  <BlockSemantics>
    <Text>Content</Text>
  </BlockSemantics>,
  <BottomAppBar>
    <Text>Content</Text>
  </BottomAppBar>,
  <BottomAppBarTheme>
    <Text>Content</Text>
  </BottomAppBarTheme>,
  <BottomNavigationBar items={[]} />,
  <BottomNavigationBarTheme data={{}}>
    <Text>Content</Text>
  </BottomNavigationBarTheme>,
  <ButtonBar>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ButtonBar>,
  <ButtonBarTheme data={{}}>
    <Text>Content</Text>
  </ButtonBarTheme>,
  <ButtonTheme>
    <Text>Content</Text>
  </ButtonTheme>,
  <Card>
    <Text>Content</Text>
  </Card>,
  <CardTheme>
    <Text>Content</Text>
  </CardTheme>,
  <CarouselView itemExtent={1}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CarouselView>,
  <CarouselViewTheme data={{}}>
    <Text>Content</Text>
  </CarouselViewTheme>,
  <Center>
    <Text>Content</Text>
  </Center>,
  <Checkbox value={true} onChanged={() => {}} />,
  <CheckboxListTile value={true} onChanged={() => {}} />,
  <CheckboxMenuButton value={true} onChanged={() => {}}>
    <Text>Content</Text>
  </CheckboxMenuButton>,
  <CheckboxTheme data={{}}>
    <Text>Content</Text>
  </CheckboxTheme>,
  <CheckedModeBanner>
    <Text>Content</Text>
  </CheckedModeBanner>,
  <CheckedPopupMenuItem>
    <Text>Content</Text>
  </CheckedPopupMenuItem>,
  <Chip label={<Text>Content</Text>} />,
  <ChipTheme data={{}}>
    <Text>Content</Text>
  </ChipTheme>,
  <ChoiceChip label={<Text>Content</Text>} selected={true} />,
  <CircleAvatar>
    <Text>Content</Text>
  </CircleAvatar>,
  <CircularProgressIndicator />,
  <ClipOval>
    <Text>Content</Text>
  </ClipOval>,
  <ClipPath>
    <Text>Content</Text>
  </ClipPath>,
  <ClipRRect>
    <Text>Content</Text>
  </ClipRRect>,
  <ClipRSuperellipse>
    <Text>Content</Text>
  </ClipRSuperellipse>,
  <ClipRect>
    <Text>Content</Text>
  </ClipRect>,
  <CloseButton />,
  <CloseButtonIcon />,
  <ColoredBox color="activeBlue">
    <Text>Content</Text>
  </ColoredBox>,
  <Column>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Column>,
  <ConstrainedBox constraints={{}}>
    <Text>Content</Text>
  </ConstrainedBox>,
  <Container>
    <Text>Content</Text>
  </Container>,
  <CupertinoActionSheet />,
  <CupertinoActionSheetAction onClick={() => {}}>
    <Text>Content</Text>
  </CupertinoActionSheetAction>,
  <CupertinoActivityIndicator />,
  <CupertinoAlertDialog />,
  <CupertinoApp />,
  <CupertinoButton onClick={() => {}}>
    <Text>Content</Text>
  </CupertinoButton>,
  <CupertinoCheckbox value={true} onChanged={() => {}} />,
  <CupertinoContextMenu actions={[]}>
    <Text>Content</Text>
  </CupertinoContextMenu>,
  <CupertinoContextMenuAction>
    <Text>Content</Text>
  </CupertinoContextMenuAction>,
  <CupertinoDatePicker onDateTimeChanged={() => {}} />,
  <CupertinoDesktopTextSelectionToolbar anchor="infinite">
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoDesktopTextSelectionToolbar>,
  <CupertinoDesktopTextSelectionToolbarButton onClick={() => {}}>
    <Text>Content</Text>
  </CupertinoDesktopTextSelectionToolbarButton>,
  <CupertinoDialogAction>
    <Text>Content</Text>
  </CupertinoDialogAction>,
  <CupertinoExpansionTile title={<Text>Content</Text>}>
    <Text>Content</Text>
  </CupertinoExpansionTile>,
  <CupertinoFormRow>
    <Text>Content</Text>
  </CupertinoFormRow>,
  <CupertinoFormSection>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoFormSection>,
  <CupertinoLinearActivityIndicator progress={1} />,
  <CupertinoListSection>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoListSection>,
  <CupertinoListTile title={<Text>Content</Text>} />,
  <CupertinoListTileChevron />,
  <CupertinoMagnifier />,
  <CupertinoMenuAnchor menuChildren={[]}>
    <Text>Content</Text>
  </CupertinoMenuAnchor>,
  <CupertinoMenuDivider />,
  <CupertinoMenuItem>
    <Text>Content</Text>
  </CupertinoMenuItem>,
  <CupertinoNavigationBar />,
  <CupertinoNavigationBarBackButton />,
  <CupertinoPageScaffold>
    <Text>Content</Text>
  </CupertinoPageScaffold>,
  <CupertinoPageScaffoldBackgroundColor color="activeBlue">
    <Text>Content</Text>
  </CupertinoPageScaffoldBackgroundColor>,
  <CupertinoPicker itemExtent={1} onSelectedItemChanged={() => {}}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoPicker>,
  <CupertinoPickerDefaultSelectionOverlay />,
  <CupertinoPopupSurface>
    <Text>Content</Text>
  </CupertinoPopupSurface>,
  <CupertinoScrollbar>
    <Text>Content</Text>
  </CupertinoScrollbar>,
  <CupertinoSearchTextField />,
  <CupertinoSlider value={1} onChanged={() => {}} />,
  <CupertinoSliverNavigationBar />,
  <CupertinoSliverRefreshControl />,
  <CupertinoSwitch value={true} onChanged={() => {}} />,
  <CupertinoTabBar items={[]} />,
  <CupertinoTabView />,
  <CupertinoTextField />,
  <CupertinoTextFormFieldRow />,
  <CupertinoTextSelectionToolbar anchorAbove="infinite" anchorBelow="infinite">
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoTextSelectionToolbar>,
  <CupertinoTextSelectionToolbarButton>
    <Text>Content</Text>
  </CupertinoTextSelectionToolbarButton>,
  <CupertinoTheme data={{}}>
    <Text>Content</Text>
  </CupertinoTheme>,
  <CupertinoTimerPicker onTimerDurationChanged={() => {}} />,
  <CupertinoUserInterfaceLevel data="base">
    <Text>Content</Text>
  </CupertinoUserInterfaceLevel>,
  <CustomPaint>
    <Text>Content</Text>
  </CustomPaint>,
  <CustomScrollView />,
  <DataTable columns={[]} rows={[]} />,
  <DataTableTheme data={{}}>
    <Text>Content</Text>
  </DataTableTheme>,
  <DatePickerTheme data={{}}>
    <Text>Content</Text>
  </DatePickerTheme>,
  <DefaultSelectionStyle>
    <Text>Content</Text>
  </DefaultSelectionStyle>,
  <DefaultTabController length={8}>
    <Text>Content</Text>
  </DefaultTabController>,
  <DefaultTextEditingShortcuts>
    <Text>Content</Text>
  </DefaultTextEditingShortcuts>,
  <DefaultTextHeightBehavior textHeightBehavior={{}}>
    <Text>Content</Text>
  </DefaultTextHeightBehavior>,
  <DefaultTextStyle style="cupertinoMisspelledTextStyle">
    <Text>Content</Text>
  </DefaultTextStyle>,
  <DesktopTextSelectionToolbar anchor="infinite">
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </DesktopTextSelectionToolbar>,
  <DesktopTextSelectionToolbarButton onClick={() => {}}>
    <Text>Content</Text>
  </DesktopTextSelectionToolbarButton>,
  <Dialog>
    <Text>Content</Text>
  </Dialog>,
  <DialogTheme>
    <Text>Content</Text>
  </DialogTheme>,
  <Directionality textDirection="rtl">
    <Text>Content</Text>
  </Directionality>,
  <DisableWidgetInspectorScope>
    <Text>Content</Text>
  </DisableWidgetInspectorScope>,
  <DisplayFeatureSubScreen>
    <Text>Content</Text>
  </DisplayFeatureSubScreen>,
  <Divider />,
  <DividerTheme data={{}}>
    <Text>Content</Text>
  </DividerTheme>,
  <DragBoundary>
    <Text>Content</Text>
  </DragBoundary>,
  <Draggable feedback={<Text>Content</Text>}>
    <Text>Content</Text>
  </Draggable>,
  <DraggableScrollableActuator>
    <Text>Content</Text>
  </DraggableScrollableActuator>,
  <Drawer>
    <Text>Content</Text>
  </Drawer>,
  <DrawerButton />,
  <DrawerButtonIcon />,
  <DrawerController alignment="start">
    <Text>Content</Text>
  </DrawerController>,
  <DrawerHeader>
    <Text>Content</Text>
  </DrawerHeader>,
  <DrawerTheme data={{}}>
    <Text>Content</Text>
  </DrawerTheme>,
  <DropdownButton items={[]} onChanged={() => {}} />,
  <DropdownButtonFormField items={[]} onChanged={() => {}} />,
  <DropdownButtonHideUnderline>
    <Text>Content</Text>
  </DropdownButtonHideUnderline>,
  <DropdownMenu dropdownMenuEntries={[]} />,
  <DropdownMenuFormField dropdownMenuEntries={[]} />,
  <DropdownMenuItem>
    <Text>Content</Text>
  </DropdownMenuItem>,
  <DropdownMenuTheme data={{}}>
    <Text>Content</Text>
  </DropdownMenuTheme>,
  <ElevatedButton onClick={() => {}}>
    <Text>Content</Text>
  </ElevatedButton>,
  <ElevatedButtonTheme data={{}}>
    <Text>Content</Text>
  </ElevatedButtonTheme>,
  <EnableWidgetInspectorScope>
    <Text>Content</Text>
  </EnableWidgetInspectorScope>,
  <EndDrawerButton />,
  <EndDrawerButtonIcon />,
  <ExcludeFocus>
    <Text>Content</Text>
  </ExcludeFocus>,
  <ExcludeFocusTraversal>
    <Text>Content</Text>
  </ExcludeFocusTraversal>,
  <ExcludeSemantics>
    <Text>Content</Text>
  </ExcludeSemantics>,
  <ExpandIcon onClick={() => {}} />,
  <Expanded>
    <Text>Content</Text>
  </Expanded>,
  <ExpansionPanelList />,
  <ExpansionTile title={<Text>Content</Text>}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ExpansionTile>,
  <ExpansionTileTheme data={{}}>
    <Text>Content</Text>
  </ExpansionTileTheme>,
  <FilledButton onClick={() => {}}>
    <Text>Content</Text>
  </FilledButton>,
  <FilledButtonTheme data={{}}>
    <Text>Content</Text>
  </FilledButtonTheme>,
  <FilterChip label={<Text>Content</Text>} onSelected={() => {}} />,
  <FittedBox>
    <Text>Content</Text>
  </FittedBox>,
  <Flex direction="horizontal">
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Flex>,
  <Flexible>
    <Text>Content</Text>
  </Flexible>,
  <FlexibleSpaceBar />,
  <FlexibleSpaceBarSettings
    toolbarOpacity={1}
    minExtent={1}
    maxExtent={1}
    currentExtent={1}
  >
    <Text>Content</Text>
  </FlexibleSpaceBarSettings>,
  <FloatingActionButton onClick={() => {}}>
    <Text>Content</Text>
  </FloatingActionButton>,
  <FloatingActionButtonTheme data={{}}>
    <Text>Content</Text>
  </FloatingActionButtonTheme>,
  <FlutterLogo />,
  <Focus>
    <Text>Content</Text>
  </Focus>,
  <FocusScope>
    <Text>Content</Text>
  </FocusScope>,
  <FocusTraversalGroup>
    <Text>Content</Text>
  </FocusTraversalGroup>,
  <FocusableActionDetector>
    <Text>Content</Text>
  </FocusableActionDetector>,
  <Form>
    <Text>Content</Text>
  </Form>,
  <FractionalTranslation translation="infinite">
    <Text>Content</Text>
  </FractionalTranslation>,
  <FractionallySizedBox>
    <Text>Content</Text>
  </FractionallySizedBox>,
  <GestureDetector>
    <Text>Content</Text>
  </GestureDetector>,
  <GlowingOverscrollIndicator axisDirection="up" color="activeBlue">
    <Text>Content</Text>
  </GlowingOverscrollIndicator>,
  <GridPaper>
    <Text>Content</Text>
  </GridPaper>,
  <GridTile>
    <Text>Content</Text>
  </GridTile>,
  <GridTileBar />,
  <HeroMode>
    <Text>Content</Text>
  </HeroMode>,
  <HtmlElementView viewType="example" />,
  <Icon icon="abc" />,
  <IconButton onClick={() => {}} icon={<Text>Content</Text>} />,
  <IconButtonTheme data={{}}>
    <Text>Content</Text>
  </IconButtonTheme>,
  <IconTheme data={{}}>
    <Text>Content</Text>
  </IconTheme>,
  <IgnoreBaseline>
    <Text>Content</Text>
  </IgnoreBaseline>,
  <IgnorePointer>
    <Text>Content</Text>
  </IgnorePointer>,
  <IndexedSemantics index={8}>
    <Text>Content</Text>
  </IndexedSemantics>,
  <IndexedStack>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </IndexedStack>,
  <Ink>
    <Text>Content</Text>
  </Ink>,
  <InkResponse>
    <Text>Content</Text>
  </InkResponse>,
  <InkWell>
    <Text>Content</Text>
  </InkWell>,
  <InputChip label={<Text>Content</Text>} />,
  <InputDecorationTheme>
    <Text>Content</Text>
  </InputDecorationTheme>,
  <InputDecorator decoration={{}}>
    <Text>Content</Text>
  </InputDecorator>,
  <InteractiveViewer>
    <Text>Content</Text>
  </InteractiveViewer>,
  <IntrinsicHeight>
    <Text>Content</Text>
  </IntrinsicHeight>,
  <IntrinsicWidth>
    <Text>Content</Text>
  </IntrinsicWidth>,
  <KeepAlive keepAlive={true}>
    <Text>Content</Text>
  </KeepAlive>,
  <KeyedSubtree>
    <Text>Content</Text>
  </KeyedSubtree>,
  <LicensePage />,
  <LimitedBox>
    <Text>Content</Text>
  </LimitedBox>,
  <LinearProgressIndicator />,
  <ListBody>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ListBody>,
  <ListTile />,
  <ListTileTheme>
    <Text>Content</Text>
  </ListTileTheme>,
  <ListView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ListView>,
  <ListWheelScrollView itemExtent={1}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ListWheelScrollView>,
  <Listener>
    <Text>Content</Text>
  </Listener>,
  <LongPressDraggable feedback={<Text>Content</Text>}>
    <Text>Content</Text>
  </LongPressDraggable>,
  <LookupBoundary>
    <Text>Content</Text>
  </LookupBoundary>,
  <Magnifier />,
  <Material>
    <Text>Content</Text>
  </Material>,
  <MaterialApp />,
  <MaterialBanner content={<Text>Content</Text>} actions={[]} />,
  <MaterialBannerTheme>
    <Text>Content</Text>
  </MaterialBannerTheme>,
  <MaterialButton onClick={() => {}}>
    <Text>Content</Text>
  </MaterialButton>,
  <MediaQuery data={{}}>
    <Text>Content</Text>
  </MediaQuery>,
  <MenuAcceleratorCallbackBinding>
    <Text>Content</Text>
  </MenuAcceleratorCallbackBinding>,
  <MenuAcceleratorLabel>Hello world</MenuAcceleratorLabel>,
  <MenuAnchor menuChildren={[]}>
    <Text>Content</Text>
  </MenuAnchor>,
  <MenuBar>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </MenuBar>,
  <MenuBarTheme data={{}}>
    <Text>Content</Text>
  </MenuBarTheme>,
  <MenuButtonTheme data={{}}>
    <Text>Content</Text>
  </MenuButtonTheme>,
  <MenuItemButton>
    <Text>Content</Text>
  </MenuItemButton>,
  <MenuTheme data={{}}>
    <Text>Content</Text>
  </MenuTheme>,
  <MergeSemantics>
    <Text>Content</Text>
  </MergeSemantics>,
  <MergeableMaterial />,
  <MetaData>
    <Text>Content</Text>
  </MetaData>,
  <ModalBarrier />,
  <MouseRegion>
    <Text>Content</Text>
  </MouseRegion>,
  <NavigationBar destinations={[]} />,
  <NavigationBarTheme data={{}}>
    <Text>Content</Text>
  </NavigationBarTheme>,
  <NavigationDestination icon={<Text>Content</Text>} label="example" />,
  <NavigationDrawer>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </NavigationDrawer>,
  <NavigationDrawerDestination
    icon={<Text>Content</Text>}
    label={<Text>Content</Text>}
  />,
  <NavigationDrawerTheme data={{}}>
    <Text>Content</Text>
  </NavigationDrawerTheme>,
  <NavigationRail destinations={[]} selectedIndex={8} />,
  <NavigationRailTheme data={{}}>
    <Text>Content</Text>
  </NavigationRailTheme>,
  <NavigationToolbar />,
  <Navigator />,
  <NavigatorPopHandler>
    <Text>Content</Text>
  </NavigatorPopHandler>,
  <NotificationListener>
    <Text>Content</Text>
  </NotificationListener>,
  <Offstage>
    <Text>Content</Text>
  </Offstage>,
  <Opacity opacity={1}>
    <Text>Content</Text>
  </Opacity>,
  <OutlinedButton onClick={() => {}}>
    <Text>Content</Text>
  </OutlinedButton>,
  <OutlinedButtonTheme data={{}}>
    <Text>Content</Text>
  </OutlinedButtonTheme>,
  <OverflowBar>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </OverflowBar>,
  <OverflowBox>
    <Text>Content</Text>
  </OverflowBox>,
  <Overlay />,
  <Padding padding="infinity">
    <Text>Content</Text>
  </Padding>,
  <PageView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </PageView>,
  <PerformanceOverlay />,
  <PhysicalModel color="activeBlue">
    <Text>Content</Text>
  </PhysicalModel>,
  <PinnedHeaderSliver>
    <Text>Content</Text>
  </PinnedHeaderSliver>,
  <Placeholder>
    <Text>Content</Text>
  </Placeholder>,
  <PlatformMenuBar menus={[]}>
    <Text>Content</Text>
  </PlatformMenuBar>,
  <PlatformSelectableRegionContextMenu>
    <Text>Content</Text>
  </PlatformSelectableRegionContextMenu>,
  <PopScope>
    <Text>Content</Text>
  </PopScope>,
  <PopupMenuDivider />,
  <PopupMenuItem>
    <Text>Content</Text>
  </PopupMenuItem>,
  <PopupMenuTheme data={{}}>
    <Text>Content</Text>
  </PopupMenuTheme>,
  <Positioned>
    <Text>Content</Text>
  </Positioned>,
  <PositionedDirectional>
    <Text>Content</Text>
  </PositionedDirectional>,
  <PreferredSize preferredSize="infinite">
    <Text>Content</Text>
  </PreferredSize>,
  <ProgressIndicatorTheme data={{}}>
    <Text>Content</Text>
  </ProgressIndicatorTheme>,
  <RadioGroup onChanged={() => {}}>
    <Text>Content</Text>
  </RadioGroup>,
  <RadioTheme data={{}}>
    <Text>Content</Text>
  </RadioTheme>,
  <RawChip label={<Text>Content</Text>} />,
  <RawGestureDetector>
    <Text>Content</Text>
  </RawGestureDetector>,
  <RawImage />,
  <RawMagnifier size="infinite">
    <Text>Content</Text>
  </RawMagnifier>,
  <RawMaterialButton onClick={() => {}}>
    <Text>Content</Text>
  </RawMaterialButton>,
  <RawScrollbar>
    <Text>Content</Text>
  </RawScrollbar>,
  <RefreshProgressIndicator />,
  <ReorderableDelayedDragStartListener index={8}>
    <Text>Content</Text>
  </ReorderableDelayedDragStartListener>,
  <ReorderableDragStartListener index={8}>
    <Text>Content</Text>
  </ReorderableDragStartListener>,
  <ReorderableListView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ReorderableListView>,
  <RepaintBoundary>
    <Text>Content</Text>
  </RepaintBoundary>,
  <RestorationScope restorationId="example">
    <Text>Content</Text>
  </RestorationScope>,
  <RootRestorationScope restorationId="example">
    <Text>Content</Text>
  </RootRestorationScope>,
  <RootWidget>
    <Text>Content</Text>
  </RootWidget>,
  <RotatedBox quarterTurns={8}>
    <Text>Content</Text>
  </RotatedBox>,
  <Row>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Row>,
  <SafeArea>
    <Text>Content</Text>
  </SafeArea>,
  <Scaffold />,
  <ScaffoldMessenger>
    <Text>Content</Text>
  </ScaffoldMessenger>,
  <ScrollNotificationObserver>
    <Text>Content</Text>
  </ScrollNotificationObserver>,
  <Scrollbar>
    <Text>Content</Text>
  </Scrollbar>,
  <ScrollbarTheme data={{}}>
    <Text>Content</Text>
  </ScrollbarTheme>,
  <SearchBar />,
  <SearchBarTheme data={{}}>
    <Text>Content</Text>
  </SearchBarTheme>,
  <SearchViewTheme data={{}}>
    <Text>Content</Text>
  </SearchViewTheme>,
  <SegmentedButtonTheme data={{}}>
    <Text>Content</Text>
  </SegmentedButtonTheme>,
  <SelectableText>Hello world</SelectableText>,
  <SelectionArea>
    <Text>Content</Text>
  </SelectionArea>,
  <Semantics>
    <Text>Content</Text>
  </Semantics>,
  <SemanticsDebugger>
    <Text>Content</Text>
  </SemanticsDebugger>,
  <SensitiveContent sensitivity="autoSensitive">
    <Text>Content</Text>
  </SensitiveContent>,
  <SharedAppData>
    <Text>Content</Text>
  </SharedAppData>,
  <ShortcutRegistrar>
    <Text>Content</Text>
  </ShortcutRegistrar>,
  <SimpleDialog>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </SimpleDialog>,
  <SimpleDialogOption>
    <Text>Content</Text>
  </SimpleDialogOption>,
  <SingleChildScrollView>
    <Text>Content</Text>
  </SingleChildScrollView>,
  <SizeChangedLayoutNotifier>
    <Text>Content</Text>
  </SizeChangedLayoutNotifier>,
  <SizedBox>
    <Text>Content</Text>
  </SizedBox>,
  <SizedOverflowBox size="infinite">
    <Text>Content</Text>
  </SizedOverflowBox>,
  <Slider value={1} onChanged={() => {}} />,
  <SliderTheme data={{}}>
    <Text>Content</Text>
  </SliderTheme>,
  <SliverAnimatedOpacity opacity={1} duration="defaultAnimationDuration" />,
  <SliverAppBar />,
  <SliverConstrainedCrossAxis maxExtent={1} sliver={<Text>Content</Text>} />,
  <SliverCrossAxisExpanded flex={8} sliver={<Text>Content</Text>} />,
  <SliverCrossAxisGroup slivers={[]} />,
  <SliverEnsureSemantics sliver={<Text>Content</Text>} />,
  <SliverFillRemaining>
    <Text>Content</Text>
  </SliverFillRemaining>,
  <SliverFloatingHeader>
    <Text>Content</Text>
  </SliverFloatingHeader>,
  <SliverIgnorePointer />,
  <SliverMainAxisGroup slivers={[]} />,
  <SliverOffstage />,
  <SliverOpacity opacity={1} />,
  <SliverPadding padding="infinity" />,
  <SliverResizingHeader>
    <Text>Content</Text>
  </SliverResizingHeader>,
  <SliverSafeArea sliver={<Text>Content</Text>} />,
  <SliverSemantics sliver={<Text>Content</Text>} />,
  <SliverToBoxAdapter>
    <Text>Content</Text>
  </SliverToBoxAdapter>,
  <SliverVisibility sliver={<Text>Content</Text>} />,
  <SnackBar content={<Text>Content</Text>} />,
  <SnackBarAction label="example" onClick={() => {}} />,
  <SnackBarTheme data={{}}>
    <Text>Content</Text>
  </SnackBarTheme>,
  <Spacer />,
  <SpellCheckSuggestionsToolbar anchor="infinite" buttonItems={[]} />,
  <Stack>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Stack>,
  <Stepper steps={[]} />,
  <StretchEffect axis="horizontal">
    <Text>Content</Text>
  </StretchEffect>,
  <StretchingOverscrollIndicator axisDirection="up">
    <Text>Content</Text>
  </StretchingOverscrollIndicator>,
  <SubmenuButton menuChildren={[]}>
    <Text>Content</Text>
  </SubmenuButton>,
  <Switch value={true} onChanged={() => {}} />,
  <SwitchListTile value={true} onChanged={() => {}} />,
  <SwitchTheme data={{}}>
    <Text>Content</Text>
  </SwitchTheme>,
  <Tab>
    <Text>Content</Text>
  </Tab>,
  <TabBar tabs={[]} />,
  <TabBarTheme>
    <Text>Content</Text>
  </TabBarTheme>,
  <TabBarView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </TabBarView>,
  <TabPageSelector />,
  <TabPageSelectorIndicator
    backgroundColor="activeBlue"
    borderColor="activeBlue"
    size={1}
  />,
  <Table />,
  <TableCell>
    <Text>Content</Text>
  </TableCell>,
  <TableRowInkWell>
    <Text>Content</Text>
  </TableRowInkWell>,
  <TapRegion>
    <Text>Content</Text>
  </TapRegion>,
  <TapRegionSurface>
    <Text>Content</Text>
  </TapRegionSurface>,
  <Text>Hello world</Text>,
  <TextButton onClick={() => {}}>
    <Text>Content</Text>
  </TextButton>,
  <TextButtonTheme data={{}}>
    <Text>Content</Text>
  </TextButtonTheme>,
  <TextField />,
  <TextFieldTapRegion>
    <Text>Content</Text>
  </TextFieldTapRegion>,
  <TextFormField />,
  <TextSelectionGestureDetector>
    <Text>Content</Text>
  </TextSelectionGestureDetector>,
  <TextSelectionTheme data={{}}>
    <Text>Content</Text>
  </TextSelectionTheme>,
  <TextSelectionToolbar anchorAbove="infinite" anchorBelow="infinite">
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </TextSelectionToolbar>,
  <TextSelectionToolbarTextButton padding="infinity">
    <Text>Content</Text>
  </TextSelectionToolbarTextButton>,
  <Texture textureId={8} />,
  <TickerMode enabled={true}>
    <Text>Content</Text>
  </TickerMode>,
  <TimePickerTheme data={{}}>
    <Text>Content</Text>
  </TimePickerTheme>,
  <Title color="activeBlue">
    <Text>Content</Text>
  </Title>,
  <ToggleButtons isSelected={[]}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ToggleButtons>,
  <ToggleButtonsTheme data={{}}>
    <Text>Content</Text>
  </ToggleButtonsTheme>,
  <Tooltip>
    <Text>Content</Text>
  </Tooltip>,
  <TooltipTheme data={{}}>
    <Text>Content</Text>
  </TooltipTheme>,
  <TooltipVisibility visible={true}>
    <Text>Content</Text>
  </TooltipVisibility>,
  <TreeSliver tree={[]} />,
  <UiKitView viewType="example" />,
  <UnconstrainedBox>
    <Text>Content</Text>
  </UnconstrainedBox>,
  <UnmanagedRestorationScope>
    <Text>Content</Text>
  </UnmanagedRestorationScope>,
  <UserAccountsDrawerHeader
    accountName={<Text>Content</Text>}
    accountEmail={<Text>Content</Text>}
  />,
  <VerticalDivider />,
  <ViewAnchor>
    <Text>Content</Text>
  </ViewAnchor>,
  <ViewCollection views={[]} />,
  <Visibility>
    <Text>Content</Text>
  </Visibility>,
  <WidgetsApp color="activeBlue" />,
  <Wrap>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Wrap>,
];
