// GENERATED by `bun run docs` from the synthesized API-reference examples
// — do not edit. Checked by `tsc`: every complete example must typecheck
// against the published package surface.
import {
  AboutDialog,
  AboutListTile,
  AbsorbPointer,
  ActionChip,
  AlertDialog,
  Align,
  AlignmentGeometry,
  AndroidView,
  AnimatedAlign,
  AnimatedContainer,
  AnimatedCrossFade,
  AnimatedDefaultTextStyle,
  AnimatedFractionallySizedBox,
  AnimatedOpacity,
  AnimatedPadding,
  AnimatedPhysicalModel,
  AnimatedPositioned,
  AnimatedPositionedDirectional,
  AnimatedRotation,
  AnimatedScale,
  AnimatedSize,
  AnimatedSlide,
  AnimatedSwitcher,
  AppBar,
  AppBarTheme,
  AppKitView,
  AspectRatio,
  AutofillGroup,
  AutomaticKeepAlive,
  BackButton,
  BackButtonIcon,
  BackdropFilter,
  BackdropGroup,
  Badge,
  Banner,
  Baseline,
  BlockSemantics,
  BottomAppBar,
  BottomAppBarTheme,
  BottomNavigationBar,
  ButtonBar,
  ButtonTheme,
  Card,
  CardTheme,
  CarouselView,
  Center,
  Checkbox,
  CheckboxListTile,
  CheckboxMenuButton,
  CheckedModeBanner,
  CheckedPopupMenuItem,
  Chip,
  ChoiceChip,
  CircleAvatar,
  CircularProgressIndicator,
  ClipOval,
  ClipPath,
  ClipRRect,
  ClipRSuperellipse,
  ClipRect,
  CloseButton,
  CloseButtonIcon,
  ColoredBox,
  Colors,
  Column,
  Container,
  CupertinoActionSheet,
  CupertinoActionSheetAction,
  CupertinoActivityIndicator,
  CupertinoAlertDialog,
  CupertinoApp,
  CupertinoButton,
  CupertinoCheckbox,
  CupertinoContextMenu,
  CupertinoContextMenuAction,
  CupertinoDatePicker,
  CupertinoDesktopTextSelectionToolbar,
  CupertinoDesktopTextSelectionToolbarButton,
  CupertinoDialogAction,
  CupertinoExpansionTile,
  CupertinoFormRow,
  CupertinoFormSection,
  CupertinoLinearActivityIndicator,
  CupertinoListSection,
  CupertinoListTile,
  CupertinoListTileChevron,
  CupertinoMagnifier,
  CupertinoMenuAnchor,
  CupertinoMenuDivider,
  CupertinoMenuItem,
  CupertinoNavigationBar,
  CupertinoNavigationBarBackButton,
  CupertinoPageScaffold,
  CupertinoPageScaffoldBackgroundColor,
  CupertinoPicker,
  CupertinoPickerDefaultSelectionOverlay,
  CupertinoPopupSurface,
  CupertinoScrollbar,
  CupertinoSearchTextField,
  CupertinoSlider,
  CupertinoSliverNavigationBar,
  CupertinoSliverRefreshControl,
  CupertinoSwitch,
  CupertinoTabBar,
  CupertinoTabView,
  CupertinoTextField,
  CupertinoTextFormFieldRow,
  CupertinoTextSelectionToolbar,
  CupertinoTextSelectionToolbarButton,
  CupertinoTimerPicker,
  CupertinoUserInterfaceLevel,
  CustomPaint,
  CustomScrollView,
  DataTable,
  DefaultSelectionStyle,
  DefaultTabController,
  DefaultTextEditingShortcuts,
  DefaultTextStyle,
  DesktopTextSelectionToolbar,
  DesktopTextSelectionToolbarButton,
  Dialog,
  DialogTheme,
  Directionality,
  DisableWidgetInspectorScope,
  Dismissible,
  DisplayFeatureSubScreen,
  Divider,
  DragBoundary,
  Draggable,
  DraggableScrollableActuator,
  Drawer,
  DrawerButton,
  DrawerButtonIcon,
  DrawerController,
  DrawerHeader,
  DropdownButton,
  DropdownButtonFormField,
  DropdownButtonHideUnderline,
  DropdownMenu,
  DropdownMenuFormField,
  DropdownMenuItem,
  EdgeInsetsGeometry,
  ElevatedButton,
  EnableWidgetInspectorScope,
  EndDrawerButton,
  EndDrawerButtonIcon,
  ExcludeFocus,
  ExcludeFocusTraversal,
  ExcludeSemantics,
  ExpandIcon,
  Expanded,
  ExpansionPanelList,
  ExpansionTile,
  FilledButton,
  FilterChip,
  FittedBox,
  Flex,
  Flexible,
  FlexibleSpaceBar,
  FlexibleSpaceBarSettings,
  FloatingActionButton,
  FlutterLogo,
  Focus,
  FocusScope,
  FocusTraversalGroup,
  FocusableActionDetector,
  Form,
  FractionalTranslation,
  FractionallySizedBox,
  GestureDetector,
  GlowingOverscrollIndicator,
  GridPaper,
  GridTile,
  GridTileBar,
  HeroMode,
  HtmlElementView,
  Icon,
  IconButton,
  Icons,
  IgnoreBaseline,
  IgnorePointer,
  IndexedSemantics,
  IndexedStack,
  InheritedCupertinoTheme,
  Ink,
  InkResponse,
  InkWell,
  InputChip,
  InputDecorationTheme,
  InteractiveViewer,
  IntrinsicHeight,
  IntrinsicWidth,
  KeepAlive,
  KeyedSubtree,
  LicensePage,
  LimitedBox,
  LinearProgressIndicator,
  ListBody,
  ListTile,
  ListTileTheme,
  ListView,
  ListWheelScrollView,
  Listener,
  LongPressDraggable,
  LookupBoundary,
  Magnifier,
  Material,
  MaterialApp,
  MaterialBanner,
  MaterialBannerTheme,
  MaterialButton,
  MenuAcceleratorCallbackBinding,
  MenuAcceleratorLabel,
  MenuAnchor,
  MenuBar,
  MenuItemButton,
  MergeSemantics,
  MergeableMaterial,
  MetaData,
  ModalBarrier,
  MouseRegion,
  NavigationBar,
  NavigationDestination,
  NavigationDrawer,
  NavigationDrawerDestination,
  NavigationRail,
  NavigationToolbar,
  Navigator,
  NavigatorPopHandler,
  NotificationListener,
  Offset,
  Offstage,
  Opacity,
  OutlinedButton,
  OverflowBar,
  OverflowBox,
  Overlay,
  Padding,
  PageView,
  PerformanceOverlay,
  PhysicalModel,
  PinnedHeaderSliver,
  Placeholder,
  PlatformMenuBar,
  PlatformSelectableRegionContextMenu,
  PopScope,
  PopupMenuDivider,
  PopupMenuItem,
  Positioned,
  PositionedDirectional,
  PreferredSize,
  RadioGroup,
  RawChip,
  RawGestureDetector,
  RawImage,
  RawMagnifier,
  RawMaterialButton,
  RawScrollbar,
  RefreshProgressIndicator,
  ReorderableDelayedDragStartListener,
  ReorderableDragStartListener,
  ReorderableListView,
  RepaintBoundary,
  RestorationScope,
  RootRestorationScope,
  RootWidget,
  RotatedBox,
  Row,
  SafeArea,
  Scaffold,
  ScaffoldMessenger,
  ScrollNotificationObserver,
  Scrollbar,
  SearchBar,
  SegmentedButton,
  SelectableText,
  SelectionArea,
  Semantics,
  SemanticsDebugger,
  SensitiveContent,
  SharedAppData,
  ShortcutRegistrar,
  SimpleDialog,
  SimpleDialogOption,
  SingleChildScrollView,
  SizeChangedLayoutNotifier,
  SizedBox,
  SizedOverflowBox,
  Slider,
  SliverAnimatedOpacity,
  SliverAppBar,
  SliverConstrainedCrossAxis,
  SliverCrossAxisExpanded,
  SliverCrossAxisGroup,
  SliverEnsureSemantics,
  SliverFillRemaining,
  SliverFloatingHeader,
  SliverIgnorePointer,
  SliverMainAxisGroup,
  SliverOffstage,
  SliverOpacity,
  SliverPadding,
  SliverResizingHeader,
  SliverSafeArea,
  SliverSemantics,
  SliverToBoxAdapter,
  SliverVisibility,
  SnackBar,
  SnackBarAction,
  Spacer,
  SpellCheckSuggestionsToolbar,
  Stack,
  Stepper,
  StretchEffect,
  StretchingOverscrollIndicator,
  SubmenuButton,
  Switch,
  SwitchListTile,
  Tab,
  TabBar,
  TabBarTheme,
  TabBarView,
  TabPageSelector,
  TabPageSelectorIndicator,
  Table,
  TableCell,
  TableRowInkWell,
  TapRegion,
  TapRegionSurface,
  Text,
  TextButton,
  TextField,
  TextFieldTapRegion,
  TextFormField,
  TextSelectionGestureDetector,
  TextSelectionToolbar,
  TextSelectionToolbarTextButton,
  Texture,
  TickerMode,
  Title,
  ToggleButtons,
  Tooltip,
  TooltipVisibility,
  TreeSliver,
  UiKitView,
  UnconstrainedBox,
  UnmanagedRestorationScope,
  UserAccountsDrawerHeader,
  VerticalDivider,
  ViewAnchor,
  ViewCollection,
  Visibility,
  WidgetsApp,
  Wrap,
} from 'flutter-tsx';

export const examples = [
  <AboutDialog>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </AboutDialog>,
  <AboutListTile>
    <Text>Content</Text>
  </AboutListTile>,
  <AbsorbPointer>
    <Text>Content</Text>
  </AbsorbPointer>,
  <ActionChip label={<Text>Content</Text>} />,
  <AlertDialog />,
  <Align>
    <Text>Content</Text>
  </Align>,
  <AndroidView viewType="example" />,
  <AnimatedAlign
    alignment={AlignmentGeometry.bottomCenter}
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedAlign>,
  <AnimatedContainer
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedContainer>,
  <AnimatedCrossFade
    firstChild={<Text>Content</Text>}
    secondChild={<Text>Content</Text>}
    crossFadeState="showFirst"
    duration={CircularProgressIndicator.defaultAnimationDuration}
  />,
  <AnimatedDefaultTextStyle
    style={CupertinoTextField.cupertinoMisspelledTextStyle}
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedDefaultTextStyle>,
  <AnimatedFractionallySizedBox
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedFractionallySizedBox>,
  <AnimatedOpacity
    opacity={16}
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedOpacity>,
  <AnimatedPadding
    padding={EdgeInsetsGeometry.infinity}
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedPadding>,
  <AnimatedPhysicalModel
    color={Colors.blue}
    shadowColor={Colors.blue}
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedPhysicalModel>,
  <AnimatedPositioned
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedPositioned>,
  <AnimatedPositionedDirectional
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedPositionedDirectional>,
  <AnimatedRotation
    turns={16}
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedRotation>,
  <AnimatedScale
    scale={16}
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedScale>,
  <AnimatedSize duration={CircularProgressIndicator.defaultAnimationDuration}>
    <Text>Content</Text>
  </AnimatedSize>,
  <AnimatedSlide
    offset={Offset.infinite}
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedSlide>,
  <AnimatedSwitcher
    duration={CircularProgressIndicator.defaultAnimationDuration}
  >
    <Text>Content</Text>
  </AnimatedSwitcher>,
  <AppBar />,
  <AppBarTheme>
    <Text>Content</Text>
  </AppBarTheme>,
  <AppKitView viewType="example" />,
  <AspectRatio aspectRatio={16}>
    <Text>Content</Text>
  </AspectRatio>,
  <AutofillGroup>
    <Text>Content</Text>
  </AutofillGroup>,
  <AutomaticKeepAlive>
    <Text>Content</Text>
  </AutomaticKeepAlive>,
  <BackButton />,
  <BackButtonIcon />,
  <BackdropFilter>
    <Text>Content</Text>
  </BackdropFilter>,
  <BackdropGroup>
    <Text>Content</Text>
  </BackdropGroup>,
  <Badge>
    <Text>Content</Text>
  </Badge>,
  <Banner message="example" location="topStart">
    <Text>Content</Text>
  </Banner>,
  <Baseline baseline={16} baselineType="alphabetic">
    <Text>Content</Text>
  </Baseline>,
  <BlockSemantics>
    <Text>Content</Text>
  </BlockSemantics>,
  <BottomAppBar>
    <Text>Content</Text>
  </BottomAppBar>,
  <BottomAppBarTheme>
    <Text>Content</Text>
  </BottomAppBarTheme>,
  <BottomNavigationBar items={[]} />,
  <ButtonBar>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ButtonBar>,
  <ButtonTheme>
    <Text>Content</Text>
  </ButtonTheme>,
  <Card>
    <Text>Content</Text>
  </Card>,
  <CardTheme>
    <Text>Content</Text>
  </CardTheme>,
  <CarouselView itemExtent={16}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CarouselView>,
  <Center>
    <Text>Content</Text>
  </Center>,
  <Checkbox value={true} onChanged={() => {}} />,
  <CheckboxListTile value={true} onChanged={() => {}} />,
  <CheckboxMenuButton value={true} onChanged={() => {}}>
    <Text>Content</Text>
  </CheckboxMenuButton>,
  <CheckedModeBanner>
    <Text>Content</Text>
  </CheckedModeBanner>,
  <CheckedPopupMenuItem>
    <Text>Content</Text>
  </CheckedPopupMenuItem>,
  <Chip label={<Text>Content</Text>} />,
  <ChoiceChip label={<Text>Content</Text>} selected={true} />,
  <CircleAvatar>
    <Text>Content</Text>
  </CircleAvatar>,
  <CircularProgressIndicator />,
  <ClipOval>
    <Text>Content</Text>
  </ClipOval>,
  <ClipPath>
    <Text>Content</Text>
  </ClipPath>,
  <ClipRRect>
    <Text>Content</Text>
  </ClipRRect>,
  <ClipRSuperellipse>
    <Text>Content</Text>
  </ClipRSuperellipse>,
  <ClipRect>
    <Text>Content</Text>
  </ClipRect>,
  <CloseButton />,
  <CloseButtonIcon />,
  <ColoredBox color={Colors.blue}>
    <Text>Content</Text>
  </ColoredBox>,
  <Column>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Column>,
  <Container>
    <Text>Content</Text>
  </Container>,
  <CupertinoActionSheet />,
  <CupertinoActionSheetAction onClick={() => {}}>
    <Text>Content</Text>
  </CupertinoActionSheetAction>,
  <CupertinoActivityIndicator />,
  <CupertinoAlertDialog />,
  <CupertinoApp />,
  <CupertinoButton onClick={() => {}}>
    <Text>Content</Text>
  </CupertinoButton>,
  <CupertinoCheckbox value={true} onChanged={() => {}} />,
  <CupertinoContextMenu actions={[]}>
    <Text>Content</Text>
  </CupertinoContextMenu>,
  <CupertinoContextMenuAction>
    <Text>Content</Text>
  </CupertinoContextMenuAction>,
  <CupertinoDatePicker onDateTimeChanged={() => {}} />,
  <CupertinoDesktopTextSelectionToolbar anchor={Offset.infinite}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoDesktopTextSelectionToolbar>,
  <CupertinoDesktopTextSelectionToolbarButton onClick={() => {}}>
    <Text>Content</Text>
  </CupertinoDesktopTextSelectionToolbarButton>,
  <CupertinoDialogAction>
    <Text>Content</Text>
  </CupertinoDialogAction>,
  <CupertinoExpansionTile title={<Text>Content</Text>}>
    <Text>Content</Text>
  </CupertinoExpansionTile>,
  <CupertinoFormRow>
    <Text>Content</Text>
  </CupertinoFormRow>,
  <CupertinoFormSection>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoFormSection>,
  <CupertinoLinearActivityIndicator progress={16} />,
  <CupertinoListSection>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoListSection>,
  <CupertinoListTile title={<Text>Content</Text>} />,
  <CupertinoListTileChevron />,
  <CupertinoMagnifier />,
  <CupertinoMenuAnchor menuChildren={[]}>
    <Text>Content</Text>
  </CupertinoMenuAnchor>,
  <CupertinoMenuDivider />,
  <CupertinoMenuItem>
    <Text>Content</Text>
  </CupertinoMenuItem>,
  <CupertinoNavigationBar />,
  <CupertinoNavigationBarBackButton />,
  <CupertinoPageScaffold>
    <Text>Content</Text>
  </CupertinoPageScaffold>,
  <CupertinoPageScaffoldBackgroundColor color={Colors.blue}>
    <Text>Content</Text>
  </CupertinoPageScaffoldBackgroundColor>,
  <CupertinoPicker itemExtent={16} onSelectedItemChanged={() => {}}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoPicker>,
  <CupertinoPickerDefaultSelectionOverlay />,
  <CupertinoPopupSurface>
    <Text>Content</Text>
  </CupertinoPopupSurface>,
  <CupertinoScrollbar>
    <Text>Content</Text>
  </CupertinoScrollbar>,
  <CupertinoSearchTextField />,
  <CupertinoSlider value={16} onChanged={() => {}} />,
  <CupertinoSliverNavigationBar />,
  <CupertinoSliverRefreshControl />,
  <CupertinoSwitch value={true} onChanged={() => {}} />,
  <CupertinoTabBar items={[]} />,
  <CupertinoTabView />,
  <CupertinoTextField />,
  <CupertinoTextFormFieldRow />,
  <CupertinoTextSelectionToolbar
    anchorAbove={Offset.infinite}
    anchorBelow={Offset.infinite}
  >
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </CupertinoTextSelectionToolbar>,
  <CupertinoTextSelectionToolbarButton>
    <Text>Content</Text>
  </CupertinoTextSelectionToolbarButton>,
  <CupertinoTimerPicker onTimerDurationChanged={() => {}} />,
  <CupertinoUserInterfaceLevel data="base">
    <Text>Content</Text>
  </CupertinoUserInterfaceLevel>,
  <CustomPaint>
    <Text>Content</Text>
  </CustomPaint>,
  <CustomScrollView />,
  <DataTable columns={[]} rows={[]} />,
  <DefaultSelectionStyle>
    <Text>Content</Text>
  </DefaultSelectionStyle>,
  <DefaultTabController length={8}>
    <Text>Content</Text>
  </DefaultTabController>,
  <DefaultTextEditingShortcuts>
    <Text>Content</Text>
  </DefaultTextEditingShortcuts>,
  <DefaultTextStyle style={CupertinoTextField.cupertinoMisspelledTextStyle}>
    <Text>Content</Text>
  </DefaultTextStyle>,
  <DesktopTextSelectionToolbar anchor={Offset.infinite}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </DesktopTextSelectionToolbar>,
  <DesktopTextSelectionToolbarButton onClick={() => {}}>
    <Text>Content</Text>
  </DesktopTextSelectionToolbarButton>,
  <Dialog>
    <Text>Content</Text>
  </Dialog>,
  <DialogTheme>
    <Text>Content</Text>
  </DialogTheme>,
  <Directionality textDirection="rtl">
    <Text>Content</Text>
  </Directionality>,
  <DisableWidgetInspectorScope>
    <Text>Content</Text>
  </DisableWidgetInspectorScope>,
  <Dismissible>
    <Text>Content</Text>
  </Dismissible>,
  <DisplayFeatureSubScreen>
    <Text>Content</Text>
  </DisplayFeatureSubScreen>,
  <Divider />,
  <DragBoundary>
    <Text>Content</Text>
  </DragBoundary>,
  <Draggable feedback={<Text>Content</Text>}>
    <Text>Content</Text>
  </Draggable>,
  <DraggableScrollableActuator>
    <Text>Content</Text>
  </DraggableScrollableActuator>,
  <Drawer>
    <Text>Content</Text>
  </Drawer>,
  <DrawerButton />,
  <DrawerButtonIcon />,
  <DrawerController alignment="start">
    <Text>Content</Text>
  </DrawerController>,
  <DrawerHeader>
    <Text>Content</Text>
  </DrawerHeader>,
  <DropdownButton items={[]} onChanged={() => {}} />,
  <DropdownButtonFormField items={[]} onChanged={() => {}} />,
  <DropdownButtonHideUnderline>
    <Text>Content</Text>
  </DropdownButtonHideUnderline>,
  <DropdownMenu dropdownMenuEntries={[]} />,
  <DropdownMenuFormField dropdownMenuEntries={[]} />,
  <DropdownMenuItem>
    <Text>Content</Text>
  </DropdownMenuItem>,
  <ElevatedButton onClick={() => {}}>
    <Text>Content</Text>
  </ElevatedButton>,
  <EnableWidgetInspectorScope>
    <Text>Content</Text>
  </EnableWidgetInspectorScope>,
  <EndDrawerButton />,
  <EndDrawerButtonIcon />,
  <ExcludeFocus>
    <Text>Content</Text>
  </ExcludeFocus>,
  <ExcludeFocusTraversal>
    <Text>Content</Text>
  </ExcludeFocusTraversal>,
  <ExcludeSemantics>
    <Text>Content</Text>
  </ExcludeSemantics>,
  <ExpandIcon onClick={() => {}} />,
  <Expanded>
    <Text>Content</Text>
  </Expanded>,
  <ExpansionPanelList />,
  <ExpansionTile title={<Text>Content</Text>}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ExpansionTile>,
  <FilledButton onClick={() => {}}>
    <Text>Content</Text>
  </FilledButton>,
  <FilterChip label={<Text>Content</Text>} onSelected={() => {}} />,
  <FittedBox>
    <Text>Content</Text>
  </FittedBox>,
  <Flex direction="horizontal">
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Flex>,
  <Flexible>
    <Text>Content</Text>
  </Flexible>,
  <FlexibleSpaceBar />,
  <FlexibleSpaceBarSettings
    toolbarOpacity={16}
    minExtent={16}
    maxExtent={16}
    currentExtent={16}
  >
    <Text>Content</Text>
  </FlexibleSpaceBarSettings>,
  <FloatingActionButton onClick={() => {}}>
    <Text>Content</Text>
  </FloatingActionButton>,
  <FlutterLogo />,
  <Focus>
    <Text>Content</Text>
  </Focus>,
  <FocusScope>
    <Text>Content</Text>
  </FocusScope>,
  <FocusTraversalGroup>
    <Text>Content</Text>
  </FocusTraversalGroup>,
  <FocusableActionDetector>
    <Text>Content</Text>
  </FocusableActionDetector>,
  <Form>
    <Text>Content</Text>
  </Form>,
  <FractionalTranslation translation={Offset.infinite}>
    <Text>Content</Text>
  </FractionalTranslation>,
  <FractionallySizedBox>
    <Text>Content</Text>
  </FractionallySizedBox>,
  <GestureDetector>
    <Text>Content</Text>
  </GestureDetector>,
  <GlowingOverscrollIndicator axisDirection="up" color={Colors.blue}>
    <Text>Content</Text>
  </GlowingOverscrollIndicator>,
  <GridPaper>
    <Text>Content</Text>
  </GridPaper>,
  <GridTile>
    <Text>Content</Text>
  </GridTile>,
  <GridTileBar />,
  <HeroMode>
    <Text>Content</Text>
  </HeroMode>,
  <HtmlElementView viewType="example" />,
  <Icon icon={Icons.add} />,
  <IconButton onClick={() => {}} icon={<Text>Content</Text>} />,
  <IgnoreBaseline>
    <Text>Content</Text>
  </IgnoreBaseline>,
  <IgnorePointer>
    <Text>Content</Text>
  </IgnorePointer>,
  <IndexedSemantics index={8}>
    <Text>Content</Text>
  </IndexedSemantics>,
  <IndexedStack>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </IndexedStack>,
  <InheritedCupertinoTheme theme={<Text>Content</Text>}>
    <Text>Content</Text>
  </InheritedCupertinoTheme>,
  <Ink>
    <Text>Content</Text>
  </Ink>,
  <InkResponse>
    <Text>Content</Text>
  </InkResponse>,
  <InkWell>
    <Text>Content</Text>
  </InkWell>,
  <InputChip label={<Text>Content</Text>} />,
  <InputDecorationTheme>
    <Text>Content</Text>
  </InputDecorationTheme>,
  <InteractiveViewer>
    <Text>Content</Text>
  </InteractiveViewer>,
  <IntrinsicHeight>
    <Text>Content</Text>
  </IntrinsicHeight>,
  <IntrinsicWidth>
    <Text>Content</Text>
  </IntrinsicWidth>,
  <KeepAlive keepAlive={true}>
    <Text>Content</Text>
  </KeepAlive>,
  <KeyedSubtree>
    <Text>Content</Text>
  </KeyedSubtree>,
  <LicensePage />,
  <LimitedBox>
    <Text>Content</Text>
  </LimitedBox>,
  <LinearProgressIndicator />,
  <ListBody>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ListBody>,
  <ListTile />,
  <ListTileTheme>
    <Text>Content</Text>
  </ListTileTheme>,
  <ListView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ListView>,
  <ListWheelScrollView itemExtent={16}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ListWheelScrollView>,
  <Listener>
    <Text>Content</Text>
  </Listener>,
  <LongPressDraggable feedback={<Text>Content</Text>}>
    <Text>Content</Text>
  </LongPressDraggable>,
  <LookupBoundary>
    <Text>Content</Text>
  </LookupBoundary>,
  <Magnifier />,
  <Material>
    <Text>Content</Text>
  </Material>,
  <MaterialApp />,
  <MaterialBanner content={<Text>Content</Text>} actions={[]} />,
  <MaterialBannerTheme>
    <Text>Content</Text>
  </MaterialBannerTheme>,
  <MaterialButton onClick={() => {}}>
    <Text>Content</Text>
  </MaterialButton>,
  <MenuAcceleratorCallbackBinding>
    <Text>Content</Text>
  </MenuAcceleratorCallbackBinding>,
  <MenuAcceleratorLabel>Hello world</MenuAcceleratorLabel>,
  <MenuAnchor menuChildren={[]}>
    <Text>Content</Text>
  </MenuAnchor>,
  <MenuBar>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </MenuBar>,
  <MenuItemButton>
    <Text>Content</Text>
  </MenuItemButton>,
  <MergeSemantics>
    <Text>Content</Text>
  </MergeSemantics>,
  <MergeableMaterial />,
  <MetaData>
    <Text>Content</Text>
  </MetaData>,
  <ModalBarrier />,
  <MouseRegion>
    <Text>Content</Text>
  </MouseRegion>,
  <NavigationBar destinations={[]} />,
  <NavigationDestination icon={<Text>Content</Text>} label="example" />,
  <NavigationDrawer>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </NavigationDrawer>,
  <NavigationDrawerDestination
    icon={<Text>Content</Text>}
    label={<Text>Content</Text>}
  />,
  <NavigationRail destinations={[]} selectedIndex={8} />,
  <NavigationToolbar />,
  <Navigator />,
  <NavigatorPopHandler>
    <Text>Content</Text>
  </NavigatorPopHandler>,
  <NotificationListener>
    <Text>Content</Text>
  </NotificationListener>,
  <Offstage>
    <Text>Content</Text>
  </Offstage>,
  <Opacity opacity={16}>
    <Text>Content</Text>
  </Opacity>,
  <OutlinedButton onClick={() => {}}>
    <Text>Content</Text>
  </OutlinedButton>,
  <OverflowBar>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </OverflowBar>,
  <OverflowBox>
    <Text>Content</Text>
  </OverflowBox>,
  <Overlay />,
  <Padding padding={EdgeInsetsGeometry.infinity}>
    <Text>Content</Text>
  </Padding>,
  <PageView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </PageView>,
  <PerformanceOverlay />,
  <PhysicalModel color={Colors.blue}>
    <Text>Content</Text>
  </PhysicalModel>,
  <PinnedHeaderSliver>
    <Text>Content</Text>
  </PinnedHeaderSliver>,
  <Placeholder>
    <Text>Content</Text>
  </Placeholder>,
  <PlatformMenuBar menus={[]}>
    <Text>Content</Text>
  </PlatformMenuBar>,
  <PlatformSelectableRegionContextMenu>
    <Text>Content</Text>
  </PlatformSelectableRegionContextMenu>,
  <PopScope>
    <Text>Content</Text>
  </PopScope>,
  <PopupMenuDivider />,
  <PopupMenuItem>
    <Text>Content</Text>
  </PopupMenuItem>,
  <Positioned>
    <Text>Content</Text>
  </Positioned>,
  <PositionedDirectional>
    <Text>Content</Text>
  </PositionedDirectional>,
  <PreferredSize preferredSize={CupertinoMagnifier.kDefaultSize}>
    <Text>Content</Text>
  </PreferredSize>,
  <RadioGroup onChanged={() => {}}>
    <Text>Content</Text>
  </RadioGroup>,
  <RawChip label={<Text>Content</Text>} />,
  <RawGestureDetector>
    <Text>Content</Text>
  </RawGestureDetector>,
  <RawImage />,
  <RawMagnifier size={CupertinoMagnifier.kDefaultSize}>
    <Text>Content</Text>
  </RawMagnifier>,
  <RawMaterialButton onClick={() => {}}>
    <Text>Content</Text>
  </RawMaterialButton>,
  <RawScrollbar>
    <Text>Content</Text>
  </RawScrollbar>,
  <RefreshProgressIndicator />,
  <ReorderableDelayedDragStartListener index={8}>
    <Text>Content</Text>
  </ReorderableDelayedDragStartListener>,
  <ReorderableDragStartListener index={8}>
    <Text>Content</Text>
  </ReorderableDragStartListener>,
  <ReorderableListView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ReorderableListView>,
  <RepaintBoundary>
    <Text>Content</Text>
  </RepaintBoundary>,
  <RestorationScope restorationId="example">
    <Text>Content</Text>
  </RestorationScope>,
  <RootRestorationScope restorationId="example">
    <Text>Content</Text>
  </RootRestorationScope>,
  <RootWidget>
    <Text>Content</Text>
  </RootWidget>,
  <RotatedBox quarterTurns={8}>
    <Text>Content</Text>
  </RotatedBox>,
  <Row>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Row>,
  <SafeArea>
    <Text>Content</Text>
  </SafeArea>,
  <Scaffold />,
  <ScaffoldMessenger>
    <Text>Content</Text>
  </ScaffoldMessenger>,
  <ScrollNotificationObserver>
    <Text>Content</Text>
  </ScrollNotificationObserver>,
  <Scrollbar>
    <Text>Content</Text>
  </Scrollbar>,
  <SearchBar />,
  <SegmentedButton segments={[]} selected={[]} />,
  <SelectableText>Hello world</SelectableText>,
  <SelectionArea>
    <Text>Content</Text>
  </SelectionArea>,
  <Semantics>
    <Text>Content</Text>
  </Semantics>,
  <SemanticsDebugger>
    <Text>Content</Text>
  </SemanticsDebugger>,
  <SensitiveContent sensitivity="autoSensitive">
    <Text>Content</Text>
  </SensitiveContent>,
  <SharedAppData>
    <Text>Content</Text>
  </SharedAppData>,
  <ShortcutRegistrar>
    <Text>Content</Text>
  </ShortcutRegistrar>,
  <SimpleDialog>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </SimpleDialog>,
  <SimpleDialogOption>
    <Text>Content</Text>
  </SimpleDialogOption>,
  <SingleChildScrollView>
    <Text>Content</Text>
  </SingleChildScrollView>,
  <SizeChangedLayoutNotifier>
    <Text>Content</Text>
  </SizeChangedLayoutNotifier>,
  <SizedBox>
    <Text>Content</Text>
  </SizedBox>,
  <SizedOverflowBox size={CupertinoMagnifier.kDefaultSize}>
    <Text>Content</Text>
  </SizedOverflowBox>,
  <Slider value={16} onChanged={() => {}} />,
  <SliverAnimatedOpacity
    opacity={16}
    duration={CircularProgressIndicator.defaultAnimationDuration}
  />,
  <SliverAppBar />,
  <SliverConstrainedCrossAxis maxExtent={16} sliver={<Text>Content</Text>} />,
  <SliverCrossAxisExpanded flex={8} sliver={<Text>Content</Text>} />,
  <SliverCrossAxisGroup slivers={[]} />,
  <SliverEnsureSemantics sliver={<Text>Content</Text>} />,
  <SliverFillRemaining>
    <Text>Content</Text>
  </SliverFillRemaining>,
  <SliverFloatingHeader>
    <Text>Content</Text>
  </SliverFloatingHeader>,
  <SliverIgnorePointer />,
  <SliverMainAxisGroup slivers={[]} />,
  <SliverOffstage />,
  <SliverOpacity opacity={16} />,
  <SliverPadding padding={EdgeInsetsGeometry.infinity} />,
  <SliverResizingHeader>
    <Text>Content</Text>
  </SliverResizingHeader>,
  <SliverSafeArea sliver={<Text>Content</Text>} />,
  <SliverSemantics sliver={<Text>Content</Text>} />,
  <SliverToBoxAdapter>
    <Text>Content</Text>
  </SliverToBoxAdapter>,
  <SliverVisibility sliver={<Text>Content</Text>} />,
  <SnackBar content={<Text>Content</Text>} />,
  <SnackBarAction label="example" onClick={() => {}} />,
  <Spacer />,
  <SpellCheckSuggestionsToolbar anchor={Offset.infinite} buttonItems={[]} />,
  <Stack>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Stack>,
  <Stepper steps={[]} />,
  <StretchEffect axis="horizontal">
    <Text>Content</Text>
  </StretchEffect>,
  <StretchingOverscrollIndicator axisDirection="up">
    <Text>Content</Text>
  </StretchingOverscrollIndicator>,
  <SubmenuButton menuChildren={[]}>
    <Text>Content</Text>
  </SubmenuButton>,
  <Switch value={true} onChanged={() => {}} />,
  <SwitchListTile value={true} onChanged={() => {}} />,
  <Tab>
    <Text>Content</Text>
  </Tab>,
  <TabBar tabs={[]} />,
  <TabBarTheme>
    <Text>Content</Text>
  </TabBarTheme>,
  <TabBarView>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </TabBarView>,
  <TabPageSelector />,
  <TabPageSelectorIndicator
    backgroundColor={Colors.blue}
    borderColor={Colors.blue}
    size={16}
  />,
  <Table />,
  <TableCell>
    <Text>Content</Text>
  </TableCell>,
  <TableRowInkWell>
    <Text>Content</Text>
  </TableRowInkWell>,
  <TapRegion>
    <Text>Content</Text>
  </TapRegion>,
  <TapRegionSurface>
    <Text>Content</Text>
  </TapRegionSurface>,
  <Text>Hello world</Text>,
  <TextButton onClick={() => {}}>
    <Text>Content</Text>
  </TextButton>,
  <TextField />,
  <TextFieldTapRegion>
    <Text>Content</Text>
  </TextFieldTapRegion>,
  <TextFormField />,
  <TextSelectionGestureDetector>
    <Text>Content</Text>
  </TextSelectionGestureDetector>,
  <TextSelectionToolbar
    anchorAbove={Offset.infinite}
    anchorBelow={Offset.infinite}
  >
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </TextSelectionToolbar>,
  <TextSelectionToolbarTextButton padding={EdgeInsetsGeometry.infinity}>
    <Text>Content</Text>
  </TextSelectionToolbarTextButton>,
  <Texture textureId={8} />,
  <TickerMode enabled={true}>
    <Text>Content</Text>
  </TickerMode>,
  <Title color={Colors.blue}>
    <Text>Content</Text>
  </Title>,
  <ToggleButtons isSelected={[]}>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </ToggleButtons>,
  <Tooltip>
    <Text>Content</Text>
  </Tooltip>,
  <TooltipVisibility visible={true}>
    <Text>Content</Text>
  </TooltipVisibility>,
  <TreeSliver tree={[]} />,
  <UiKitView viewType="example" />,
  <UnconstrainedBox>
    <Text>Content</Text>
  </UnconstrainedBox>,
  <UnmanagedRestorationScope>
    <Text>Content</Text>
  </UnmanagedRestorationScope>,
  <UserAccountsDrawerHeader
    accountName={<Text>Content</Text>}
    accountEmail={<Text>Content</Text>}
  />,
  <VerticalDivider />,
  <ViewAnchor>
    <Text>Content</Text>
  </ViewAnchor>,
  <ViewCollection views={[]} />,
  <Visibility>
    <Text>Content</Text>
  </Visibility>,
  <WidgetsApp color={Colors.blue} />,
  <Wrap>
    <Text>Item 1</Text>
    <Text>Item 2</Text>
  </Wrap>,
];
