import { mkdtemp, readdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, relative } from 'node:path';

import { describe, expect, test } from 'bun:test';

import { exampleFiles, examplesIndex, writeExamples } from '@src/cli/examples';
import { loadTemplate, TEMPLATE_NAMES } from '@src/cli/templates';

const EXAMPLES_DIR = new URL('../../../../examples/', import.meta.url).pathname;

const committedFiles = async (directory: string): Promise<string[]> => {
  const entries = await readdir(directory, {
    recursive: true,
    withFileTypes: true,
  });
  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => relative(directory, join(entry.parentPath, entry.name)))
    .sort();
};

// The examples in the repository are what `fsx init --template=<name>`
// writes — generated by `bun run examples`, never edited by hand. Checking
// them here means the four apps a newcomer reads are the four apps the CLI
// actually produces, down to the byte.
describe('writeExamples', () => {
  test('writes every template into a directory of its own', async () => {
    const into = await mkdtemp(join(tmpdir(), 'fsx-examples-'));

    const written = await writeExamples(into);

    expect(written).toContain('README.md');
    expect(written).toContain(join('web', 'src', 'routes.tsx'));
    expect(await Bun.file(join(into, 'README.md')).text()).toBe(
      examplesIndex(
        await Promise.all(TEMPLATE_NAMES.map((name) => loadTemplate(name))),
      ),
    );
    expect(await committedFiles(join(into, 'tray'))).toEqual(
      exampleFiles(await loadTemplate('tray'))
        .map((file) => file.path)
        .sort(),
    );

    // Writing again over what is there leaves exactly the same tree.
    expect(await writeExamples(into)).toEqual(written);

    await rm(into, { recursive: true, force: true });
  }, 60000);
});

describe('the committed examples are what the templates scaffold', () => {
  test('examples/README.md lists every template', async () => {
    const templates = await Promise.all(
      TEMPLATE_NAMES.map((name) => loadTemplate(name)),
    );

    expect(await Bun.file(join(EXAMPLES_DIR, 'README.md')).text()).toBe(
      examplesIndex(templates),
    );
  });

  for (const name of TEMPLATE_NAMES) {
    test(`examples/${name} is byte-identical to its template`, async () => {
      const template = await loadTemplate(name);
      const directory = join(EXAMPLES_DIR, name);
      const expected = exampleFiles(template);

      expect(await committedFiles(directory)).toEqual(
        expected.map((file) => file.path).sort(),
      );

      for (const file of expected) {
        expect(await Bun.file(join(directory, file.path)).text()).toBe(
          file.contents,
        );
      }
    });
  }
});
