import type { SiteWidget } from './model';
import { exampleImports, exampleSource } from './synthesize';

export const emitExampleProbe = (page: { widgets: SiteWidget[] }): string => {
  const complete = page.widgets.filter((widget) => widget.example.complete);
  const values = new Set<string>();
  const types = new Set<string>();
  for (const widget of complete) {
    const imports = exampleImports(widget.name, widget.example);
    for (const name of imports.values) {
      values.add(name);
    }
    for (const name of imports.types) {
      types.add(name);
    }
  }
  const typeImport = [...types].filter((name) => !values.has(name)).sort();

  return [
    '// GENERATED by `bun run docs` from the synthesized API-reference examples',
    '// — do not edit. Checked by `tsc`: every complete example must typecheck',
    '// against the published package surface.',
    ...(typeImport.length === 0
      ? []
      : [`import type { ${typeImport.join(', ')} } from 'flutter-tsx';`]),
    `import { ${[...values].sort().join(', ')} } from 'flutter-tsx';`,
    '',
    ...complete.map(
      (widget) =>
        `${exampleSource(widget.name, widget.example, { component: true })}\n`,
    ),
  ].join('\n');
};
