import type { SiteWidget } from './model';
import { exampleImports, exampleSource } from './synthesize';

export const emitExampleProbe = (page: { widgets: SiteWidget[] }): string => {
  const complete = page.widgets.filter((widget) => widget.example.complete);
  const identifiers = new Set<string>();
  for (const widget of complete) {
    for (const name of exampleImports(widget.name, widget.example)) {
      identifiers.add(name);
    }
  }

  return [
    '// GENERATED by `bun run docs` from the synthesized API-reference examples',
    '// — do not edit. Checked by `tsc`: every complete example must typecheck',
    '// against the published package surface.',
    `import { ${[...identifiers].sort().join(', ')} } from 'flutter-tsx';`,
    '',
    ...complete.map(
      (widget) =>
        `${exampleSource(widget.name, widget.example, { component: true })}\n`,
    ),
  ].join('\n');
};
