import type { SitePage } from './model';

const NAMESPACE_REFERENCE = /\{([A-Z][A-Za-z0-9_]*)\./g;

export const emitExampleProbe = (page: SitePage): string => {
  const complete = page.widgets.filter((widget) => widget.exampleComplete);

  const identifiers = new Set<string>(['Text']);
  for (const widget of complete) {
    identifiers.add(widget.name);
    for (const match of widget.tsxExample.matchAll(NAMESPACE_REFERENCE)) {
      identifiers.add(match[1] ?? '');
    }
  }
  identifiers.delete('');

  const imports = [...identifiers].sort().join(', ');
  const entries = complete
    .map((widget) => `  ${widget.tsxExample.replaceAll('\n', '\n  ')},`)
    .join('\n');

  return [
    '// GENERATED by `bun run docs` from the synthesized API-reference examples',
    '// — do not edit. Checked by `tsc`: every complete example must typecheck',
    '// against the published package surface.',
    `import { ${imports} } from 'flutter-tsx';`,
    '',
    'export const examples = [',
    entries,
    '];',
    '',
  ].join('\n');
};
