import { describe, expect, test } from 'bun:test';

import { loadPluginApi, type PluginApi } from '@src/plugins/api';
import { emitPluginDeclaration } from '@src/plugins/emit-types';
import { deriveHooks } from '@src/plugins/hooks';
import { PLUGIN_OVERRIDES } from '@src/plugins/overrides';

describe('emitPluginDeclaration', () => {
  test('a small api emits the complete ambient module', () => {
    const api: PluginApi = {
      package: 'demo',
      version: '1.2.3',
      classes: [
        {
          name: 'DemoController',
          doc: '/// Controls demos.',
          constructors: [
            {
              name: '',
              doc: '',
              isConst: false,
              paramMemberAsserts: false,
              params: [
                {
                  name: 'mode',
                  type: { kind: 'enum', name: 'DemoMode' },
                  display: 'DemoMode',
                  named: false,
                  required: true,
                  defaultValue: null,
                  doc: '',
                  deprecated: false,
                },
                {
                  name: 'loud',
                  type: { kind: 'scalar', name: 'bool' },
                  display: 'bool',
                  named: true,
                  required: false,
                  defaultValue: 'false',
                  doc: '',
                  deprecated: false,
                },
              ],
            },
          ],
          methods: [
            {
              name: 'dispose',
              doc: '',
              isStatic: false,
              returnType: { kind: 'future', item: { kind: 'void' } },
              params: [],
            },
            {
              name: 'initialize',
              doc: '',
              isStatic: false,
              returnType: { kind: 'future', item: { kind: 'void' } },
              params: [],
            },
            {
              name: 'run',
              doc: '/// Runs once.',
              isStatic: false,
              returnType: {
                kind: 'future',
                item: { kind: 'named', name: 'Report' },
              },
              params: [],
            },
          ],
          constants: [],
        },
      ],
      enums: [{ name: 'DemoMode', values: ['off', 'on'] }],
      functions: [
        {
          name: 'availableDemoControllers',
          doc: '',
          isStatic: false,
          returnType: {
            kind: 'future',
            item: {
              kind: 'list',
              item: { kind: 'named', name: 'DemoController' },
            },
          },
          params: [
            {
              name: 'region',
              type: { kind: 'named', name: 'Region' },
              display: 'Region',
              named: false,
              required: true,
              defaultValue: null,
              doc: '',
              deprecated: false,
            },
          ],
        },
      ],
    };
    const hooks = [
      {
        hookName: 'useDemo',
        className: 'DemoController',
        dartImport: 'package:demo/demo.dart',
        acquisition: { kind: 'constructor' as const },
        construct: [],
        managed: ['initialize', 'dispose'],
        options: [
          {
            name: 'mode',
            enumName: 'DemoMode',
            values: ['off', 'on'],
            defaultMember: 'off',
          },
        ],
      },
    ];

    expect(emitPluginDeclaration(api, hooks)).toBe(
      `// GENERATED by \`bun run generate:plugin demo\` from ref/plugins/demo.json — do not edit.
// demo 1.2.3

declare module 'plugin:demo' {
  export type DemoMode = 'off' | 'on';

  export interface Region {
    readonly __external: 'Region';
  }

  export interface Report {
    readonly __external: 'Report';
  }

  export class DemoController {
    constructor(mode: DemoMode, options?: { loud?: boolean });
    dispose(): Promise<void>;
    initialize(): Promise<void>;
    run(): Promise<Report>;
  }

  export const availableDemoControllers: (region: Region) => Promise<DemoController[]>;

  export const useDemo: (options?: { mode?: DemoMode }) => Omit<DemoController, 'initialize' | 'dispose'>;
}
`,
    );
  });

  test('the committed camera declaration is byte-fresh', async () => {
    const api = await loadPluginApi('camera');
    const hooks = deriveHooks(api, PLUGIN_OVERRIDES.camera);
    const committed = await Bun.file(
      new URL('../fixtures/types/camera.d.ts', import.meta.url),
    ).text();

    expect(committed).toBe(emitPluginDeclaration(api, hooks));
  });
});
