import { describe, expect, test } from 'bun:test';

import {
  planPluginSync,
  readPluginDependencies,
  resolvedVersions,
} from '@src/plugins/install';

describe('readPluginDependencies', () => {
  test('reads the plugins map', () => {
    expect(
      readPluginDependencies(
        '{"name":"demo","plugins":{"camera":"^0.12.0","url_launcher":"^6.3.0"}}',
        'package.json',
      ),
    ).toEqual({ camera: '^0.12.0', url_launcher: '^6.3.0' });
  });

  test('treats a manifest without a plugins map as declaring none', () => {
    expect(readPluginDependencies('{"name":"demo"}', 'package.json')).toEqual(
      {},
    );
  });

  test('rejects a manifest that is not valid JSON', () => {
    expect(() => readPluginDependencies('{', 'package.json')).toThrow(
      'package.json is not valid JSON.',
    );
  });

  test('rejects a manifest that is valid JSON but not an object', () => {
    expect(() => readPluginDependencies('7', 'package.json')).toThrow(
      'package.json is not valid JSON.',
    );
  });

  test('rejects a plugins map that is not an object', () => {
    expect(() =>
      readPluginDependencies('{"plugins":[]}', 'package.json'),
    ).toThrow('package.json: "plugins" must be an object of pub constraints.');
  });

  test('rejects a constraint that is not a string', () => {
    expect(() =>
      readPluginDependencies('{"plugins":{"camera":12}}', 'package.json'),
    ).toThrow('package.json: "plugins.camera" must be a version constraint.');
  });
});

describe('planPluginSync', () => {
  test('adds newly declared plugins', () => {
    expect(planPluginSync({ camera: '^0.12.0' }, {})).toEqual({
      add: ['camera@^0.12.0'],
      remove: [],
    });
  });

  test('re-adds a plugin whose constraint changed', () => {
    expect(
      planPluginSync({ camera: '^0.12.1' }, { camera: '^0.12.0' }),
    ).toEqual({ add: ['camera@^0.12.1'], remove: [] });
  });

  test('leaves an unchanged plugin alone', () => {
    expect(
      planPluginSync({ camera: '^0.12.0' }, { camera: '^0.12.0' }),
    ).toEqual({ add: [], remove: [] });
  });

  test('removes a plugin that is no longer declared', () => {
    expect(planPluginSync({}, { camera: '^0.12.0' })).toEqual({
      add: [],
      remove: ['camera'],
    });
  });

  test('orders both lists so the commands it drives are deterministic', () => {
    expect(
      planPluginSync(
        { url_launcher: '^6.3.0', camera: '^0.12.0' },
        { shared_preferences: '^2.0.0', http: '^1.0.0' },
      ),
    ).toEqual({
      add: ['camera@^0.12.0', 'url_launcher@^6.3.0'],
      remove: ['http', 'shared_preferences'],
    });
  });
});

describe('resolvedVersions', () => {
  const LOCK = `# Generated by pub
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "abc"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  url_launcher:
    dependency: "direct main"
    description:
      name: url_launcher
      sha256: "def"
      url: "https://pub.dev"
    source: hosted
    version: "6.3.2"
sdks:
  dart: ">=3.4.0 <4.0.0"
`;

  test('reads the resolved version of every locked package', () => {
    expect(resolvedVersions(LOCK)).toEqual({
      async: '2.11.0',
      url_launcher: '6.3.2',
    });
  });

  test('reads an unquoted version', () => {
    expect(
      resolvedVersions(
        'packages:\n  http:\n    source: hosted\n    version: 1.2.0\n',
      ),
    ).toEqual({ http: '1.2.0' });
  });

  test('is empty when nothing is locked', () => {
    expect(resolvedVersions('packages: {}\nsdks:\n  dart: "any"\n')).toEqual(
      {},
    );
  });
});
